.github/ISSUE_TEMPLATE/---bug-report.md
.github/ISSUE_TEMPLATE/---feature-request.md
.github/ISSUE_TEMPLATE/--question.md

Update some templates for github issues/pr/question
Related to #10

Update github templates

---

akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowMergeAllSpec.scala

Was: https://github.com/mdedetrich/akka-apache/pull/6

=str Update FlowMergeAllSpec because the merge order is undefined.

---

.asf.yaml

https://lists.apache.org/thread/jrqjdshp9vll8o75drdrynzk4b670vtn

use notifications mailing list for issues and PRs

---

CONTRIBUTING.md
README.md
RELEASING.md

Updated three markdown files:
- CONTRIBUTING.md
- README.md
- RELEASING.md

Updated references from akka to pekko #28

---

akka-docs/src/test/scala-jdk9-only/docs/stream/operators/source/AsSubscriber.scala
akka-docs/src/test/scala-jdk9-only/docs/stream/operators/source/FromPublisher.scala

Remove unneeded semicolons

---

project/MiMa.scala

mima checks still seem to kick in

set mimaPreviousArtifacts := Set.empty to disable mima checks

---

project/MultiNode.scala
project/SigarLoader.scala

Rename akka to pekko in system properties

---

project/ValidatePullRequest.scala

When https://github.com/apache/incubator-pekko/pull/62 was merged it caused a regression due to sbt's implicit behaviour of having the sbt project id the same as the project name if the project name is not explicitly set along with assuming project dir = project name (technically there is no such relation in sbt). With the rename of `akka-docs` to `docs` this caused the `akka-*` filter to break for the `docs` folder.
This PR solves the problem by using a more principled approach, i.e. rather than assuming every sbt project is within a project dir that starts with akka we just directly grab all of the sbt projects and create a filter out of it.
Its possible to verify this PR by adding a `println(directory)` to see the printed project names, i.e. on my system it prints out
``` …
```

Fix regression with doc dir rename

---

actor/src/main/scala/org/apache/pekko/actor/ActorSystem.scala
project/GitHub.scala
project/project-info.conf
stream/src/main/scala/org/apache/pekko/stream/StreamRefs.scala

* mainly affects docs - and links in the docs

fix some stray akka refs

---

actor-tests/src/test/scala/org/apache/pekko/util/ByteStringSpec.scala
actor/src/main/scala/org/apache/pekko/actor/ActorSelection.scala
actor/src/main/scala/org/apache/pekko/actor/ActorSystem.scala
actor/src/main/scala/org/apache/pekko/util/ManifestInfo.scala
build.sbt
project/JdkOptions.scala
project/Publish.scala
remote/src/test/resources/aeron.properties
remote/src/test/scala/org/apache/pekko/remote/artery/tcp/ssl/PemManagersProviderSpec.scala
stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/BoundedSourceQueueSpec.scala

https://github.com/apache/incubator-pekko/issues/115

use Apache Pekko name for version check

---

.github/workflows/publish-nightly.yml
project/Publish.scala

Publish nightlies to Apache Nexus Repository

---

docs/src/main/paradox/common/other-modules.md
docs/src/main/paradox/general/configuration-reference.md

- Discussion: https://lists.apache.org/thread/8orjtlx2w42y3j45pswmf9nbtf64gp77
- Issue: #122

Remove Akka-Enhancements relevant docs

---

cluster/jmx-client/pekko-cluster

Rename akka refs in pekko-cluster script

---

docs/src/main/paradox/additional/books.md

Hopefully, we'll have some Pekko stuff for this page soon.

link to akka docs for the akka books info

---

.asf.yaml

https://lists.apache.org/thread/cx3t7g9rs44tchoz4jytb74sdtlq16zk

enable github projects feature

---

docs/src/main/paradox/persistence.md
docs/src/main/paradox/project/migration-guides.md

Early placeholder for https://github.com/apache/incubator-pekko/issues/109

stub of migration documentation

---

.github/workflows/binary-compatibility-checks.yml
.github/workflows/build-test-prValidation.yml
.github/workflows/format.yml
.github/workflows/link-validator.yml
.github/workflows/multi-node.yml
.github/workflows/nightly-builds.yml
.github/workflows/publish-nightly.yml
.github/workflows/publish.yml
.github/workflows/scala3-build.yml
.github/workflows/scala3-compile.yml
.github/workflows/timing-tests.yml

related to https://github.com/apache/incubator-pekko-connectors-kafka/pull/26

replace use of unmaintained setup-scala action

---

build.sbt
project/plugins.sbt

Adds the prototype source dist plugin which generates source packages for Apache

Add SourceDistPlugin for creating source packages

---

.github/workflows/publish-nightly.yml

Resolves: https://github.com/apache/incubator-pekko/issues/149

publish documentation during nightlies

---

DISCLAIMER
project/MetaInfLicenseNoticeCopy.scala

https://incubator.apache.org/policy/incubation.html#disclaimers

add DISCLAIMER

---

.github/workflows/publish-nightly.yml

fix docs path for publishing

---

docs/src/test/java-jdk9-only/jdocs/stream/operators/source/AsSubscriber.java
docs/src/test/java-jdk9-only/jdocs/stream/operators/source/FromPublisher.java

As observed in https://github.com/apache/incubator-pekko/actions/runs/4162081891/jobs/7200808860#step:6:36419

fix compilation of jdk9 docs tests

---

cluster/src/main/scala/org/apache/pekko/cluster/JoinConfigCompatCheckCluster.scala
cluster/src/test/scala/org/apache/pekko/cluster/JoinConfigCompatCheckClusterSpec.scala

relates to https://github.com/apache/incubator-pekko/issues/185

remove support for legacy Lightbend Split Brain Resolver

---

build.sbt
project/plugins.sbt

Note that `.enablePlugins` isn't needed anymore with the newest version

Updates sbt-source-dist

---

CONTRIBUTING.md

Update CONTRIBUTING.md to use pekko names

---

project/CopyrightHeader.scala

same issue as https://github.com/apache/incubator-pekko-connectors/pull/33

can only set headerLicense config once

---

LICENSE
NOTICE
legal/pekko-actor-jar-license.txt
legal/pekko-actor-jar-notice.txt

acknowledge use of scala-collection-compat code

---

LICENSE
NOTICE
legal/pekko-actor-jar-license.txt
legal/pekko-actor-jar-notice.txt

acknowledge use of netty derived code

---

project/Publish.scala
project/plugins.sbt

Replaces ci-release with dynver, see https://lists.apache.org/thread/l7yp8yb2ooy7opwmzpw7hkmz9gm0qr2r

Replace ci-release with dynver

---

LICENSE

https://github.com/apache/incubator-pekko/issues/230

acknowledge Lagom source code

---

project/Paradox.scala
project/build.properties
project/plugins.sbt

Latest version of sbt now has Apache snapshots repo already included

Use ApacheMavenSnapshotsRepo constant

---

.github/workflows/nightly-builds.yml

Some minor whitespace that I noticed

Fix whitespace

---

project/ValidatePullRequest.scala

Use FileFilter.nothing from newest sbt

---

actor/src/main/scala-2.13+/org/apache/pekko/util/OptionConverters.scala

Missed inline in toJavaPrimitive

---

build.sbt
project/Doc.scala
project/Paradox.scala
project/Publish.scala
project/plugins.sbt

we use a github workflow to rsync

remove rsync plugin

---

project/build.properties

=build Update to sbt 1.9.0-RC3

---

project/JdkOptions.scala
project/TestExtras.scala

Something that I quickly noticed, death to the semicolons

Remove redundant semicolons

---

project/plugins.sbt

* enables `sbt publishSigned`
* #351

update sbt-apache-sonatype plugin

---

README.md

* see https://github.com/apache/incubator-pekko/issues/339

doc: how to set version number in build

---

cluster-sharding/src/test/scala/org/apache/pekko/cluster/sharding/passivation/HillClimbingAdmissionOptimizerSpec.scala
docs/src/test/scala/docs/stream/cookbook/RecipeSplitter.scala
project/Dependencies.scala
remote/src/main/scala/org/apache/pekko/remote/transport/netty/NettyTransport.scala

refs: https://github.com/apache/incubator-pekko/issues/344
Not for merge , helping test the new scala release.

Upgrade to Scala 2.12.18 and 2.13.11

---

actor-tests/src/test/scala/org/apache/pekko/util/Scala212CompatTest.scala
actor/src/main/scala-2.12/org/apache/pekko/util/ccompat/package.scala

See https://github.com/apache/incubator-pekko-connectors/pull/146 for context

Add Iterable.once to ccompat

---

LICENSE
NOTICE
legal/pekko-actor-jar-license.txt
legal/pekko-actor-jar-notice.txt

relates to #378 
fyi @mdedetrich

acknowledge use of scala-library code

---

actor/src/main/scala-2.12/org/apache/pekko/util/ccompat/package.scala

These classes shouldn't be extended and can also help out in potential performance

Make 2.12 ccompat extension classes final

---

project/Dependencies.scala

Resolves: https://github.com/apache/incubator-pekko/issues/376

Update jackson-databind for sbt plugins

---

actor-tests/src/test/scala/org/apache/pekko/io/dns/DnsSettingsSpec.scala
actor-tests/src/test/scala/org/apache/pekko/io/dns/IdGeneratorSpec.scala
actor-tests/src/test/scala/org/apache/pekko/io/dns/internal/AsyncDnsResolverSpec.scala
actor-tests/src/test/scala/org/apache/pekko/io/dns/internal/DnsClientSpec.scala
actor/src/main/resources/reference.conf
actor/src/main/scala/org/apache/pekko/io/dns/DnsSettings.scala
actor/src/main/scala/org/apache/pekko/io/dns/IdGenerator.scala
actor/src/main/scala/org/apache/pekko/io/dns/internal/AsyncDnsResolver.scala
actor/src/main/scala/org/apache/pekko/io/dns/internal/DnsClient.scala
actor/src/main/scala/org/apache/pekko/io/dns/internal/Question.scala
bench-jmh/src/main/scala/org/apache/pekko/io/dns/IdGeneratorBanchmark.scala

This also addresses a concurrency bug in the sequence generator, and verifies the question asked in the response.

CVE-2023-31442 Address DNS poisoning vulnerability

---

actor/src/main/scala/org/apache/pekko/io/dns/IdGenerator.scala

see https://github.com/apache/incubator-pekko/pull/401#discussion_r1231609526

fix sign in code to generate a random signed short

---

actor-typed-tests/src/test/scala/docs/org/apache/pekko/typed/RouterSpec.scala
actor-typed-tests/src/test/scala/org/apache/pekko/actor/typed/ActorRefResolverSpec.scala
cluster-typed/src/main/scala/org/apache/pekko/cluster/ddata/typed/scaladsl/DistributedData.scala
persistence-query/src/main/scala/org/apache/pekko/persistence/query/Offset.scala
remote-tests/src/test/scala/org/apache/pekko/remote/testconductor/ControllerSpec.scala
remote/src/main/scala/org/apache/pekko/remote/artery/compress/CompressionTable.scala
remote/src/main/scala/org/apache/pekko/remote/serialization/ProtobufSerializer.scala
remote/src/main/scala/org/apache/pekko/remote/transport/PekkoPduCodec.scala
remote/src/main/scala/org/apache/pekko/remote/transport/PekkoProtocolTransport.scala
remote/src/main/scala/org/apache/pekko/remote/transport/Transport.scala
remote/src/test/scala/org/apache/pekko/remote/RemoteFeaturesSpec.scala

Noticed this when going through the code

Remove fqcn

---

persistence-query/src/main/scala/org/apache/pekko/persistence/query/EventEnvelope.scala

Remove another FQCN

---

LICENSE
legal/pekko-actor-jar-license.txt

Add note to LICENSE files regarding AbstractBoundedNodeQueue origin

---

LICENSE
actor/src/main/scala-2.12/org/apache/pekko/util/ccompat/package.scala
actor/src/main/scala/org/apache/pekko/util/Helpers.scala
legal/pekko-actor-jar-license.txt

better acknowledge code derived from scala-library

---

LICENSE
actor/src/main/scala/org/apache/pekko/util/FrequencySketch.scala
legal/pekko-actor-jar-license.txt

acknowledge use of hash-prospector code

---

stream/src/main/scala/org/apache/pekko/stream/impl/io/TLSActor.scala

TLSActor: apply check to avoid an endless loop

---

LICENSE

acknowledge use of Play Samples scripts

---

project/build.properties

refs: https://github.com/sbt/sbt/releases/tag/v1.9.1

=sbt Bump sbt version to 1.9.1

---

project/plugins.sbt

https://github.com/apache/incubator-pekko-sbt-paradox/pulls?q=is%3Apr+is%3Aclosed

use latest paradox plugin fixes

---

.github/workflows/publish-1.0-docs.yml
.github/workflows/publish-nightly.yml

remote_path changes in #459 were wrong - the remote_path should not have been changed
Apologies for the trial and error but running the CI job the only way to see what is going on

change remote_path back

---

.github/workflows/publish-1.0-docs.yml

Fix recursive copy

---

.github/workflows/binary-compatibility-checks.yml
.github/workflows/nightly-builds-latest-jdks.yml

add job that can test with java 20

---

build.sbt
project/plugins.sbt

mainly to uptake https://github.com/pjfanning/sbt-source-dist/issues/23

upgrade sbt-source-dist

---

README.md
project/PekkoBuild.scala

Useful in both diagnosing and dealing with flaky tests

Document testQuick in welcome screen

---

persistence/src/test/scala/org/apache/pekko/persistence/PersistenceSpec.scala

Follow on from https://github.com/apache/incubator-pekko/pull/473 but with other tests (i.e. `JournalCompactionSpecBase`).

Cleanup more state in PersistenceSpec

---

project/CopyrightHeader.scala

Minor change but these can be vals rather than val

Change defs to val

---

docs/src/main/paradox/index.md
docs/src/main/paradox/release-notes/index.md

* copied from https://cwiki.apache.org/confluence/display/PEKKO/Pekko+Core+Release+Notes
* pekko-http docs have release notes - so this is more consistent
* https://pekko.apache.org/docs/pekko-http/current/release-notes/index.html

add release notes

---

remote/src/main/resources/reference.conf

=ret Change the comment of Akka to Pekko.

---

remote/src/main/mima-filters/1.0.x.backwards.excludes/pducodec.backwards.excludes
remote/src/main/scala/org/apache/pekko/remote/Endpoint.scala
remote/src/main/scala/org/apache/pekko/remote/Remoting.scala
remote/src/main/scala/org/apache/pekko/remote/transport/PekkoPduCodec.scala
remote/src/main/scala/org/apache/pekko/remote/transport/PekkoProtocolTransport.scala
remote/src/main/scala/org/apache/pekko/remote/transport/ThrottlerTransportAdapter.scala
remote/src/test/scala/org/apache/pekko/remote/classic/RemotingSpec.scala
remote/src/test/scala/org/apache/pekko/remote/classic/transport/GenericTransportSpec.scala
remote/src/test/scala/org/apache/pekko/remote/classic/transport/PekkoProtocolSpec.scala

remove $ from class name

---

project/plugins.sbt

This will bring in the newly updated incubator logo which we were asked to use

Update latest pekko-sbt-paradox

---

docs/src/main/paradox/project/migration-guides.md

mention pekko and pekko.tcp URL schemes

---

actor-testkit-typed/src/main/scala/org/apache/pekko/actor/testkit/typed/CapturedLogEvent.scala
remote/src/main/scala/org/apache/pekko/remote/serialization/DaemonMsgCreateSerializer.scala
remote/src/main/scala/org/apache/pekko/remote/serialization/ProtobufSerializer.scala

Akka in comments (1.0.x backport)

---

.github/workflows/publish-1.0-nightly.yml

publish 1.0 snapshots

---

.github/workflows/build-test-prValidation.yml
build.sbt
project/JavaFormatter.scala

(cherry picked from commit c18a81a243e3f8b3452b07b4d596409334661e8d)

Remove javafmtOnCompile and check in CI

---

.scalafix.conf
stream/src/main/scala/org/apache/pekko/stream/impl/Stages.scala
stream/src/main/scala/org/apache/pekko/stream/impl/fusing/LazyFutureSource.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala
stream/src/main/scala/org/apache/pekko/stream/scaladsl/Source.scala

refs: https://github.com/apache/incubator-pekko/issues/46

=str Add LazyFutureSource to avoid sub materialization.

---

cluster-sharding/src/main/resources/reference.conf
cluster/src/main/resources/reference.conf
docs/src/main/paradox/supervision-classic.md
docs/src/main/paradox/testing.md
remote/src/main/resources/reference.conf
serialization-jackson/src/main/resources/reference.conf
stream/src/main/resources/reference.conf

cherry pick https://github.com/apache/incubator-pekko/commit/4169e7d476015fce84494725da2400d915f9318e

fix up some docs with version numbers that are Akka versions (#533)

---

stream/src/main/scala/org/apache/pekko/stream/impl/Timers.scala

refs: https://github.com/akka/akka/issues/30333

!str Logging error instead of failing the `keepAlive` operator.

---

project/SbtMultiJvm.scala

Extracted from the previouse PR for concat the `LICENSE` files.

+sbt Concat `LICENSE` in SbtMultiJvm assembly result.

---

actor/src/main/resources/reference.conf
actor/src/main/scala/org/apache/pekko/actor/RepointableActorRef.scala
actor/src/main/scala/org/apache/pekko/dispatch/BalancingDispatcher.scala
actor/src/main/scala/org/apache/pekko/dispatch/Dispatchers.scala
actor/src/main/scala/org/apache/pekko/dispatch/Future.scala
actor/src/main/scala/org/apache/pekko/dispatch/Mailboxes.scala
cluster-sharding/src/main/scala/org/apache/pekko/cluster/sharding/ClusterShardingSettings.scala
cluster-typed/src/main/scala/org/apache/pekko/cluster/typed/ClusterSingleton.scala
cluster/src/main/scala/org/apache/pekko/cluster/protobuf/ClusterMessageSerializer.scala
cluster/src/test/scala/org/apache/pekko/cluster/protobuf/ClusterMessageSerializerSpec.scala
persistence/src/main/java/org/apache/pekko/persistence/serialization/MessageFormats.java
persistence/src/main/protobuf/MessageFormats.proto
persistence/src/main/scala/org/apache/pekko/persistence/fsm/PersistentFSMBase.scala
persistence/src/main/scala/org/apache/pekko/persistence/journal/AsyncWriteJournal.scala
persistence/src/main/scala/org/apache/pekko/persistence/journal/leveldb/SharedLeveldbStore.scala
persistence/src/main/scala/org/apache/pekko/persistence/serialization/MessageSerializer.scala
remote/src/main/scala/org/apache/pekko/remote/AddressUidExtension.scala
remote/src/main/scala/org/apache/pekko/remote/RemoteActorRefProvider.scala
remote/src/main/scala/org/apache/pekko/remote/RemotingLifecycleEvent.scala
remote/src/main/scala/org/apache/pekko/remote/transport/netty/NettyTransport.scala
stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/CancellationStrategySpec.scala
stream/src/main/boilerplate/org/apache/pekko/stream/scaladsl/GraphApply.scala.template
stream/src/main/scala/org/apache/pekko/stream/StreamTcpException.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/FileIO.scala
stream/src/main/scala/org/apache/pekko/stream/scaladsl/FileIO.scala

I plan to backport this to 1.0.x branch

Yet more Akka version numbers in deprecation warnings

---

actor/src/main/resources/reference.conf
actor/src/main/scala/org/apache/pekko/actor/RepointableActorRef.scala
actor/src/main/scala/org/apache/pekko/dispatch/BalancingDispatcher.scala
actor/src/main/scala/org/apache/pekko/dispatch/Dispatchers.scala
actor/src/main/scala/org/apache/pekko/dispatch/Future.scala
actor/src/main/scala/org/apache/pekko/dispatch/Mailboxes.scala
cluster-sharding/src/main/scala/org/apache/pekko/cluster/sharding/ClusterShardingSettings.scala
cluster-typed/src/main/scala/org/apache/pekko/cluster/typed/ClusterSingleton.scala
cluster/src/main/scala/org/apache/pekko/cluster/protobuf/ClusterMessageSerializer.scala
cluster/src/test/scala/org/apache/pekko/cluster/protobuf/ClusterMessageSerializerSpec.scala
persistence/src/main/java/org/apache/pekko/persistence/serialization/MessageFormats.java
persistence/src/main/protobuf/MessageFormats.proto
persistence/src/main/scala/org/apache/pekko/persistence/fsm/PersistentFSMBase.scala
persistence/src/main/scala/org/apache/pekko/persistence/journal/AsyncWriteJournal.scala
persistence/src/main/scala/org/apache/pekko/persistence/journal/leveldb/SharedLeveldbStore.scala
persistence/src/main/scala/org/apache/pekko/persistence/serialization/MessageSerializer.scala
remote/src/main/scala/org/apache/pekko/remote/AddressUidExtension.scala
remote/src/main/scala/org/apache/pekko/remote/RemoteActorRefProvider.scala
remote/src/main/scala/org/apache/pekko/remote/RemotingLifecycleEvent.scala
remote/src/main/scala/org/apache/pekko/remote/transport/netty/NettyTransport.scala
stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/CancellationStrategySpec.scala
stream/src/main/boilerplate/org/apache/pekko/stream/scaladsl/GraphApply.scala.template
stream/src/main/scala/org/apache/pekko/stream/StreamTcpException.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/FileIO.scala
stream/src/main/scala/org/apache/pekko/stream/scaladsl/FileIO.scala

* Yet more Akka version numbers in deprecation warnings
cherry pick 4f570ea24cccbb19055272fd4e2673eb7492628f

Yet more Akka version numbers in deprecation warnings (#545)

---

project/plugins.sbt

* only produce tgz source release
* I plan to backport to 1.0.x branch

sbt-source-dist 0.1.10

---

project/plugins.sbt

cherry pick d6ddba13d33d8a73b007d8bf70547a79ffeeea86

sbt-source-dist 0.1.10 (#551)

---

docs/src/main/paradox/stream/operators/Flow/contramap.md
docs/src/main/paradox/stream/operators/index.md
docs/src/test/scala/docs/stream/operators/flow/ContraMap.scala
stream-tests/src/test/java/org/apache/pekko/stream/javadsl/FlowTest.java
stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowSpec.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/Flow.scala
stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala

Refs: https://github.com/apache/incubator-pekko/issues/554
Was: https://github.com/akka/akka/pull/31960
@kstokoz cc

+str Add Flow contramap.

---

docs/src/main/paradox/security/index.md

This link probably shouldn't be list in the page itself

remove link to itself

---

docs/src/main/paradox/security/index.md

cherry pick 5fde3e6b99d7e8bb0a4955fbe6777207f371a069 - #557

fix to point akka's security page (#557)

---

docs/src/main/paradox/typed/guide/tutorial_4.md

(cherry picked from commit 2ad6c6cd03fbe9fb57bc2331c9da853141ce268e)

fix docs typo

---

serialization-jackson/src/main/scala/org/apache/pekko/serialization/jackson/JacksonObjectMapperProvider.scala
serialization-jackson/src/main/scala/org/apache/pekko/serialization/jackson/JacksonSerializer.scala

* cherry pick 02595bbfd4ee9ec45e86a1b8a0a2f944f690fcfa (#567)

fix incorrect config name (serialization-jackson) (#567)

---

multi-node-testkit/src/main/scala/org/apache/pekko/remote/testconductor/Player.scala

=test Fix typo in Player class.

---

CONTRIBUTING.md
build.sbt

See https://github.com/apache/incubator-pekko-connectors/pull/208#discussion_r1294331081 for context
@He-Pin

Rename verifyCodeStyle to checkCodeStyle

---

stream/src/main/scala/org/apache/pekko/stream/impl/fusing/LazyFutureSource.scala

This was an oversight, should marked as final.

=str Mark LazyFutureSource final.

---

stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/ReverseArrowSpec.scala
stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/SourceSpec.scala
stream/src/main/scala/org/apache/pekko/stream/impl/fusing/IterableSource.scala
stream/src/main/scala/org/apache/pekko/stream/scaladsl/Source.scala

was https://github.com/akka/akka/pull/31372
This introduce a dedicated IterableSource, which can be later used for performance optimization. And also obey the supervisionStrategy now.

=str Add IterableSource.

---

project/build.properties

=sbt Bump sbt to 1.9.4

---

actor/src/main/scala/org/apache/pekko/actor/LightArrayRevolverScheduler.scala
actor/src/main/scala/org/apache/pekko/actor/Scheduler.scala

Motivation:
Reduce code duplication and make the code simpler to understand.
Result:
Clean Code.

Extract AtomicCancellable in Scheduler.

---

project/Paradox.scala
project/plugins.sbt

cherry pick 99cc4e794d7457938a4fcafa9d6f12c4265b58e7

use sbt paradox release (#597)

---

stream/src/main/scala/org/apache/pekko/stream/impl/Unfold.scala

As methioned at https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletionStage.html#toCompletableFuture--

=str Fix `CompletionStage#toCompletableFuture` may throw Exception

---

cluster-sharding/src/test/scala/org/apache/pekko/cluster/sharding/passivation/simulator/Simulator.scala
docs/src/main/paradox/stream/operators/Source-or-Flow/statefulMapConcat.md
docs/src/test/scala/docs/stream/operators/flow/StatefulMapConcat.scala
docs/src/test/scala/docs/stream/operators/sourceorflow/Split.scala
persistence-testkit/src/main/scala/org/apache/pekko/persistence/testkit/state/scaladsl/PersistenceTestKitDurableStateStore.scala
remote/src/test/scala/org/apache/pekko/remote/artery/SystemMessageDeliverySpec.scala
stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowStatefulMapConcatSpec.scala
stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/WithContextUsageSpec.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/Flow.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/SubFlow.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/SubSource.scala
stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala

refs https://github.com/apache/incubator-pekko/issues/601

=str Deprecate `statefulMapConcat` operator.

---

bench-jmh/src/main/scala/org/apache/pekko/stream/ZipWithIndexBenchmark.scala
docs/src/main/paradox/stream/operators/Source-or-Flow/statefulMapConcat.md
docs/src/test/scala/docs/stream/operators/flow/StatefulMapConcat.scala
docs/src/test/scala/docs/stream/operators/sourceorflow/Split.scala
stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowStatefulMapConcatSpec.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/Flow.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/SubFlow.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/SubSource.scala
stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala

refs https://github.com/apache/incubator-pekko/issues/601
As https://github.com/apache/incubator-pekko/pull/608 for 1.1.x

=str Deprecate statefulMapConcat operator.

---

stream/src/main/scala/org/apache/pekko/stream/impl/fusing/Ops.scala

Motivation:
This field is unessesary needed.

=str Remove `futureCB` in MapAsyncUnordered.

---

.github/workflows/binary-compatibility-checks.yml
.github/workflows/build-test-prValidation.yml
.github/workflows/dependency-graph.yml
.github/workflows/format.yml
.github/workflows/headers.yml
.github/workflows/link-validator.yml
.github/workflows/nightly-builds-aeron.yml
.github/workflows/nightly-builds-latest-jdks.yml
.github/workflows/nightly-builds.yml
.github/workflows/publish-1.0-docs.yml
.github/workflows/publish-nightly.yml
.github/workflows/scala3-build.yml
.github/workflows/scala3-compile.yml
.github/workflows/timing-tests.yml

(cherry picked from commit 131e7748297d334c1dcb118945d9eae8f10d90dc)

Use fetch tags from latest checkout action

---

multi-node-testkit/src/main/scala/org/apache/pekko/remote/testconductor/Player.scala
project/Dependencies.scala

* an experiment
* not sure if we need to merge this

scala 3.3.1

---

project/Dependencies.scala

Update and verify Scala 2.13.12

=sbt Update Scala to 2.13.12

---

remote/src/main/scala/org/apache/pekko/remote/transport/netty/NettyTransport.scala

simplify some NettyTransport code

---

project/Dependencies.scala

also need to keep aeron in sync

agrona 1.19.2

---

remote/src/main/scala/org/apache/pekko/remote/transport/netty/NettyTransport.scala

=remote Clean up unused field.

---

remote/src/test/scala/org/apache/pekko/remote/classic/RemotingSpec.scala

Otherwise it fails on Windows.

=test Fix keystore loading on Windows in RemotingSpec.

---

stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowStatefulMapSpec.scala

Motivation:
Test the onComplete method is been called only once.

=test Update the test to make sure `onComplete` been called only once.

---

build.sbt
project/build.properties

SBT 1.9.5. added the `Resolver.ApacheMavenStagingRepo` constant

Update to SBT 1.9.6 and use Apache Staging repo constant

---

remote/src/test/scala/org/apache/pekko/remote/Ticket1978CommunicationSpec.scala
remote/src/test/scala/org/apache/pekko/remote/artery/ArterySpecSupport.scala
remote/src/test/scala/org/apache/pekko/remote/artery/tcp/TlsTcpSpec.scala
remote/src/test/scala/org/apache/pekko/remote/artery/tcp/ssl/PemManagersProviderSpec.scala
remote/src/test/scala/org/apache/pekko/remote/artery/tcp/ssl/RotatingKeysSSLEngineProviderSpec.scala
remote/src/test/scala/org/apache/pekko/remote/artery/tcp/ssl/TlsResourcesSpec.scala
remote/src/test/scala/org/apache/pekko/remote/classic/RemotingSpec.scala
testkit/src/test/scala/org/apache/pekko/testkit/PekkoSpec.scala

Motivation:
These tests were failing on Windows, so fix it.
Result:
Passed on my pc.

=test Fix ssl related tests on Windows.

---

.github/workflows/format.yml
.scalafmt.conf

Update to the latest scalafmt version

=sbt update scalafmt to 3.7.14

---

remote/src/main/scala/org/apache/pekko/remote/transport/netty/NettyTransport.scala

Motivation:
Less blocking after migrated to netty 4
based on https://github.com/apache/incubator-pekko/pull/651

Remove blocking

---

.github/workflows/nightly-builds-latest-jdks.yml

refs:https://github.com/apache/incubator-pekko/issues/657

+build Add Jdk 21 to nightly build.

---

actor-typed/src/main/scala/org/apache/pekko/actor/typed/internal/ActorContextImpl.scala
actor/src/main/scala/org/apache/pekko/pattern/FutureTimeoutSupport.scala
actor/src/main/scala/org/apache/pekko/pattern/PipeToSupport.scala

Make use of SAM instead.

---

project/Dependencies.scala

refs: https://netty.io/news/2023/09/21/4-1-98-Final.html

=sbt Update Netty to 4.1.98.final

---

actor-typed/src/main/scala/org/apache/pekko/actor/typed/internal/routing/PoolRouterImpl.scala
actor-typed/src/main/scala/org/apache/pekko/actor/typed/javadsl/Routers.scala
actor-typed/src/main/scala/org/apache/pekko/actor/typed/scaladsl/Routers.scala

refs: https://github.com/apache/incubator-pekko/pull/675

=act Make parameter rename safe.

---

stream-typed-tests/src/test/scala/org/apache/pekko/stream/MapAsyncPartitionedSpec.scala

see https://github.com/apache/incubator-pekko/actions/runs/6306314096/job/17121248529

fix scala 3 compile issue

---

cluster-sharding-typed/src/main/scala/org/apache/pekko/cluster/sharding/typed/ShardingMessageExtractor.scala

fix scala 2.12 build

---

cluster/src/main/scala/org/apache/pekko/cluster/sbr/SplitBrainResolver.scala

Witnessed this typo in our logs.

Remove superfluous comma

---

docs/src/main/paradox/typed/persistence.md
persistence-typed/src/main/scala/org/apache/pekko/persistence/typed/PersistenceId.scala

Remove note about Lagom

---

actor/src/main/scala/org/apache/pekko/actor/ActorSystem.scala

Found this while working on Pekko

Replace Akka reference with Pekko

---

docs/src/main/paradox/typed/persistence.md
persistence-typed/src/main/scala/org/apache/pekko/persistence/typed/PersistenceId.scala

See #698 - cherry picks c6dc8210d71bbc180145175f737893dba0cae9d8

Remove note about Lagom (#698)

---

.github/workflows/scala-steward.yml

Resolves https://github.com/apache/incubator-pekko/issues/56

Add scala steward

---

.scala-steward.conf

Let me know if any other additions/removals need to be done

Improve .scala-steward.conf

---

project/Dependencies.scala

https://mvnrepository.com/artifact/org.bouncycastle/bcpkix-jdk18on
https://mvnrepository.com/artifact/org.bouncycastle/bcpkix-jdk15on

use bcpkix-jdk18on (jdk15on no longer published)

---

project/PekkoBuild.scala
project/plugins.sbt

refs: https://github.com/apache/incubator-pekko/pull/715
Need some adjustment.

=sbt Update sbt-welcome to 0.3.2

---

.github/workflows/binary-compatibility-checks.yml
.github/workflows/publish-check.yml

We've hit recent issues where compile issues are getting past our PR checks.
See #690 and #684

on each PR, do a full local publish

---

actor-typed/src/main/scala/org/apache/pekko/actor/typed/internal/ExtensionsImpl.scala

Avoids https://github.com/lampepfl/dotty/issues/18248
Backport of #708

Sidestep reproducibility issue

---

.github/workflows/binary-compatibility-checks.yml
.github/workflows/publish-check.yml

cherry pick 97bc8113ac0590a9474a0cf6f4be769debe3913e

on each PR, do a full local publish (#691)

---

project/OSGi.scala
project/plugins.sbt

Resolves: https://github.com/apache/incubator-pekko/issues/685

Fix OSGI protobuf bug

---

.scala-steward.conf

refs: https://github.com/apache/incubator-pekko/pull/723 & https://github.com/apache/incubator-pekko/pull/756
Pin sbt-java-formatter for now.

Pin sbt-java-formatter to 0.7.0

---

project/Dependencies.scala

(cherry picked from commit 9c19c91bed5d90fa22c382948a576d58a9bc75a0)

Remove invalid comment

---

actor/src/main/scala/org/apache/pekko/dispatch/Dispatchers.scala

saw a compiler warning about it

mark function tail recursive

---

actor/src/main/scala/org/apache/pekko/dispatch/Dispatchers.scala

cherry pick a9ff8e8dede79bcaafbb8cf2a978ac0da12a0720

mark function tail recursive (#780)

---

actor-tests/src/test/scala/org/apache/pekko/actor/ActorSystemSpec.scala
actor-typed-tests/src/test/scala/org/apache/pekko/actor/typed/ActorSystemSpec.scala
actor-typed/src/main/scala/org/apache/pekko/actor/typed/ActorSystem.scala
actor/src/main/scala/org/apache/pekko/actor/ActorSystem.scala
actor/src/main/scala/org/apache/pekko/dispatch/Dispatchers.scala
actor/src/main/scala/org/apache/pekko/util/Helpers.scala

cherry pick 860d0166a281a7e595e546393d1ef79203670f06 - #771

do not render env variables in configs (#771)

---

docs/src/main/paradox/general/configuration.md
docs/src/main/paradox/release-notes/index.md

cherry pick 2864b6a26c27511330d2b5e5f5eaf5b7d02f90ae

add release notes for v1.0.2 (#792)

---

cluster-typed/src/test/scala/org/apache/pekko/cluster/typed/ClusterActorLoggingSpec.scala

increase timeout on flaky test

---

docs/src/main/paradox/project/scala3.md

cherry pick 4e4f53fa65c47dfd1fada99b9a686a73554e933e

Update scala3.md (#804)

---

actor-typed/src/main/mima-filters/1.0.x.backwards.excludes/jfr.excludes
cluster-sharding/src/main/mima-filters/1.0.x.backwards.excludes/jdk-11-specific-classes.excludes
remote/src/main/mima-filters/1.0.x.backwards.excludes/jdk11-specific-classes.backwards.excludes
remote/src/main/mima-filters/1.0.x.backwards.excludes/pducodec.backwards.excludes
stream/src/main/mima-filters/1.0.x.backwards.excludes/28324-jdk9-specific-classes.backwards.excludes

cherry pick ccce880d4cedc38e305923a0ddc8251fe5b92852 - #813

license headers for mima files (#813)

---

docs/src/main/paradox/logging.md
docs/src/main/paradox/typed/logging.md

we don't want to encourage the use of this in production

adjust log-on-startup docs

---

docs/src/main/paradox/logging.md
docs/src/main/paradox/typed/logging.md

cherry pick 2ebec0364d5185a93cf6ff3e0c77003bee865dd7 - #815

adjust log-on-startup docs (#815)

---

.scala-steward.conf
project/Dependencies.scala

https://github.com/qos-ch/logback/issues/745
https://github.com/advisories/GHSA-vmq6-5m68-f53m

upgrade logback due to cve

---

docs/src/main/paradox/release-notes/index.md

full list of changes - https://github.com/apache/incubator-pekko/compare/v1.0.1...v1.0.2
I think it is ok to focus on main ones

add more v1.0.2 release notes

---

persistence/src/main/scala/org/apache/pekko/persistence/serialization/SnapshotSerializer.scala
persistence/src/test/scala/org/apache/pekko/persistence/serialization/SnapshotSerializerSpec.scala

cherry pick 15aee501720195d0c986c949343628b422dc38af #837
* support reading akka-persistence snapshots
* add test
* Update SnapshotSerializerSpec.scala

support reading akka-persistence snapshots (#837)

---

.github/workflows/build-test-prValidation.yml
cluster-typed/src/test/scala/org/apache/pekko/cluster/typed/ClusterActorLoggingSpec.scala

relates to #795 - #796 did not help
* it seems like this filter-leeway is the right timeout
* this test never fails for me - so this is a bit painful to get the CI issue fixed

try to fix ClusterActorLoggingSpec

---

stream/src/main/scala/org/apache/pekko/stream/impl/ActorRefSource.scala

=str Fold InHandler and OutHandler for operator ActorRefSource.

---

stream/src/main/scala/org/apache/pekko/stream/impl/fusing/Ops.scala

=str Fold InHandler and OutHandler for operator Scan.

---

stream/src/main/scala/org/apache/pekko/stream/KillSwitch.scala

=str Fold InHandler and outHandler for UniqueBidiKillSwitchStage.

---

docs/src/main/paradox/typed/style-guide.md

cherry pick 8dedfc242ffa09eec53acae45d850b7932fc3276 #853

fix broken link (#853)

---

stream-tests/src/test/java/org/apache/pekko/stream/javadsl/FlowTest.java
stream-tests/src/test/java/org/apache/pekko/stream/javadsl/SourceTest.java
stream/src/main/scala/org/apache/pekko/stream/StreamTimeoutException.scala
stream/src/main/scala/org/apache/pekko/stream/impl/Timers.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/BidiFlow.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/Flow.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/SubFlow.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/SubSource.scala
stream/src/main/scala/org/apache/pekko/stream/scaladsl/BidiFlow.scala
stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala

refs https://github.com/apache/incubator-pekko/issues/856

=str Add dedicated stream timeout exceptions for stream timeout operators

---

stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala
stream/src/main/scala/org/apache/pekko/stream/scaladsl/Sink.scala

I think these comments are outdated now

=str Remove unused comments

---

stream/src/main/scala/org/apache/pekko/stream/impl/fusing/FlatMapPrefix.scala

Motivation:
The in and out handler in flatmapPrefix can be fold into one.
Result:
Less allocation for per materlization.

perf: Fold In&OutHanlder in FlatMapPrefix.

---

stream/src/main/boilerplate/org/apache/pekko/stream/scaladsl/GraphApply.scala.template

refs: https://github.com/apache/incubator-pekko/issues/875
I checked it locally, it works now.

chore: Fix GraphApply.scala.template

---

stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowStatefulMapSpec.scala

Motivation:
Add more tests for not invoking `onComplete` twice for statefulMap, and later I will try to add `mapWithResource` operator.
Result:
Safer to coverage more cases.

chore: Add tests for not invoking `onComplete` twice for statefulMap.

---

.github/workflows/scala-steward.yml

References: https://github.com/apache/incubator-pekko-http/issues/379, see https://github.com/scala-steward-org/scala-steward/issues/3257#issuecomment-1872788986

Fix scala-steward updating incorrect repo's

---

NOTICE
legal/PekkoNotice.txt
legal/pekko-actor-jar-notice.txt
legal/pekko-remote-jar-notice.txt

cherry pick d7f1b9058a583c3ff0fda1eeef3b9a2db034aa28 #896

2024 added to copyright (#896)

---

actor-tests/src/test/scala-2.13+/org/apache/pekko/util/ByteStringBuilderScala213PlusSpec.scala
actor-tests/src/test/scala/org/apache/pekko/util/ByteStringBuilderSpec.scala
actor/src/main/scala-2.13/org/apache/pekko/util/ByteString.scala
actor/src/main/scala-3/org/apache/pekko/util/ByteString.scala
project/PekkoBuild.scala

cherry pick d5381958c8ef7349aaf9b01e7c394c71aff39295 #903

fix ByteStringBuilder.addAll (#903)

---

.scala-steward.conf

See https://github.com/apache/incubator-pekko/pull/910 and https://github.com/apache/incubator-pekko/issues/757 for context

Add second sbt-osgi in dependency update ignore list

---

actor-typed/src/main/mima-filters/1.0.x.backwards.excludes/jfr.excludes
cluster-sharding/src/main/mima-filters/1.0.x.backwards.excludes/jdk-11-specific-classes.excludes
remote/src/main/mima-filters/1.0.x.backwards.excludes/jdk11-specific-classes.backwards.excludes
remote/src/main/mima-filters/1.0.x.backwards.excludes/pducodec.backwards.excludes
stream/src/main/mima-filters/1.0.x.backwards.excludes/28324-jdk9-specific-classes.backwards.excludes

cherry pick 468aab0c636a3c97f93713d5b78dbf6f69e3d9d7 (except files that do not exist on 1.0.x branch) - #921

reformat some headers (#921)

---

actor-tests/src/test/scala/org/apache/pekko/io/dns/DockerBindDnsService.scala
project/Dependencies.scala

tidy up imports in new docker code

---

bench-jmh/src/main/scala/org/apache/pekko/remote/artery/LiteralEncodingBenchmark.scala
docs/src/test/scala/docs/persistence/PersistenceSchemaEvolutionDocSpec.scala
remote/src/main/scala/org/apache/pekko/remote/artery/tcp/ssl/PemManagersProvider.scala
remote/src/test/scala/org/apache/pekko/remote/artery/MetadataCarryingSpec.scala
remote/src/test/scala/org/apache/pekko/remote/artery/RemoteInstrumentsSerializationSpec.scala

use StandardCharsets

---

actor/src/main/scala-2.12/org/apache/pekko/util/ByteString.scala
actor/src/main/scala-3/org/apache/pekko/util/ByteString.scala
actor/src/main/scala/org/apache/pekko/actor/ActorSystem.scala
actor/src/main/scala/org/apache/pekko/actor/dungeon/Children.scala
actor/src/main/scala/org/apache/pekko/dispatch/AbstractDispatcher.scala
actor/src/main/scala/org/apache/pekko/routing/RouterConfig.scala
bench-jmh/src/main/scala/org/apache/pekko/stream/io/FileSourcesBenchmark.scala
cluster-sharding/src/main/scala/org/apache/pekko/cluster/sharding/ShardRegion.scala
cluster/src/main/scala/org/apache/pekko/cluster/ClusterJmx.scala
distributed-data/src/main/scala/org/apache/pekko/cluster/ddata/protobuf/ReplicatedDataSerializer.scala
multi-node-testkit/src/main/scala/org/apache/pekko/remote/testconductor/Conductor.scala
osgi/src/main/scala/org/apache/pekko/osgi/BundleDelegatingClassLoader.scala
remote/src/main/scala/org/apache/pekko/remote/RemoteActorRefProvider.scala
remote/src/main/scala/org/apache/pekko/remote/transport/PekkoProtocolTransport.scala
stream/src/main/scala/org/apache/pekko/stream/impl/Sinks.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala
stream/src/main/scala/org/apache/pekko/stream/scaladsl/Source.scala
testkit/src/main/scala/org/apache/pekko/testkit/CallingThreadDispatcher.scala

cherry pick 6872f9c8b78ae2fababb97cb4600d67d77b4bbd2 #939

Fix some non-standard comments (#939)

---

docs/src/test/java-jdk9-only/jdocs/stream/operators/source/AsSubscriber.java
docs/src/test/java-jdk9-only/jdocs/stream/operators/source/FromPublisher.java

Motication:
Fix compiling error.
refs: https://github.com/apache/incubator-pekko/actions/runs/7522637028/job/20474910545
Result:
It compiles now.

chore: Fix compiling error in AsSubscriber.java and FromPublisher.java

---

.sbt-java-formatter.conf

(cherry picked from commit 485639ef821b5036b521b65d973d698e373721da)

chore: Ignore two pb files from java formatter.

---

actor/src/main/scala/org/apache/pekko/japi/function/Function.scala

cherry pick 7c82c2a1c41f687fd04bcb3e0ec4bb9b04700f51 #961

fix up javadoc on Creator trait (#961)

---

docs/src/main/paradox/stream/operators/Source-or-Flow/collectWhile.md
docs/src/main/paradox/stream/operators/index.md
docs/src/test/java/jdocs/stream/operators/SourceOrFlow.java
docs/src/test/scala/docs/stream/operators/sourceorflow/Collect.scala
stream-tests/src/test/java/org/apache/pekko/stream/javadsl/FlowTest.java
stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowCollectWhileSpec.scala
stream/src/main/scala/org/apache/pekko/stream/impl/Stages.scala
stream/src/main/scala/org/apache/pekko/stream/impl/fusing/CollectWhile.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/Flow.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/SubFlow.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/SubSource.scala
stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala

Motivation:
refs: https://github.com/apache/incubator-pekko/issues/957
Add `collectWhile` to Pekko stream
Result:
Rich operators set.
Just a preview, will need a rebase.

feat: Add collectWhile operator.

---

project/Dependencies.scala

follow up to https://github.com/apache/incubator-pekko/pull/922

remove some unnecessary test dependencies

---

project/project-info.conf
scripts/link-validator.conf

cherry pick 3c7921c66c13d99b01558224082040abb225bc48 #999

add conf header (#999)

---

project/PekkoBuild.scala

Motivation:
Add this because new contributors will know, a Chinese contributor just found this and report back.

chore: Mention how long paradox will took.

---

NOTICE
legal/PekkoNotice.txt
legal/pekko-actor-jar-notice.txt
legal/pekko-remote-jar-notice.txt

see https://github.com/apache/incubator-seata/blob/2.x/NOTICE
see https://lists.apache.org/thread/5n8bv7tl87p05pq95w6dnoy1x5pqt5f5

add incubating to NOTICE

---

NOTICE
legal/PekkoNotice.txt
legal/pekko-actor-jar-notice.txt
legal/pekko-remote-jar-notice.txt

cherry pick b273c06c68c479c0d40c8078163bb86cf5dfae93 #1009

add incubating to NOTICE (#1009)

---

.asf.yaml

(cherry picked from commit f99a9ea156973e21ee0e2b53d247d6d4d5878666)

Only use dependabot for alerts

---

docs/src/main/paradox/actors.md

doc: metion for the Java 21's new switch statement in document

---

project/project-info.conf

Resolves #1017

---

stream/src/main/mima-filters/1.0.x.backwards.excludes/pr-991-remove-unused-attributes.backwards.excludes
stream/src/main/scala/org/apache/pekko/stream/impl/Stages.scala

Motivation:
These fields are internal and not used in anywhere.
Result:
Clean code.

chore: Remove unused attributes in Stages.

---

project/project-info.conf

cherry pick dc1fc69255dafd0da67a0554fa5dbd98fcb9a4dd #1028

Add JDK21 info to doc #1017 (#1028)

---

build.sbt

Use Test configuration constant

---

build.sbt
project/plugins.sbt

(cherry picked from commit 639d5ad8ee48a8ac5c151df6370af426dd1b3c07)

Update sbt-pekko-build to 0.3.1

---

stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala

Motivation:
Add @since 1.1.0 for flatten operator.

chore: Add @since 1.1.0 for flatten operator.

---

remote/src/main/resources/reference.conf
remote/src/main/scala/org/apache/pekko/remote/transport/PekkoProtocolTransport.scala

cherry pick 11ba3d7beff3bd8ece5244c595375de8b25ed7c9 #587

fix managerName to use `pekko` (#587)

---

project/plugins.sbt

cherry pick 7bf26c8d44121b877432d6de3e19d09beafbb4a5 #1067

Upgrade sbt-pull-request-validator (#1067)

---

persistence-typed/src/main/scala/org/apache/pekko/persistence/typed/internal/RetentionCriteriaImpl.scala

get avoid snapshot interval calculate int overflow (#1088)

---

docs/src/main/paradox/stream/stream-graphs.md

cherry pick from a55ebc3b79eb059c18287512d926d5cb1d00e141

add partition operator in stream graph docs (#1093)

---

actor-typed/src/main/resources/reference.conf
actor/src/main/resources/reference.conf
cluster-sharding-typed/src/main/resources/reference.conf
cluster-sharding/src/main/resources/reference.conf
cluster-tools/src/main/resources/reference.conf
cluster/src/main/resources/reference.conf
remote/src/main/resources/reference.conf
stream/src/main/resources/reference.conf

cherry pick 8ce4973fc973ec70e79ee7e70333236b512cad2e #1100

Configuration typo fixes (#1100)

---

cluster-metrics/src/main/java/org/apache/pekko/cluster/metrics/protobuf/msg/ClusterMetricsMessages.java
cluster-sharding/src/main/java/org/apache/pekko/cluster/sharding/protobuf/msg/ClusterShardingMessages.java
cluster-tools/src/main/java/org/apache/pekko/cluster/client/protobuf/msg/ClusterClientMessages.java
cluster-typed/src/main/java/org/apache/pekko/cluster/typed/internal/protobuf/ReliableDelivery.java
cluster/src/main/java/org/apache/pekko/cluster/protobuf/msg/ClusterMessages.java
distributed-data/src/main/java/org/apache/pekko/cluster/ddata/protobuf/msg/ReplicatedDataMessages.java
distributed-data/src/main/java/org/apache/pekko/cluster/ddata/protobuf/msg/ReplicatorMessages.java
docs/src/main/java/docs/ddata/protobuf/msg/TwoPhaseSetMessages.java
persistence-typed/src/main/java/org/apache/pekko/persistence/typed/serialization/ReplicatedEventSourcing.java
project/Dependencies.scala
remote/src/main/java/org/apache/pekko/remote/ArteryControlFormats.java
remote/src/main/java/org/apache/pekko/remote/WireFormats.java

Protobuf 3.23.4

---

docs/src/main/paradox/release-notes/index.md

migration notes are also needed (#1056)

1.0.3-M1 release notes

---

docs/src/main/paradox/stream/operators/Source-or-Flow/statefulMap.md

cherry pick 53f5ba929fb4cdc46ad3fc913ae7d0e448053227 #1130

fix numbering in statefulMap.md (#1130)

---

project/Protobuf.scala

Build with protoc 3.20.3

---

stream/src/main/scala/org/apache/pekko/stream/impl/io/TLSActor.scala

relates to https://github.com/apache/incubator-pekko-http/issues/485

in TlsActor flush data to user only after handshake has finished

---

osgi/src/test/scala/org/apache/pekko/osgi/PojoSRTestSupport.scala
project/Dependencies.scala
project/PekkoDisciplinePlugin.scala
scripts/link-validator.conf

chore: Update Scala to 2.13.13

---

osgi/src/test/scala/org/apache/pekko/osgi/PojoSRTestSupport.scala
project/Dependencies.scala
project/PekkoDisciplinePlugin.scala
scripts/link-validator.conf

Motivation:
Bump Scala version on 1.0.x branch

chore: Update Scala version to 2.13.13 & 2.12.19

---

actor/src/main/scala/org/apache/pekko/actor/ActorSystem.scala

Motivation:
Fix two typos
reported by @jxnu-liguobin

chore: Replace Akka with Pekko in ActorSystem.scala

---

actor/src/main/scala/org/apache/pekko/actor/ActorSystem.scala

(cherry picked from commit 1c851550477105f5259ea397e42f183c5f0de939)

chore: Replace Akka with Pekko in ActorSystem.scala (#1163)

---

.github/workflows/link-validator.yml
.jvmopts-ci

OOM in https://github.com/apache/incubator-pekko/actions/runs/8144031853/job/22257233687

provide more memory to sbt jobs

---

.github/workflows/link-validator.yml
.jvmopts-ci

cherry pick baedbe61d8cd499b674414b0198f970003fa6d2d #1176

provide more memory to sbt jobs (#1176)

---

docs/src/main/paradox/project/migration-guides.md

cherry pick 0843f368a637700afa6ef731145f568dacbe1ab0 #1172

Update v1.0.3-M1 details in migration-guides.md (#1172)

---

project/Dependencies.scala

Co-authored-by: scala-steward-asf[bot] <147768647+scala-steward-asf[bot]@users.noreply.github.com>
(cherry picked from commit 74142920b3c89d910b5013e063fba9c9c3bf64d9)

Update scala3-library to 3.3.3 (#1169)

---

project/Dependencies.scala
serialization-jackson/src/main/resources/reference.conf

jackson 2.16.2

---

stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala

Motivation：
Fix typo in Javadsl

chore:Fix up typos for unfoldResource* operators.

---

docs/src/main/paradox/index.md
docs/src/main/paradox/migration/index.md
docs/src/main/paradox/migration/migration-guide-1.0.x-1.1.x.md
docs/src/main/paradox/migration/migration-guide-akka-1.0.x.md
docs/src/main/paradox/project/project-index.md
docs/src/main/paradox/release-notes/index.md
project/ProjectIndexGenerator.scala

resove #1180 
hi @pjfanning Could you take a look, if this is what you want?

Improve migration doc layout

---

actor-testkit-typed/src/main/scala/org/apache/pekko/actor/testkit/typed/internal/ActorSystemStub.scala
docs/src/main/paradox/release-notes/index.md
stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowFlatMapPrefixSpec.scala
stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowFutureFlowSpec.scala
stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/LazyFlowSpec.scala
stream/src/main/scala/org/apache/pekko/stream/Attributes.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/Flow.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/FlowWithContext.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/SourceWithContext.scala
stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala
stream/src/main/scala/org/apache/pekko/stream/scaladsl/FlowWithContextOps.scala

cherry pick 06cff559a419c16bcde63a3f78a2201343a1b2bb #1177

some doc changes (#1177)

---

stream/src/main/scala/org/apache/pekko/stream/impl/fusing/StreamOfStreams.scala

Motivation:
Fuse in and out handle in Split.
Result:
Fewer allocation.

chore: Fuse In/OutHandler into GraphStageLogic.

---

project/Dependencies.scala
project/Protobuf.scala

matches the protobuf-java version

build with protoc 3.25.3

---

project/Dependencies.scala

this is the version used by aeron 1.43.0

agrona 1.20.0

---

docs/src/test/scala/docs/actor/ActorDocSpec.scala
docs/src/test/scala/docs/actor/SchedulerDocSpec.scala
docs/src/test/scala/docs/dispatcher/DispatcherDocSpec.scala

* chore: Fix scala constructor finding tests for scala 3.
* reorder imports
(cherry picked from commit c818001180c52fe89037bfc76421ef8ad9cc81aa)

chore: Fix scala constructor finding tests for scala 3. (#1220)

---

.github/workflows/nightly-builds.yml

run `sbt doc` in nightly build for Scala 3 but with without genjavadoc

---

stream-tests/src/test/java/org/apache/pekko/stream/javadsl/GraphDslTest.java
stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/GraphMergeSortedSpec.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/Graph.scala
stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala
stream/src/main/scala/org/apache/pekko/stream/scaladsl/Graph.scala

Motivation:
Add helper method for java dsl.
Result:
richer javadsl.

chore: Add missing create method to javadsl Graph

---

.github/workflows/nightly-builds.yml

fix evaluation in nightly-builds.yml

---

build.sbt
project/Paradox.scala

remove incubator notice

---

project/Paradox.scala

cherry pick ebf5c89a83d75642383c0d255c108204db1eea3d #1216

remove incubator notice (#1216)

---

stream/src/main/scala/org/apache/pekko/stream/impl/UnfoldResourceSource.scala

Motivation:
Refactory UnfoldResourceSource a little instead of https://github.com/apache/pekko/pull/615
Result:
Clean code.

chore: Refactor UnfoldResourceSource.

---

stream/src/main/scala/org/apache/pekko/stream/impl/JavaStreamSource.scala

Motivation:
Use splitIterator directly
Result:
Less conversion.the current iterator is created from the splitIterator, which is another adapter, and we need double invocation hasNext and Next, both involving the adapter.
So with this directly using the split iterator, we can reduce the allocation and indirect invocation.

chore: Make use of splitIterator directly

---

.github/workflows/scala-steward.yml

Add workflow_dispatch to scala steward

---

.github/workflows/scala-steward.yml

Motivation:
refs: https://github.com/apache/pekko/issues/1253

chore: Add more heap memory to stew action.

---

.github/workflows/scala-steward.yml

Motivation:
Testing the current working directory

Chore:show the current pwd to make the scala-stew works

---

project/Dependencies.scala

see https://repo1.maven.org/maven2/io/aeron/aeron-client/1.44.0/aeron-client-1.44.0.pom

agronaVersion 1.21.1

---

actor-tests/src/test/scala/org/apache/pekko/io/dns/DockerBindDnsService.scala
project/Dependencies.scala

see https://github.com/apache/pekko/discussions/1272
cherry pick b7be586e7783f11bdcc970a81dbcb6210d30e638 and 2ae6c8d00c116b5d08d3e6b364dc467ca2d528b9

backport dockerclient change due to CVE

---

docs/src/main/paradox/actors.md
docs/src/main/paradox/typed/style-guide.md

(cherry picked from commit 3cd08016b57e95f9244f0990282dd956c173b82e)

chore: Remove vavr link. (#1280)

---

actor-tests/src/test/scala/org/apache/pekko/util/ByteStringSpec.scala
actor/src/main/scala-2.12/org/apache/pekko/util/ByteIterator.scala
actor/src/main/scala-2.13/org/apache/pekko/util/ByteIterator.scala
actor/src/main/scala-3/org/apache/pekko/util/ByteIterator.scala

Backport https://github.com/apache/pekko/pull/1282 to 1.0.x

Fix ByteIterator#indexWhere

---

.sbtopts

Update .sbtopts to match mem in .jvmopts-ci

---

.sbtopts

cherry pick 263ef3cc577e1aea6fb1078a479d9b44ca766bfe #1290

Update .sbtopts to match mem in .jvmopts-ci (#1290)

---

docs/src/main/paradox/persistence-plugins.md

update durable state status in persistence-plugins.md

---

docs/src/main/paradox/multi-jvm-testing.md

chore: update sbt-multi-jvm doc

---

serialization-jackson/src/main/resources/reference.conf

fix link in reference.conf

---

.github/workflows/nightly-builds.yml

Motivation:
Use expression from https://docs.github.com/en/actions/learn-github-actions/expressions#startswith

chore: Update startsWith in yml

---

.asf.yaml

matches https://github.com/apache/pekko-http/blob/main/.asf.yaml

notify CI failures

---

cluster/src/main/resources/reference.conf

See also https://github.com/apache/pekko/pull/263.

Fix dynamic versioning example

---

project/Dependencies.scala

* follow up to #1344 
* also no need to 'force' the Jackson deps

further fix needed for bcpkix

---

actor/src/main/scala/org/apache/pekko/actor/LightArrayRevolverScheduler.scala

chore: Fix typo in LARS comments

---

docs/src/main/paradox/release-notes/releases-1.0.md

cherry pick 3b8de55ec8052207dfa7fbd41c2940aca94cc20c #1375

add release notes for v1.0.3 (#1375)

---

project/PekkoBuild.scala
project/plugins.sbt

While clearly not perfect, I think we should start growing towards publishing valid SBOMs for our artifacts, and publishing these is a good first step in that direction.

feat: publish SBOMs

---

docs/src/main/paradox/release-notes/releases-1.1.md

add known issue for #1393

---

stream/src/main/scala/org/apache/pekko/stream/impl/streamref/SourceRefImpl.scala

fix code comment with 'aquired' typo

---

.scala-steward.conf

chore: pin aeron version

---

actor/src/main/scala/org/apache/pekko/actor/Timers.scala

add since marker in Timers.scala

---

.github/workflows/publish-1.1-docs.yml
docs/src/main/paradox/release-notes/releases-1.1.md

1.1.0 release has been approved. Need to get this merged so I can announce the release.

release notes for 1.1.0

---

docs/src/main/paradox/release-notes/releases-1.1.md

see #1463 and https://github.com/apache/pekko/pull/1456#pullrequestreview-2276084772

add some warnings to release notes

---

docs/src/main/paradox/typed/logging.md

cherry pick ffb31daeca71a79b474f50379726ebc8a92ac69c #1476

docs: logger names are Fully Qualified Class Names (#1476)

---

.scala-steward.conf

revert to sbt develocity 1.0

---

project/plugins.sbt

meant to be part of https://github.com/apache/pekko/pull/1493

revert to develocity 1.0.1

---

.scala-steward.conf
project/plugins.sbt

see #1492 and latest comment in https://issues.apache.org/jira/browse/INFRA-26139

develocity 1.1.1

---

.github/workflows/publish-1.1-docs.yml

v1.1.2 docs

---

.github/dependabot.yml

https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

chore: add dependabot for github-actions

---

.github/dependabot.yml

* #1549 was 1st attempt but https://github.com/apache/pekko/runs/32649405548 still happens
* still complaining about schedule
* now trying to make schedule match https://github.com/pjfanning/excel-streaming-reader/blob/main/.github/dependabot.yml

another attempt to fix schedule in dependabot.yml

---

docs/src/main/paradox/release-notes/releases-1.0.md

broken link in release docs

---

docs/src/main/paradox/cluster-metrics.md
docs/src/main/paradox/release-notes/index.md

broken link in release docs (1.0.x)

---

.scala-steward.conf

add missing commas in .scala-steward.conf

---

.github/workflows/link-validator.yml

run link-validator once a day (not per PR commit)

---

stream/src/main/mima-filters/1.0.x.backwards.excludes/pr-1443-also-alsoTo-source-flow-with-context.backwards.excludes
stream/src/main/mima-filters/1.0.x.backwards.excludes/pr-1619-remove-supervised-group-stage-logic.backwards.excludes
stream/src/main/scala/org/apache/pekko/stream/impl/fusing/Ops.scala

Motivation:
refs:https://github.com/apache/pekko/issues/1618
Modification:
remove SupervisedGraphStageLogic

chore: Remove SupervisedGraphStageLogic

---

.github/workflows/nightly-1.1-builds.yml
.github/workflows/publish-1.1-docs.yml
.github/workflows/publish-1.1-nightly.yml

main branch is now for 1.2 dev

add 1.1 builds

---

stream/src/main/scala/org/apache/pekko/stream/impl/PhasedFusingActorMaterializer.scala

Motivation:
Code clean up and performance.
Modification:
I found this todo when read the code, and we should avoid creating the empty array everytime.

chore: avoid create an empty array everytime.

---

stream/src/main/scala/org/apache/pekko/stream/javadsl/Sink.scala
stream/src/main/scala/org/apache/pekko/stream/scaladsl/Sink.scala

Motivation:
Missed this, it should be 1.2.0
Modification:
Change 1.1.3 to 1.2.0
Result:
Right since version

chore: Fix the @since of Sink.none operator, should be 1.2.0

---

.github/workflows/build-test-prValidation.yml
.github/workflows/nightly-1.1-builds.yml
.github/workflows/nightly-builds-aeron.yml
.github/workflows/nightly-builds.yml

Motivation:
refs:
Turn on  Netty's leak detector  to avoid for https://github.com/apache/pekko/issues/1634
Modification:
turn on the leak detector.
Result:
Will get logged in the building log.

chore: Turn on Netty's leak detector in build.

---

stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/StreamConvertersSpec.scala

(cherry picked from commit def84bf0c1338cbcdd65019d68453ea639d15ac3)

chore: fix failed in StreamConvertersSpec (#1655)

---

persistence/src/main/resources/reference.conf

see https://github.com/apache/pekko/blob/0855a3b035de3656f3297a0d7b6edda519d9038b/project/Dependencies.scala#L192

leveldb: update doc to match what we test

---

NOTICE
legal/PekkoNotice.txt
legal/pekko-actor-jar-notice.txt
legal/pekko-remote-jar-notice.txt

cherry pick 8fcac28ea2e3a9132554a68300e3ad27573116a4

add 2025 to copyright (#1651)

---

.github/workflows/nightly-1.0-builds.yml

Motivation:
refs: https://github.com/apache/pekko/issues/1694
Modification:
Only Run 1.0.x build on sunday.

chore: Run nightly 1.0 build weekly

---

project/Dependencies.scala
scripts/link-validator.conf

Motivation:
Bump Scala to 2.13.16

chore: bump Scala to 2.13.16

---

docs/src/main/paradox/migration/migration-guide-akka-1.0.x.md

update migration guide

---

project/PekkoBuild.scala
project/plugins.sbt

https://github.com/siculo/sbt-bom

chore: update sbt-bom 0.3.0 to sbt-sbom 0.4.0

---

plugins/serialversion-remover-plugin/src/main/scala/org/apache/pekko/Plugin.scala

more issues popping up in #1722 - this one looks easier to fix than the others

compile issue with scala 3 > 3.3

---

.scalafmt.conf
project/plugins.sbt

Motivation:
update scalafmt to 3.8.5
refs: https://github.com/apache/pekko/pull/1716

chore: update scalafmt to 3.8.5

---

docs/src/main/paradox/release-notes/releases-1.2.md

Need to discourage use in production

mistake in releases-1.2.md

---

multi-node-testkit/src/main/scala/org/apache/pekko/remote/testconductor/RemoteConnection.scala
project/Dependencies.scala
remote/src/main/scala/org/apache/pekko/remote/transport/netty/NettyTransport.scala

upgrade to Netty 4.2.0.Final

---

docs/src/main/paradox/stream/operators/Source-or-Flow/takeUntil.md
docs/src/main/paradox/stream/operators/index.md
stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowTakeWhileSpec.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/Flow.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/SubFlow.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/SubSource.scala
stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala

Motivation:
refs: https://github.com/apache/pekko/issues/1818

feat: Add takeUntil operator

---

stream-tests/src/test/scala/org/apache/pekko/stream/impl/fusing/AsyncCallbackSpec.scala
stream/src/main/scala/org/apache/pekko/stream/stage/GraphStage.scala

Motivation:
Add java api for `invokeWithFeedback` method.

feat: Add invokeWithFeedbackCompletionStage for javadsl.

---

serialization-jackson/src/test/java/jdoc/org/apache/pekko/serialization/jackson/v2a/CustomerMigration.java
serialization-jackson/src/test/scala/doc/org/apache/pekko/serialization/jackson/v2a/CustomerMigration.scala

* might be more
* but this is a start

avoid using deprecated Jackson methods

---

stream/src/main/scala/org/apache/pekko/stream/javadsl/Flow.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/SubFlow.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/SubSource.scala
stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala
stream/src/main/scala/org/apache/pekko/stream/stage/GraphStage.scala

Feature PR's at https://github.com/apache/pekko/pull/1820 and https://github.com/apache/pekko/pull/1776

chore: Add since for newly added methods

---

actor-tests/src/test/scala/org/apache/pekko/actor/ActorLifeCycleSpec.scala
actor-tests/src/test/scala/org/apache/pekko/actor/SchedulerSpec.scala
actor-typed-tests/src/test/scala/org/apache/pekko/actor/typed/AskSpec.scala
docs/src/test/scala/docs/stream/FlowStreamRefsDocSpec.scala
docs/src/test/scala/docs/testkit/TestkitDocSpec.scala
project/Dependencies.scala

chore: update Scala 3 to 3.3.6

---

README.md

Update REAMDE.md for newbies using Intellij for pekko

Add how to use Intellij IDEA on README.md

---

.github/workflows/binary-compatibility-checks.yml
.github/workflows/build-test-prValidation.yml
.github/workflows/dependency-graph.yml
.github/workflows/format.yml
.github/workflows/generate-doc-check.yml
.github/workflows/headers.yml
.github/workflows/link-validator.yml
.github/workflows/nightly-1.0-builds.yml
.github/workflows/nightly-1.1-builds.yml
.github/workflows/nightly-builds-aeron.yml
.github/workflows/nightly-builds.yml
.github/workflows/publish-1.0-docs.yml
.github/workflows/publish-1.0-nightly.yml
.github/workflows/publish-1.1-docs.yml
.github/workflows/publish-1.1-nightly.yml
.github/workflows/publish-nightly.yml
.github/workflows/scala-steward.yml
.github/workflows/scala3-build.yml
.github/workflows/timing-tests.yml

see https://github.com/apache/pekko-management/pull/429

CI: github actions use sha instead of version

---

.github/workflows/publish-1.0-nightly.yml
.github/workflows/publish-1.1-nightly.yml
.github/workflows/publish-nightly.yml

Due to major repository.apache.org issues that are affecting us every night.
based on https://github.com/apache/pekko/issues/1854#issuecomment-2903538870

CI: increase publish retries

---

serialization-jackson/src/main/resources/reference.conf
serialization-jackson/src/main/scala/org/apache/pekko/serialization/jackson/JacksonObjectMapperProvider.scala
serialization-jackson/src/test/scala/org/apache/pekko/serialization/jackson/JacksonSerializerSpec.scala

A new of feature enum added a while back in Jackson.
https://www.javadoc.io/doc/com.fasterxml.jackson.core/jackson-databind/2.18.4/com/fasterxml/jackson/databind/cfg/EnumFeature.html

support jackson enum features

---

cluster/src/test/scala/org/apache/pekko/cluster/MixedProtocolClusterSpec.scala

cherry pick 81559093dddf74d9f7ac08aa00dddd4d9e4fe632 #1865

allow compat check in cluster test (#1865)

---

stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowStatefulMapConcatSpec.scala
stream/src/main/scala/org/apache/pekko/stream/impl/fusing/Ops.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/Flow.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/StatefulMapConcatAccumulator.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/SubFlow.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/SubSource.scala
stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala
stream/src/main/scala/org/apache/pekko/stream/scaladsl/StatefulMapConcatAccumulator.scala

Motivation:
Fix https://github.com/apache/pekko/issues/1829
@mdedetrich Wdyt ?

feat: Add onComplete support for statefulMapConcat operator.

---

cluster/src/main/scala/org/apache/pekko/cluster/ClusterDaemon.scala
cluster/src/main/scala/org/apache/pekko/cluster/ConfigUtil.scala
cluster/src/main/scala/org/apache/pekko/cluster/SeedNodeProcess.scala
cluster/src/test/scala/org/apache/pekko/cluster/JoinConfigCompatCheckClusterSpec.scala

* cherry pick 9227912ea666f277d7ebc9dfedb53e6b2e768fa4 #1866

Join cluster check adjusted to support akka (#1866)

---

cluster/src/main/scala/org/apache/pekko/cluster/ClusterDaemon.scala
cluster/src/main/scala/org/apache/pekko/cluster/ConfigUtil.scala
cluster/src/main/scala/org/apache/pekko/cluster/SeedNodeProcess.scala
cluster/src/test/scala/org/apache/pekko/cluster/ConfigUtilSpec.scala
cluster/src/test/scala/org/apache/pekko/cluster/JoinConfigCompatCheckClusterSpec.scala
cluster/src/test/scala/org/apache/pekko/cluster/MixedProtocolClusterSpec.scala
remote/src/main/resources/reference.conf

cherry pick d7f0d510284f39d245ebf7cfebe0f78f6c8c614c #1877

support akka configs in InitJoinAck (#1877)

---

docs/src/main/paradox/release-notes/releases-1.1.md

Update releases-1.1.md (v1.1.4 release)

---

.github/workflows/publish-1.1-docs.yml

publish 1.1.4 docs

---

.scala-steward.conf
project/Dependencies.scala

seems safe to upgrade jackson for 1.2 releases

jackson 2.19.1

---

cluster-metrics/src/main/scala/org/apache/pekko/cluster/metrics/protobuf/MessageSerializer.scala
cluster-metrics/src/main/scala/org/apache/pekko/cluster/metrics/protobuf/NumberInputStream.scala
cluster-metrics/src/test/scala/org/apache/pekko/cluster/metrics/protobuf/NumberInputStreamSpec.scala

Cherry pick f4d8b8323ffa29428c332fbe18e54443827d398b #1899

tidy up metrics exchange (#1899)

---

remote/src/main/resources/reference.conf

small issue brought in as part of #1795

remote duplicate line in reference.conf

---

stream/src/main/scala/org/apache/pekko/stream/impl/fusing/Ops.scala

Motivation:
Tweak memory usage same as : https://github.com/apache/pekko/pull/1623

chore: Set vector builder to null after stage completed to avoid leak.

---

docs/src/main/paradox/stream/operators/Source-or-Flow/groupedAdjacentBy.md
docs/src/main/paradox/stream/operators/Source-or-Flow/groupedAdjacentByWeighted.md
docs/src/main/paradox/stream/operators/index.md
docs/src/test/java/jdocs/stream/operators/SourceOrFlow.java
docs/src/test/scala/docs/stream/operators/sourceorflow/GroupedAdjacentBy.scala
stream-tests/src/test/java/org/apache/pekko/stream/javadsl/FlowTest.java
stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowGroupedAdjacentByWeightedSpec.scala
stream/src/main/scala/org/apache/pekko/stream/impl/Stages.scala
stream/src/main/scala/org/apache/pekko/stream/impl/fusing/GroupedAdjacentByWeighted.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/Flow.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/SubFlow.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/SubSource.scala
stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala

Motivation:
refs: https://github.com/apache/pekko/issues/1821
Modification:
Add groupedAdjacentBy and GroupedAdjacentByWeighted operators.

feat: Add groupedAdjacentBy and GroupedAdjacentByWeighted operators.

---

persistence-typed-tests/src/test/scala/org/apache/pekko/persistence/typed/scaladsl/EventSourcedStashOverflowSpec.scala
persistence-typed-tests/src/test/scala/org/apache/pekko/persistence/typed/state/scaladsl/DurableStateBehaviorStashOverflowSpec.scala
persistence-typed/src/main/mima-filters/1.1.x.backwards.excludes/eventsourcedbehavior-stackoverflow.excludes
persistence-typed/src/main/resources/reference.conf
persistence-typed/src/main/scala/org/apache/pekko/persistence/typed/internal/EventSourcedSettings.scala
persistence-typed/src/main/scala/org/apache/pekko/persistence/typed/internal/ExternalInteractions.scala
persistence-typed/src/main/scala/org/apache/pekko/persistence/typed/internal/ReplayingEvents.scala
persistence-typed/src/main/scala/org/apache/pekko/persistence/typed/internal/Running.scala
persistence-typed/src/main/scala/org/apache/pekko/persistence/typed/state/internal/DurableStateSettings.scala
persistence-typed/src/main/scala/org/apache/pekko/persistence/typed/state/internal/DurableStateStoreInteractions.scala
persistence-typed/src/main/scala/org/apache/pekko/persistence/typed/state/internal/Recovering.scala
persistence-typed/src/main/scala/org/apache/pekko/persistence/typed/state/internal/Running.scala
persistence-typed/src/test/scala/org/apache/pekko/persistence/typed/internal/StashStateSpec.scala

Fix typed persistence stack overflow with many read only commands

---

.github/workflows/publish-1.1-docs.yml
docs/src/main/paradox/release-notes/releases-1.1.md

* pekko 1.1.5: release notes copied from 1.1.x branch - #1931

Release notes 1.1.5 (#1931)

---

.github/workflows/binary-compatibility-checks.yml
.github/workflows/build-test-prValidation.yml
.github/workflows/generate-doc-check.yml
.github/workflows/headers.yml
.github/workflows/link-validator.yml
.github/workflows/nightly-builds-aeron.yml
.github/workflows/nightly-builds.yml
.github/workflows/publish-nightly.yml
.github/workflows/scala3-build.yml
.github/workflows/timing-tests.yml

* build for main branch with Java 17 minimum
* all the java 8 build support can be removed in another PR

build with java 17

---

persistence-typed/src/main/java/org/apache/pekko/persistence/typed/serialization/ReplicatedEventSourcing.java
persistence-typed/src/main/mima-filters/2.0.x.backwards.excludes/remove-deprecated-methods.excludes
persistence-typed/src/main/scala/org/apache/pekko/persistence/typed/internal/EventSourcedBehaviorImpl.scala
persistence-typed/src/main/scala/org/apache/pekko/persistence/typed/javadsl/EventSourcedBehavior.scala
persistence-typed/src/main/scala/org/apache/pekko/persistence/typed/scaladsl/EventSourcedBehavior.scala

* low hanging fruit
* there is more that is deprecated but the code is more heavily wired in

persistence deprecations

---

cluster-metrics/src/main/java/org/apache/pekko/cluster/metrics/protobuf/msg/ClusterMetricsMessages.java
cluster-tools/src/main/scala/org/apache/pekko/cluster/pubsub/DistributedPubSubMediator.scala
cluster-typed/src/main/mima-filters/2.0.x.backwards.excludes/remove-deprecated-methods.excludes
cluster-typed/src/main/scala/org/apache/pekko/cluster/typed/ClusterSingleton.scala
cluster/src/main/java/org/apache/pekko/cluster/protobuf/msg/ClusterMessages.java
cluster/src/main/mima-filters/2.0.x.backwards.excludes/remove-deprecated-methods.excludes
cluster/src/main/scala/org/apache/pekko/cluster/ClusterEvent.scala
cluster/src/main/scala/org/apache/pekko/cluster/Member.scala
cluster/src/main/scala/org/apache/pekko/cluster/protobuf/ClusterMessageSerializer.scala
cluster/src/main/scala/org/apache/pekko/cluster/routing/ClusterRouterConfig.scala

remove some deprecated cluster code

---

actor-typed/src/main/scala/org/apache/pekko/actor/typed/javadsl/Routers.scala
actor-typed/src/main/scala/org/apache/pekko/actor/typed/scaladsl/Routers.scala
actor/src/main/scala/org/apache/pekko/actor/FSM.scala
persistence/src/main/scala/org/apache/pekko/persistence/fsm/PersistentFSM.scala
stream/src/main/scala/org/apache/pekko/stream/Materializer.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/Sink.scala
stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala
stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala
stream/src/main/scala/org/apache/pekko/stream/scaladsl/Sink.scala
stream/src/main/scala/org/apache/pekko/stream/scaladsl/Source.scala

* 2.0.x change
* these annotations have been there since Akka days

remove deprecated names annotations

---

actor-tests/src/test/scala/org/apache/pekko/util/AsciiStringCopySpec.scala
actor/src/main/java/org/apache/pekko/util/Unsafe.java

* pekko.util.Unsafe is an internal class
* we only support Java 17+ in Pekko 2

remove Unsafe.isIsJavaVersion9Plus

---

actor/src/main/java/org/apache/pekko/actor/AbstractActorRef.java
actor/src/main/java/org/apache/pekko/actor/dungeon/AbstractActorCell.java
actor/src/main/java/org/apache/pekko/dispatch/AbstractBoundedNodeQueue.java
actor/src/main/java/org/apache/pekko/dispatch/AbstractMessageDispatcher.java
actor/src/main/java/org/apache/pekko/dispatch/AbstractNodeQueue.java
actor/src/main/java/org/apache/pekko/pattern/AbstractCircuitBreaker.java
actor/src/main/java/org/apache/pekko/pattern/AbstractPromiseActorRef.java
actor/src/main/java/org/apache/pekko/util/Unsafe.java
actor/src/main/mima-filters/2.0.x.backwards.excludes/util-unsafe-refactor.excludes
actor/src/main/scala/org/apache/pekko/actor/LightArrayRevolverScheduler.scala
actor/src/main/scala/org/apache/pekko/actor/RepointableActorRef.scala
actor/src/main/scala/org/apache/pekko/actor/dungeon/Children.scala
actor/src/main/scala/org/apache/pekko/actor/dungeon/Dispatch.scala
actor/src/main/scala/org/apache/pekko/dispatch/AbstractDispatcher.scala
actor/src/main/scala/org/apache/pekko/pattern/AskSupport.scala
actor/src/main/scala/org/apache/pekko/pattern/CircuitBreaker.scala
remote/src/main/java/org/apache/pekko/remote/artery/AbstractAssociation.java
remote/src/main/scala/org/apache/pekko/remote/artery/Association.scala

* using VarHandle in more places
* there are a couple of uses left over that are not yet working and I intend to tackle them in a follow up PR

avoid sun.misc.Unsafe by using VarHandles

---

LICENSE
actor-tests/src/test/scala/org/apache/pekko/io/ByteBufferCleanerSpec.scala
actor/src/main/java/org/apache/pekko/io/ByteBufferCleaner.java
actor/src/main/scala/org/apache/pekko/io/DirectByteBufferPool.scala

cherry pick 96a84ca89ba81ca625cccca3f57449d432a6218b #2020

use better byte buffer cleaner (#2020)

---

.git-blame-ignore-revs

Motivation:
Add to git blame ignore

chore: ignore java fmt

---

actor-testkit-typed/src/test/java/jdocs/org/apache/pekko/actor/testkit/typed/javadsl/AsyncTestingExampleTest.java
actor-tests/src/test/java/org/apache/pekko/actor/StashJavaAPITestActors.java
actor-typed-tests/src/test/java/jdocs/org/apache/pekko/typed/AggregatorTest.java
actor-typed-tests/src/test/java/jdocs/org/apache/pekko/typed/InteractionPatternsTest.java
actor-typed-tests/src/test/java/jdocs/org/apache/pekko/typed/StashDocSample.java
actor-typed-tests/src/test/java/org/apache/pekko/actor/typed/javadsl/ActorCompile.java
actor-typed-tests/src/test/java/org/apache/pekko/actor/typed/javadsl/AdapterTest.java
actor/src/main/java/org/apache/pekko/japi/pf/FSMStateFunctionBuilder.java
persistence/src/main/java/org/apache/pekko/persistence/fsm/japi/pf/FSMStateFunctionBuilder.java
persistence/src/test/java/org/apache/pekko/persistence/fsm/AbstractPersistentFSMTest.java
remote/src/main/java/org/apache/pekko/remote/artery/compress/CountMinSketch.java
stream-typed/src/test/java/docs/org/apache/pekko/stream/typed/ActorSourceExample.java
stream-typed/src/test/java/docs/org/apache/pekko/stream/typed/ActorSourceWithBackpressureExample.java
stream-typed/src/test/java/org/apache/pekko/stream/typed/javadsl/ActorSourceSinkCompileTest.java

bind instanceof to named variables

---

stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowMapWithResourceSpec.scala
stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala

cherry picks 6ef6ae1446031c5838c66b6dbdd4240b1ac2bb8a #1949

Allow overriding dispatcher in mapWithResource (#1949)

---

build.sbt
project/OSGi.scala

Signed-off-by: Robert Varga <robert.varga@pantheon.tech>

Add OSGi headers to pekko-pki

---

build.sbt
project/OSGi.scala

cherry pick 2a04e9649ea0ae47c89252f99d1c3bdafedc96bd #2107

Add OSGi headers to pekko-pki (#2107)

---

actor-tests/src/test/java-jdk21-only/org/apache/pekko/actor/StashJavaAPITestUntypedActors.java
actor-tests/src/test/java-jdk21-only/org/apache/pekko/actor/UntypedStashJavaAPI.java
actor/src/main/scala/org/apache/pekko/actor/AbstractActor.scala

Motivation:
With will works better than the AbstractActor with Java 21's pattern matching

feat: Add Untyped actor with stash for Java 21

---

project/Dependencies.scala

Fix CVEs
https://netty.io/news/2025/09/03/4-2-5.html

chore: Update nettyVersion to 4.2.5.Final

---

actor/src/main/scala-2.12/org/apache/pekko/util/ByteString.scala
actor/src/main/scala-2.13/org/apache/pekko/util/ByteString.scala
actor/src/main/scala-3/org/apache/pekko/util/ByteString.scala
actor/src/main/scala/org/apache/pekko/actor/dungeon/Children.scala
actor/src/main/scala/org/apache/pekko/util/LineNumbers.scala
distributed-data/src/main/scala/org/apache/pekko/cluster/ddata/Replicator.scala

Motivation:
Make it performant better in Scala 3
https://github.com/scala/scala3/issues/8880

chore: Use while loop

---

actor/src/main/scala/org/apache/pekko/dispatch/AbstractDispatcher.scala
actor/src/main/scala/org/apache/pekko/dispatch/BalancingDispatcher.scala
actor/src/main/scala/org/apache/pekko/dispatch/Dispatcher.scala
actor/src/main/scala/org/apache/pekko/dispatch/Mailbox.scala
bench-jmh/src/main/scala/org/apache/pekko/actor/TellOnlyBenchmark.scala

Motivation: 
Add parameter name for easy reading the code.

chore: Add  boolean parameter name when call registerForExecution

---

actor/src/main/mima-filters/2.0.x.backwards.excludes/remove-deprecated-methods.excludes
actor/src/main/scala/org/apache/pekko/dispatch/AbstractDispatcher.scala
actor/src/main/scala/org/apache/pekko/dispatch/PinnedDispatcher.scala
actor/src/main/scala/org/apache/pekko/dispatch/ThreadPoolBuilder.scala

Motivation:
refs: https://github.com/apache/pekko/issues/2171

chore: Remove ExecutorServiceFactoryProvider from ThreadPoolConfig

---

actor/src/main/resources/reference.conf

chore: Fix typo about the virtual thread support.

---

.asf.yaml

protect 1.3.x branch

---

actor-tests/src/test/scala/org/apache/pekko/util/ByteStringSpec.scala
actor/src/main/mima-filters/1.2.x.backwards.excludes/bytestring-indexOf-overload.excludes
actor/src/main/scala-2.12/org/apache/pekko/util/ByteString.scala
actor/src/main/scala-2.13/org/apache/pekko/util/ByteString.scala
actor/src/main/scala-3/org/apache/pekko/util/ByteString.scala

Backport overload of indexOf from and to

---

testkit/src/main/scala/org/apache/pekko/testkit/javadsl/TestKit.scala
testkit/src/test/java/org/apache/pekko/testkit/javadsl/TestKitApiTest.java

cherry pick 6906820e697d6c3289c54687561a3d7b70d5baa6 (#2277)

JavaDSL TestKit - add shutdownActorSystem that takes Java Duration params

---

actor-tests/src/test/scala/org/apache/pekko/actor/ActorSystemSpec.scala
actor-tests/src/test/scala/org/apache/pekko/event/LoggingReceiveSpec.scala
actor/src/main/scala-2.13/org/apache/pekko/util/ByteString.scala
actor/src/main/scala/org/apache/pekko/actor/Address.scala
actor/src/main/scala/org/apache/pekko/util/FrequencySketch.scala
persistence/src/main/scala/org/apache/pekko/persistence/Eventsourced.scala
project/Dependencies.scala
remote/src/main/scala/org/apache/pekko/remote/artery/Control.scala
stream/src/main/scala/org/apache/pekko/stream/impl/QueueSource.scala
stream/src/main/scala/org/apache/pekko/stream/impl/SetupStage.scala
stream/src/main/scala/org/apache/pekko/stream/impl/Sinks.scala
stream/src/main/scala/org/apache/pekko/stream/impl/io/TcpStages.scala
testkit/src/test/scala/org/apache/pekko/testkit/metrics/MetricsKit.scala

Scala 2.13.17

---

actor-typed/src/main/scala/org/apache/pekko/actor/typed/scaladsl/package.scala
actor/src/main/scala/org/apache/pekko/actor/setup/ActorSystemSetup.scala
actor/src/main/scala/org/apache/pekko/event/Logging.scala
persistence-query/src/main/scala/org/apache/pekko/persistence/query/typed/EventEnvelope.scala

relates to https://github.com/apache/pekko-grpc/pull/522

try to remove unnecessary map calls
