.asf.yaml
While not so relevant now, the historical direction of a lot of Scala based projects (which Pekko is one, the Java API is technically a separate layer, i.e. none of the core is implemented in Java) is that at some point they end up adding support for runtimes aside of JVM, i.e. graalvm/scala-native, even Scala.js (or anything else that props up).
At some point Pekko might explore such things, in which case running on the JVM isn't the most accurate description.
=> Update description of project

.asf.yaml
* Squash merges keep the Git history clean
* see https://medium.com/swlh/squash-and-rebase-git-basics-5cb1be1e0dac
* Add back notifications settings that were accidentally removed when I reset the last merge commit
* aim is to not have emails go to dev mailing list every time someone comments on a PR  
Features are documented in https://cwiki.apache.org/confluence/display/INFRA/git+-+.asf.yaml+features
=> Only allow Squash merges and update notification email addresses

.github/workflows/binary-compatibility-checks.yml, .github/workflows/multi-node.yml, .github/workflows/nightly-builds.yml, .github/workflows/publish-docs.yml, .github/workflows/publish.yml, .github/workflows/scala3-build.yml, .github/workflows/timing-tests.yml
* we need plenty of work to get Github workflows working
* we don't yet have an email address to send our failures to
* current code has an Akka team email address and I don't want to spam them with Pekko build issues
=> temporarily remove email action from github builds

.github/workflows/build-test-prValidation.yml, .github/workflows/format.yml
This PR is a follow up from https://github.com/apache/incubator-pekko/pull/2 but only contains the replacement of sbt check with github actions. It also implements the git ratcheting system so that it only performs a diff against files that have actually been changed against `origin/main` meaning the format step should take ~10-20 seconds on average since it doesn't format the whole codebase as well as being initiated immediately rather than having to wait for the main test PR validation step to happen. Note that currently when one formats the code via `sbt-scalafmt` it takes roughly 1 minute.
Here is an example of a test run that I made deliberately to fail (i.e. I committed a single file that wasn't formatted). It took 4 seconds (ignoring the git branch checkout), 20 seconds full. …
=> Add github workflow to check scala code is formatted

.github/workflows/nightly-builds.yml
Despite its name this build doesn't actually publish anything (except for test reports). It just runs some more verbose testing on different JDKs, cluster, artery, and some other things. We'll need to add the `marcospereira/action-surefire-report@v1` action to an allow list, or find an alternative, to get test report artifacts published.
Build on my fork: https://github.com/seglo/incubator-pekko/actions/runs/3400931121
=> Fix nightly build action

.asf.yaml
This is to prevent accidental force pushes onto main (see https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features#Git.asf.yamlfeatures-Branchprotection).
=> Make main branch protected

akka-docs/src/test/java/jdocs/stream/operators/flow/StatefulMap.java
The `.filterNot(List::isEmpty)` was missing, now fixed.
=> =doc Update java code sample of StatefulMap.

CONTRIBUTING.md, README.md
Update the information in the README. I simplified the wording a bit to avoid copying the exact wording from Akka, and added a note about the project being forked from Akka.
We still need to migrate the CONTRIBUTING file as well, but I think it makes sense to do that separately since it's far more complex and probably requires some thought about how the Pekko dev process will differ from Akka.
=> Update README for Pekko name

.github/workflows/binary-compatibility-checks.yml, .github/workflows/build-test-prValidation.yml, .github/workflows/link-validator.yml, .github/workflows/multi-node.yml, .github/workflows/nightly-builds.yml, .github/workflows/scala3-build.yml, .github/workflows/scala3-compile.yml, .github/workflows/timing-tests.yml
Getting warnings like this:
```
Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
This upgrade may not help that but it's usually good to keep up to date with versions.
=> upgrade cache-action due to build warnings

.github/workflows/binary-compatibility-checks.yml, .github/workflows/build-test-prValidation.yml, .github/workflows/format.yml, .github/workflows/link-validator.yml, .github/workflows/multi-node.yml, .github/workflows/nightly-builds.yml, .github/workflows/publish-docs.yml, .github/workflows/publish.yml, .github/workflows/scala3-build.yml, .github/workflows/scala3-compile.yml, .github/workflows/timing-tests.yml
See warnings on https://github.com/apache/incubator-pekko/actions/runs/3480833557
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2, olafurpg/setup-scala@v10
```
=> update github actions due to warnings about nodejs version

project/AddLogTimestamps.scala, project/Doc.scala, project/MiMa.scala, project/MultiNode.scala, project/ValidatePullRequest.scala
Renames the `CliOption` that happens to have `akka` in the name. @pjfanning Note that this also reverts the change in https://github.com/apache/incubator-pekko/pull/65, the original cause for the CI suddenly checking for mima is that the https://github.com/apache/incubator-pekko/pull/58 PR changed the `-Dakka.mima.enabled=false` argument to `-Dpekko.mima.enabled=false` in the `build-test-prValidation.yml` workflow but not the `CliOption` which this PR is fixing.
=> Rename akka to pekko in CliOption and fix mima

project/ValidatePullRequest.scala
Make use of `java.io.File.separatorChar` to work properly on Windows
A follow up of https://github.com/apache/incubator-pekko/pull/75
=> =sbt Make use of `File.separatorChar` to avoid exception.

.github/workflows/binary-compatibility-checks.yml, .github/workflows/build-test-prValidation.yml, .github/workflows/multi-node.yml, .github/workflows/nightly-builds.yml, .github/workflows/scala3-build.yml, .github/workflows/scala3-compile.yml, .github/workflows/timing-tests.yml
Fix for #59 
Replace by prior copy of `.jvmopts-ci` into `.jvmopts` which is the file sbt natively supports
Naive approach, just trying to help, not sure if that's what you expected? 😄  It seems sbt doesn't support a custom filename for jvm opts
=> Remove sbtx usage

build.sbt
This PR improves the `akka-actor-typed` `initialCommands` which are executed when you start the Scala REPL shell in the sbt console with `akka-actor-typed/console`. The two main improvements are
* We `import org.apache.pekko` which means that further pekko imports don't need the `org.apache` prefix
* Also `import scala.language.postfixOps` since especially in an Scala REPL session people often find it more convenient to write `5 seconds` instead of `5.seconds` or `seconds(5)`.
I can confirm that locally the REPL still works on my machine, i.e.
```
[info] Useful sbt tasks:
[info] >  compile - Compile the current project
[info] >  test - Run all the tests
[info] >  testOnly *.AnySpec - Only run a selected test
[info] >  verifyCodeStyle - Verify code style
[info] >  applyCodeStyle - Apply …
```
=> Improve akka-actor-typed initialCommands

project/PekkoBuild.scala
This is particularly helpful if you want to try local pekko changes in another project
=> Add sbt UsefulTask for publishLocal

project/build.properties
Updates to the latest SBT version, this is important because its solves an SBT issue with the new Mac ARM machines (see https://github.com/sbt/sbt/releases/tag/v1.8.2).
=> Update latest sbt version

project/project-info.conf
In trying to replace the akka paradox theme with just the basic paradox theme, one issue I found is that akka/lightbend projects use the concept of readiness levels which comes from sbt-paradox-project-info https://github.com/lightbend/sbt-paradox-project-info#readiness-levels.
While it is possible to provide our own readiness-levels, this doesn't make too much sense for Apache projects. Also in doing so we would have to create our own sbt-paradox-pekko-project-info (akin to https://github.com/lightbend/sbt-paradox-lightbend-project-info) which is too much overhead for now.
If we do end up deciding on readiness levels this should be done via an Apache process and we can always add it in later.
References: https://github.com/apache/incubator-pekko/issues/32
=> Remove readiness levels

docs/src/main/paradox/additional/osgi.md, docs/src/main/paradox/durable-state/persistence-query.md, docs/src/main/paradox/persistence-query-leveldb.md, docs/src/main/paradox/persistence-query.md, docs/src/main/paradox/remoting-artery.md, docs/src/main/paradox/typed/actor-discovery.md, docs/src/main/paradox/typed/actor-lifecycle.md, docs/src/main/paradox/typed/cluster-dc.md, docs/src/main/paradox/typed/coexisting.md, docs/src/main/paradox/typed/from-classic.md, docs/src/main/paradox/typed/guide/modules.md, docs/src/main/paradox/typed/interaction-patterns.md, docs/src/main/paradox/typed/reliable-delivery.md, docs/src/main/paradox/typed/routers.md, docs/src/main/paradox/typed/stash.md
When looking at the docs I noticed that the `artifact` fields in `project-info` still had the `akka-` prefix.
=> Fix paradox project info artifact names

.github/workflows/publish-nightly.yml
I think this makes more sense otherwise snapshots will quickly become truncated or if we changed the eviction strategy to actually be time based we will end up with a lot of artifacts on nightly.
=> Publish nightly once a day

CONTRIBUTING.md
* Adjust `create one` link to provide the choice of which kind of issue to raise (feature/bug/discussion/vulnerability) (previously created a bare issue with no template).
* Adjust `fork` link to create a fork (previously just showed the repo).
* Insert missing word `guide`.
* Insert sentence-closing punctuation.
=> Fix link targets and minor wording in CONTRIBUTING

.github/workflows/build-test-prValidation.yml, actor-tests/src/test/scala-2.12/org/apache/pekko/util/LineNumberSpec.scala, actor-tests/src/test/scala-2.12/org/apache/pekko/util/TypedMultiMapSpec.scala, actor-tests/src/test/scala-3/org/apache/pekko/util/LineNumberSpec.scala, actor-typed/src/main/scala-2.12/org/apache/pekko/actor/typed/internal/receptionist/Platform.scala, actor-typed/src/main/scala-3/org/apache/pekko/actor/typed/internal/receptionist/Platform.scala, actor/src/main/scala-2.12/org/apache/pekko/compat/Future.scala, actor/src/main/scala-2.12/org/apache/pekko/compat/PartialFunction.scala, actor/src/main/scala-2.12/org/apache/pekko/dispatch/internal/SameThreadExecutionContext.scala, actor/src/main/scala-2.12/org/apache/pekko/dispatch/internal/ScalaBatchable.scala, actor/src/main/scala-2.12/org/apache/pekko/util/ByteIterator.scala, actor/src/main/scala-2.12/org/apache/pekko/util/ByteString.scala, actor/src/main/scala-2.12/org/apache/pekko/util/ccompat/CompatImpl.scala, actor/src/main/scala-2.12/org/apache/pekko/util/ccompat/ccompatUsedUntil213.scala, actor/src/main/scala-2.12/org/apache/pekko/util/ccompat/package.scala, actor/src/main/scala-3/org/apache/pekko/dispatch/internal/ScalaBatchable.scala, actor/src/main/scala-3/org/apache/pekko/util/ByteIterator.scala, actor/src/main/scala-3/org/apache/pekko/util/ByteString.scala, cluster-typed/src/main/scala-2.12/org/apache/pekko/cluster/typed/internal/receptionist/ClusterReceptionistProtocol.scala, cluster-typed/src/main/scala-3/org/apache/pekko/cluster/typed/internal/receptionist/ClusterReceptionistProtocol.scala, distributed-data/src/main/scala-3/org/apache/pekko/cluster/ddata/GSet.scala, persistence/src/main/scala-3/org/apache/pekko/persistence/TraitOrder.scala
As noticed in https://github.com/apache/incubator-pekko/issues/107#issuecomment-1400285147 `headerCreate` runs during `ci-release` and will change the workspace so that it is not clean. Consequently, the nightly build will create snapshots with timestamps (and might just fail for actual releases).
=> Fix 2.12 copyright headers and enable headerCheckAll for all Scala versions

.github/workflows/publish-nightly.yml
There was some issues in the nightly build, for example graph viz not being available for the standard publish. Also refactoring the pipeline a bit to make it more clear
=> Fix minor bugs and improve nightly publish-nightly.yml

project/Publish.scala
So I figured out the what was causing the publishing issues, it turns out that since sbt-ci-release was added into pekko, it overrode the settings defined in https://github.com/apache/incubator-pekko/blob/main/project/Publish.scala#L25-L56.
This is because sbt-ci-release depends on sbt-sonatype, which by default points to the OS sonatype public repo. This PR tries to set various sbt-sonatype settings so that sbt-ci-release ends up publishing to Apache's Nexus repo instead of sonatype, since they both use Nexus it should theoretically work however if it doesn't we may end up having to remove sbt-ci-release (because its hardcoded to use sbt-sonatype).
At least locally when I run `sbt show publishTo` it does appear the settings are now correctly working
```
pekko > show publishTo
[info] pki …
```
=> Properly set sonatype repo settings for publishTo

project/Publish.scala
Since our sonatype is having a bit of an identity crisis having to look like an Apache's nexus repo, I need to change the name of the credential, see
```
[warn] versionScheme setting is empty; set `ThisBuild / versionScheme := Some("early-semver")`, `Some("semver-spec")` or `Some("pvp")`
[warn] so tooling can use it for eviction errors etc - https://www.scala-sbt.org/1.x/docs/Publishing.html
[error] Unable to find credentials for [Sonatype Nexus Repository Manager @ repository.apache.org].
[error]   Is one of these realms misspelled for host [repository.apache.org]:
[error]   * Apache Nexus Repository Manager
```
from the last run at https://github.com/apache/incubator-pekko/actions/runs/4015355806/jobs/6896983341
Related to https://github.com/apache/incubator-pekko/issues/103
=> Rename name for Apache nexus repo to work with Sonatype

docs/src/main/paradox/additional/deploying.md, docs/src/main/paradox/additional/faq.md, docs/src/main/paradox/additional/operations.md, docs/src/main/paradox/additional/osgi.md, docs/src/main/paradox/additional/packaging.md, docs/src/main/paradox/additional/rolling-updates.md, docs/src/main/paradox/cluster-client.md, docs/src/main/paradox/common/binary-compatibility-rules.md, docs/src/main/paradox/common/circuitbreaker.md, docs/src/main/paradox/common/io-layer.md, docs/src/main/paradox/common/may-change.md, docs/src/main/paradox/common/other-modules.md, docs/src/main/paradox/index.md, docs/src/main/paradox/typed/extending.md, docs/src/main/paradox/typed/guide/introduction.md, docs/src/main/paradox/typed/guide/modules.md
We're going to have to go through docs page by page to decide when it's necessary to use 'Apache Pekko' as opposed to `Pekko`.
We should probably always start a page by referring to 'Apache Pekko' but later in the page, we might start shortening it to Pekko.
Current docs on https://pekko.apache.org highlight that we don't use 'Apache Pekko' enough.
This PR focuses on a few very visible instances that affect the table of contents.
=> docs: Apache Pekko naming

.github/workflows/nightly-builds.yml
I made a mistake in my last PR.
https://github.com/apache/incubator-pekko/pull/148/files#diff-e780cb03e0575bf97176af613cf9b23d9337cc6a8d309a7475704fc756cfcce3R166
I copy/pasted this from another project and inadvertently kept the wrong variable name (java-version instead of jdkVersion) but then reviewing the existing variable, I see now that setup-java requires numeric params - so I changed the matrix values and anything that used them. I renamed the param to javaVersion to match the naming style in this file.
I removed extraopts because it always appears to be set to ""
=> try to fix nightly build issue

actor/src/main/scala/org/apache/pekko/event/japi/EventBusJavaAPI.scala, docs/src/test/scala/docs/actor/SharedMutableStateDocSpec.scala, remote/src/test/scala/org/apache/pekko/remote/artery/RollingEventLogSimulationSpec.scala, stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/GraphUnzipWithSpec.scala
I ran `sbt scalafmtAll javafmtAll scalafmtSbt` and got these diffs
Just thought it best to do a dedicated PR instead of having these appear in PR dedicated to fixing a particular issue (but that also needs scalafmt to be run - thus accidentally adding these unrelated diffs).
=> diffs when running scalafmtAll

.github/workflows/publish-nightly.yml
The error message before was
```
rsync: mkdir "***/pekko/pekko-docs-main/docs" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at main.c(682) [Receiver=3.1.3]
```
which might related to the trailing slash.
=> fix publish docs rsync

cluster-sharding-typed/src/main/java/org/apache/pekko/cluster/sharding/typed/internal/protobuf/ShardingMessages.java, cluster-sharding/src/main/java/org/apache/pekko/cluster/sharding/protobuf/msg/ClusterShardingMessages.java, cluster-typed/src/main/java/org/apache/pekko/cluster/typed/internal/protobuf/ClusterMessages.java, cluster-typed/src/main/java/org/apache/pekko/cluster/typed/internal/protobuf/ReliableDelivery.java, cluster/src/main/java/org/apache/pekko/cluster/protobuf/msg/ClusterMessages.java, distributed-data/src/main/java/org/apache/pekko/cluster/ddata/protobuf/msg/ReplicatedDataMessages.java, distributed-data/src/main/java/org/apache/pekko/cluster/ddata/protobuf/msg/ReplicatorMessages.java, multi-node-testkit/src/main/java/org/apache/pekko/remote/testconductor/TestConductorProtocol.java, persistence-query/src/main/java/org/apache/pekko/persistence/query/internal/protobuf/QueryMessages.java, persistence-typed/src/main/java/org/apache/pekko/persistence/typed/serialization/ReplicatedEventSourcing.java, persistence/src/main/java/org/apache/pekko/persistence/serialization/MessageFormats.java, remote-tests/src/test/java/org/apache/pekko/remote/artery/protobuf/TestMessages.java, remote/src/main/java/org/apache/pekko/remote/WireFormats.java, remote/src/test/java/org/apache/pekko/remote/ProtobufProtocol.java, stream/src/main/java/org/apache/pekko/stream/StreamRefMessages.java
By regenerating protobuf messages with `protobufGenerate` in sbt after the package renames.
Fixes #167, #164
=> fix binary protobuf descriptor data

build.sbt, project/plugins.sbt
This makes sure that the binaries will actually contain the LICENSE files from the resource generators in `META-INF`.
Fixes #140.
=> make sure to include resources in protobuf-v3 assembly

.github/workflows/publish-nightly-docs.yml
The new path for nightlies will be
pekko/docs/pekko/main-snapshot/{docs,api,japi}
Refs #179
This will also try to use a single rsync invocation by building up the destination folder structure up front.
=> change directory structure for nightly documentation publish

.github/workflows/link-validator.yml, .github/workflows/multi-node.yml, .github/workflows/scala3-build.yml, .github/workflows/scala3-compile.yml, .github/workflows/timing-tests.yml
This is a precursor to get https://github.com/apache/incubator-pekko/issues/23 working because the status checks are reliant on the name of the check hence why this PR is renaming check names that contain Akka to Pekko so that we don't have to update it again in the future.
=> Rename github action names to Pekko

discovery/src/main/scala/org/apache/pekko/discovery/Discovery.scala
* pekko-discovery will not work directly with any implementation of Akka Discovery.
* we've already messed up this test with a global replace that affects the classname
=> remove check for old implementation of Akka Discovery

project/project-info.conf
as a relative url either the link at https://pekko.apache.org/docs/pekko/current/actors.html or at https://pekko.apache.org/docs/pekko/current/typed/actors.html would be wrong
=> Fix link to snapshots repository documentation

project/plugins.sbt
Updates sbt-apache-sonatype to latest version. I also did some quick cursory checking of relevant keys (i.e. `publishTo` and `apacheSonatypeLicenseFile`) and there appears to be no regressions.
=> Updates sbt-apache-sonatype

.asf.yaml
Adds a github PR status check which disallows PR's from being merged if the code is not formatted. Note that its been verified that this works in another pekko module (see https://github.com/apache/incubator-pekko-sbt-paradox/blob/main/.asf.yaml#L28-L35)
=> Add github PR check to make sure code is formatted

stream/src/main/scala/com/typesafe/sslconfig/pekko/PekkoSSLConfig.scala
* this class is deprecated
* the deprecation notices were missed when I previously changed the version numbers on other deprecation notices to highlight the version number is an Akka version as opposed to a Pekko version
* renamed one akka named param
* added a further deprecation to highlight one particular function where calling it just leads to a log warning (and nothing else is done)
=> update Akka refs in PekkoSSLConfig.scala

docs/src/main/paradox/common/binary-compatibility-rules.md
* partially related to #142 
* I'm leaving #142 open to deal with changing all the refs to Pekko 2.5 and Pekko 2.6 - it's sort of hard to come up with examples that make sense when we haven't done any releases yet - it may be better just to delete a lot of the docs about specific examples and just give a high level commitment to binary compatibility
=> remove section about Akka 2.4 versioning change

.github/workflows/build-test-prValidation.yml, .github/workflows/headers.yml, project/CopyrightHeader.scala
Similar to https://github.com/apache/incubator-pekko-http/pull/77, moves the header check into its own github workflow. Note that there are some slight differences compared to pekko-http, but this is due to bespoke pekko core differences (which can be seen in the code removed from `build-test-prValidation.yml`).
=> Move header check into its own github action

README.md
This PR is a follow on from https://github.com/apache/incubator-pekko/pull/202, it adds a badge to `README.md` which shows the current status of nightly aeron tests
=> Add badges for nightly tests

.asf.yaml
The intention behind this PR is to test the "check headers" status check on a branch that is not `main`, since if its done incorrectly then you can block PR's from being merged entirely in the project until INFRA manually unblocks it.
Once this PR is merged than future test PR's will be made against `test` to see if the status check works as expected, at which point we will change the status check to the `main` branch.
=> Test github actions check headers status check

stream/src/main/scala/org/apache/pekko/stream/javadsl/Flow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SubFlow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SubSource.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala
refs: https://github.com/apache/incubator-pekko/issues/224
Drop the deprecation annotation on `Flow#recoverWith`
=> =str Remove the deprecation annotation on Flow#recoverWith.

.asf.yaml
This PR adds a github status check to make sure source files have the appropriate headers before a PR can be merged. This feature has already been tested on the `temp` branch to make sure that it works, see 
https://github.com/apache/incubator-pekko/pull/218
I have also tested the negative case in (i.e. I deliberately broke a header for a source file and to verify that you cannot merge the PR).
Note that there is some concern about adding this check before the all of the headers have been added to the source files (see https://github.com/apache/incubator-pekko/pull/218#discussion_r1118091218). Technically speaking this is a non concern because sbt-header allows you to precisely control which files get checked (see the `headerSources` sbt setting key, i.e. …
=> Add headers to github actions status check

LICENSE
I accidentally removed this LICENSE text in https://github.com/apache/incubator-pekko/pull/237/files
=> add back license text accidentally overwritten

LICENSE, NOTICE, legal/PekkoNotice.txt, legal/pekko-actor-jar-license.txt, project/AddMetaInfLicenseFiles.scala
Applies changes similar to ones already in https://github.com/apache/incubator-pekko-http
* at the jar level, most jars only need the vanilla Pekko Notice - not the source repo 'NOTICE' file that has a fair few amendments that are specific to just a few jars
* tidy up text about scala-collection-compat license and notice to not specifically mention Scala-Lang team
* https://github.com/apache/incubator-pekko/issues/241
=> update pekko notice used in jars

actor/src/main/scala-2.12/org/apache/pekko/util/ccompat/package.scala, plugins/serialversion-remover-plugin/src/main/scala/org/apache/pekko/Plugin.scala
This adds a `.mapValues` for `IterableView` which is a Scala 2.12 specific method that is necessary to get pekko-connectors-kafka to compile for 2.12. Note that the method has been taken from https://github.com/scala/scala-collection-compat/pull/220 which is where the other methods in this file come from (basically this exists to avoid adding scala-collection-compat as a dependency of Pekko).
=> Add mapValues for Scala 2.12 collection compat

actor/src/main/scala-2.12/org/apache/pekko/util/ccompat/package.scala
Same deal as https://github.com/apache/incubator-pekko/pull/251 but with another method (`filterKeys`) which is also used by pekko-connectors-kafka.
Equivalent source is here https://github.com/scala/scala-collection-compat/blob/0737983fded4dada1c9ad20ae34d2a98b0b3083f/compat/src/main/scala-2.11_2.12/scala/collection/compat/PackageShared.scala#L634-L635
=> Add filterKeys for Scala 2.12 collection compat

actor-tests/src/test/scala/org/apache/pekko/util/ByteStringSpec.scala, actor/src/main/scala-2.12/org/apache/pekko/util/ByteString.scala
While working on https://github.com/apache/incubator-pekko-connectors/pull/74#pullrequestreview-1350324353 I noticed that while there is an `IterableOnce[Byte]` apply method in `ByteString` for Scala 2.13, there isn't the Scala 2.12 `Iterable[Byte]` equivalent apply method. Note that the already existing Scala 2.13 variant can be found at https://github.com/apache/incubator-pekko/blob/main/actor/src/main/scala-2.13/org/apache/pekko/util/ByteString.scala#L1002-L1009 and https://github.com/apache/incubator-pekko/blob/main/actor/src/main/scala-2.13/org/apache/pekko/util/ByteString.scala#L40-L43.
This change can be considered safe because if you look at the implementation either for the already existing Scala 2.13 or the Scala 2.12 variant being added in this PR, in both cases it internally …
=> Add Scala 2.12 equivalent Iterator apply method for ByteString

actor/src/main/scala/org/apache/pekko/actor/dungeon/Children.scala, actor/src/main/scala/org/apache/pekko/pattern/AskSupport.scala, actor/src/main/scala/org/apache/pekko/pattern/CircuitBreaker.scala, project/Dependencies.scala, project/JdkOptions.scala, project/PekkoDisciplinePlugin.scala, scripts/link-validator.conf
This PR updates the Scala versions of Akka.
References: https://github.com/apache/incubator-pekko/issues/6
=> Update Scala versions

docs/src/main/paradox/actors.md, docs/src/main/paradox/cluster-client.md, docs/src/main/paradox/common/binary-compatibility-rules.md, docs/src/main/paradox/fault-tolerance.md, docs/src/main/paradox/project/downstream-upgrade-strategy.md, docs/src/main/paradox/project/rolling-update.md, docs/src/main/paradox/remoting-artery.md, docs/src/main/paradox/remoting.md, docs/src/main/paradox/stream/operators/Flow/futureFlow.md, docs/src/main/paradox/stream/operators/Flow/lazyFlow.md, docs/src/main/paradox/stream/operators/Flow/lazyFutureFlow.md, docs/src/main/paradox/stream/operators/Flow/lazyInitAsync.md, docs/src/main/paradox/stream/operators/RetryFlow/withBackoff.md, docs/src/main/paradox/stream/operators/RetryFlow/withBackoffAndContext.md, docs/src/main/paradox/stream/operators/Sink/lazyInitAsync.md, docs/src/main/paradox/stream/operators/Source/fromCompletionStage.md, docs/src/main/paradox/stream/operators/Source/fromFuture.md, docs/src/main/paradox/stream/operators/Source/fromFutureSource.md, docs/src/main/paradox/stream/operators/Source/fromSourceCompletionStage.md, docs/src/main/paradox/stream/operators/Source/lazily.md, docs/src/main/paradox/stream/operators/Source/lazilyAsync.md, docs/src/main/paradox/stream/operators/Source/zipN.md, docs/src/main/paradox/stream/stream-error.md, docs/src/main/paradox/stream/stream-flows-and-basics.md, docs/src/main/paradox/typed/cluster-membership.md, docs/src/main/paradox/typed/dispatchers.md
* see https://github.com/apache/incubator-pekko/issues/142
* one exception is with a reference to a Java Vavr example that was removed after Akka 2.5. I've changed the Pekko docs to refer to the Akka location. The Pekko samples fork does not have that sample.
=> remove refs to akka versions

project/PekkoDisciplinePlugin.scala
As pointed out in https://github.com/apache/incubator-pekko/pull/258#pullrequestreview-1351557344 I got the `Xlint` options wrong in that pull request. This PR fixes that, but in the process of fixing it the Scala compiler for 2.13 specifically found some warnings related to unsealed checking of pattern matches such as 
```
[error] /Users/mdedetrich/github/incubator-pekko/docs/src/test/scala/typed/tutorial_4/DeviceGroup.scala:51:5: match may not be exhaustive.
[error] It would fail on the following input: (x: typed.tutorial_4.DeviceGroup.Command forSome x not in (typed.tutorial_4.DeviceGroup.DeviceTerminated, typed.tutorial_4.DeviceManager.RequestDeviceList, typed.tutorial_4.DeviceManager.RequestTrackDevice))
[error]     msg match {
```
This is the reason behind adding …
=> Fix Xlint options

actor-tests/src/test/scala/org/apache/pekko/pattern/AskSpec.scala, actor-typed-tests/src/test/scala/docs/org/apache/pekko/typed/InteractionPatternsSpec.scala, cluster-metrics/src/test/scala/org/apache/pekko/cluster/metrics/MetricSpec.scala, project/Dependencies.scala, project/PekkoDisciplinePlugin.scala, remote/src/test/scala/org/apache/pekko/remote/AccrualFailureDetectorSpec.scala, serialization-jackson/src/main/scala/org/apache/pekko/serialization/jackson/JacksonObjectMapperProvider.scala, serialization-jackson/src/test/scala/doc/org/apache/pekko/serialization/jackson/v2a/CustomerMigration.scala, stream-tests/src/test/scala/org/apache/pekko/stream/ActorMaterializerSpec.scala
https://github.com/apache/incubator-pekko/issues/7
* Jackson 2.14.2 for Scala 3 - supports only Scala 3.2 - so we'll need to upgrade Scala
* There is a deprecation warning - a Jackson method that we use that has now been deprecated.
* The deprecated method needs a large scale rewrite to do things the preferred Jackson 2.14 way
* Jackson is heading towards making ObjectMapper immutable and the preferred approach is to use `JsonMapper.builder()...` to create a configured MapperBuilder and to create JsonMapper/ObjectMapper instances from it
* In short term, we are probably bestter off not moving off the deprecated method - it won't be removed for ages
```
[error] /home/runner/work/incubator-pekko/incubator-pekko/serialization-jackson/src/main/scala/org/apache/pekko/serialization/jackson/Jacks …
```
=> upgrade to jackson 2.14.2

docs/src/main/paradox/persistence-query.md, docs/src/main/paradox/project/examples.md, docs/src/main/paradox/typed/choosing-cluster.md, docs/src/main/paradox/typed/cqrs.md, docs/src/main/paradox/typed/guide/tutorial_5.md, docs/src/main/paradox/typed/persistence-testing.md, docs/src/main/paradox/typed/persistence.md
* relates to https://github.com/apache/incubator-pekko/issues/244
* can add these doc points back when we actually have a Pekko Platform Guide to look at
=> temporarily remove refs to platform guide

build.sbt
https://incubator.apache.org/policy/incubation.html#releases
Current source dist uses 'incubator' but this is wrong.
=> source dists must include the word incubating

actor-testkit-typed/src/main/scala/org/apache/pekko/actor/testkit/typed/scaladsl/ScalaTestWithActorTestKit.scala, actor-testkit-typed/src/test/scala/docs/org/apache/pekko/actor/testkit/typed/scaladsl/ScalaTestIntegrationExampleSpec.scala, docs/src/main/paradox/typed/testing-async.md
This PR's factors out the common logic of `ScalaTestWithActorTestKit` into a trait `ScalaTestWithActorTestKitBase` while keeping `ScalaTestWithActorTestKit` as is (i.e. an `abstract class`). The context behind this change is that I was looking at flaky tests within https://github.com/apache/incubator-pekko-persistence-r2dbc and I noticed that one of the reasons behind the flakiness is a hardcoded timeout value (see https://github.com/apache/incubator-pekko-persistence-r2dbc/blob/main/.github/workflows/build-test.yml#L75).
While there may be "easier" ways to solve this problem, a much more principled way is to use testcontainers/testcontainers-scala which already has logic (from community effort) that handles these problems so in reality it just works™. 
The easiest way to integrate …
=> Add ScalaTestWithActorTestKitBase trait to handle multiple extends

docs/src/main/paradox/additional/deploying.md, docs/src/main/paradox/cluster-routing.md, docs/src/main/paradox/multi-jvm-testing.md, docs/src/main/paradox/project/examples.md, docs/src/main/paradox/typed/cluster-sharding.md, docs/src/main/paradox/typed/cluster.md, docs/src/main/paradox/typed/distributed-data.md, docs/src/main/paradox/typed/fsm.md, docs/src/main/paradox/typed/persistence.md, project/Paradox.scala
some samples that are referenced in pekko docs are not in https://github.com/apache/incubator-pekko-samples - so I have set those links up to work the old Akka docs way (and link to the Akka sample)
=> update links to point to pekko sample docs

docs/src/main/paradox/common/other-modules.md, docs/src/main/paradox/persistence-plugins.md, docs/src/main/paradox/typed/replicated-eventsourcing.md
https://doc.akka.io/docs/akka-persistence-spanner/current/contributing.html was abandoned before it was ever fully released. There is no Pekko equivalent.
=> remove refs to spanner persistence

project/project-info.conf
We test with Temurin OpenJDK 8, 11 and 17. Adopt OpenJDK is no longer supported and Adoptium have taken over and name their JDKs as Temurin.
Relates to https://github.com/apache/incubator-pekko/issues/247
=> Update project-info JDKs

actor-typed-tests/src/test/scala/docs/org/apache/pekko/typed/IntroSpec.scala, docs/src/main/paradox/_template/projectSpecificFooter.st, docs/src/main/paradox/actors.md, docs/src/main/paradox/assets/js/scalafiddle.js, docs/src/main/paradox/stream/operators/Source/mergePrioritizedN.md, docs/src/main/paradox/stream/stream-quickstart.md, docs/src/main/paradox/typed/actors.md, project/Paradox.scala
Fix issue #246 
- The `Paradox.scala` props have been updated to pekko value.
- The `scalafiddle.js` has been reverted to `org.akka-js`. Akka.js is distributed under [Scala LICENSE](https://www.scala-lang.org/license/)
=> Fixing #246: update signature and fiddle properties in project/Paradox.scala

docs/src/main/paradox/project/examples.md, docs/src/main/paradox/typed/guide/introduction.md, docs/src/main/paradox/typed/guide/tutorial.md, docs/src/main/paradox/typed/guide/tutorial_1.md
will later try to publish the paradox docs for the 2 quickstart projects but the github links act as a start
=> use github links as a 1st step away from lightbend links

actor-tests/src/test/scala/org/apache/pekko/util/Scala212CompatTest.scala, actor/src/main/scala-2.12/org/apache/pekko/util/OptionConverters.scala, actor/src/main/scala-2.13+/org/apache/pekko/util/OptionConverters.scala
When trying to integrate the changes from https://github.com/apache/incubator-pekko/pull/281 into pekko-http I hit a stumbling block where I missed the `.toJavaPrimitive` methods so this PR adds these methods into our `OptionConverters` helper. Since the `.toJavaPrimitive` methods are not being used within Pekko core itself, `Scala212CompatTest` was added to make sure that these helper methods cross compile against all Scala versions so that we don't deal with any regressions.
=> Add toJavaPrimitive to OptionConverters

actor-tests/src/test/scala/org/apache/pekko/util/Scala212CompatTest.scala, actor/src/main/scala-2.12/org/apache/pekko/util/OptionConverters.scala, actor/src/main/scala-2.13+/org/apache/pekko/util/OptionConverters.scala
Another case of finding more converters that have to be added to `OptionConverters` to get pekko-http with https://github.com/apache/incubator-pekko/pull/281 PR
=> Add java Optional primitive to Scala converters

actor-tests/src/test/scala/org/apache/pekko/util/Scala212CompatTest.scala, actor/src/main/scala-2.12/org/apache/pekko/util/OptionConverters.scala, actor/src/main/scala-2.13+/org/apache/pekko/util/OptionConverters.scala
And yet another case of finding more converters that have to be added to `OptionConverters` to get pekko-http with https://github.com/apache/incubator-pekko/pull/281 PR
=> Add OptionConverters.toJava and OptionConverters.toScala

actor-tests/src/test/scala/org/apache/pekko/util/Scala212CompatTest.scala, actor/src/main/scala-2.12/org/apache/pekko/util/OptionConverters.scala, actor/src/main/scala-2.13+/org/apache/pekko/util/OptionConverters.scala
As pointed out in https://github.com/apache/incubator-pekko-http/pull/142#pullrequestreview-1417421049 we should do our best to avoid usage of the `Rich*` implicit classes within Java code especially since Java doesn't do inlining (unlike Scala).
I checked the pekko-http code and within Java sources we only use the `.toScala` methods (the Scala to Java conversion cases are done within Scala source which uses the standard extension methods).
=> Add OptionConverters.toScala methods for java Optional primitives

docs/src/main/paradox/project/index.md, project/Dependencies.scala, project/LicenseReport.scala, project/Paradox.scala, project/plugins.sbt
This PR integrates the latest release of [sbt-license-report](https://github.com/sbt/sbt-license-report) into Pekko docs. This is done by using paradox's source generator support (see https://developer.lightbend.com/docs/paradox/current/customization/generators.html), the integration is quite straight forward due to the fact that sbt-license-report generates markdown format. In summary the whole process is entirely automated, when you run `paradox/docs` the report will be there for you and one can always manually run the various sbt license-report tasks manually (such as `dumpLicenseReportAggregate`). In the current implementation, the report is put into the `Project -> License Report `section of the docs and looks like this
In addition, this PR removes the license comments in …
=> Integrate sbt-license-report

project/AddMetaInfLicenseFiles.scala, project/Publish.scala, project/plugins.sbt
Updates sbt-apache-sonatype. Note that this new version renames `SonatypeApachePlugin` to `ApacheSonatypePlugin` to be consistent with the project name.
=> Update sbt-apache-sonatype and handle rename

actor-typed-tests/src/test/scala/docs/org/apache/pekko/typed/InteractionPatternsSpec.scala, project/Dependencies.scala
Preliminary support for Scala 3.3 (currently based on RC3). Aside from one case (noted below), there hasn't been any non trivial change in sources. Most of the source changes were due to update in Scala 3.3 checking more cases and hence producing more warnings (which isn't that different from latest Scala 2.13 or Scala 2.12).
=> Scala 3.3 support

project/JdkOptions.scala
When no Java 8 installation is found, mention in the error message that you can also use the JAVA_8_HOME environment variable to help the build find it.
=> Document JAVA_8_HOME in error message

build.sbt
* this exclusion of Scala3 cross build causes the scaladoc build to fail for me
* maybe there is a good reason to exclude this - but I don't know what it is
* this PR change means `sbt ++3.3.0 publishSigned` works for me now
* not sure why this does not seem to happen in CI build
@raboof @jrudolph would you have any ideas about this?
I had a quick look at Akka and they don't seem to have the osgi stuff any more - see https://github.com/akka/akka/issues/28304
fyi @mdedetrich
=> issue with osgi project scaladoc (scala3)

actor/src/main/scala-2.12/org/apache/pekko/util/FutureConverters.scala, actor/src/main/scala-2.13+/org/apache/pekko/util/FutureConverters.scala
While the inline isn't that important here, the most critical thing is that the addition of `final` in order to make sure that we don't get any problems down the road. Note that this change is making `FutureConverters` consistent with `OptionConverters`.
=> Add inline final to FutureConverters

build.sbt, project/CopyrightHeader.scala, project/plugins.sbt
The CopyrightHeader.scala change to apply headers to `.sbt` files didn't actually have an effect. I then manually added the headers. I left the CopyrightHeader.scala change there just in case a future version of sbt-header checks the `.sbt` files.
=> add license header to sbt files

project/CopyrightHeaderForBuild.scala
Added the `sbt` files to the plugin configuration.
I checked it locally.
=> =sbt Add headers for sbt files.

stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/JsonFramingSpec.scala, stream/src/main/scala/org/apache/pekko/stream/impl/JsonObjectParser.scala
Was introduced in 6b30134c5c7e8deefdfc7ff9a3e74e0bbd2d433b where an invariant was changed what `pos` can be when the loop is run.
=> stream: fix regression in JsonFraming

CONTRIBUTING.md
a lot of this is now inlined in Pekko instead to simplify the jar dependencies
=> modify out of date note about java8 compat

project/Dependencies.scala
* due to CVEs
* the change is limited to the test scope of actor-tests module
=> upgrade test dependencies used by docker-client

legal/pekko-protobuf-v3-jar-license.txt, project/Dependencies.scala
* https://github.com/apache/incubator-pekko/security/dependabot/59
* bumps from 3.16.1 to 3.16.3 -- so the risks are low (a patch level bump)
=> upgrade to protobuf 3.16.3 (due to CVE)

osgi/src/test/scala/org/apache/pekko/osgi/ActorSystemActivatorTest.scala
Not sure how this was missed but when I locally compile Pekko for Scala 3.3 it fails on this code. We should probably investigate adding Scala 3.3 to normal CI, at least `compile`/`test:compile`.
=> Fix Scala 3.3 compile issues

docs/src/main/paradox/project/migration-guides.md, project/Dependencies.scala
This PR updates ssl config specifically for Scala 2.12/Scala 2.13 (note that the Scala 3 version is unchanged because Pekko was forced to use the latest version of ssl-config for Scala 3 support). The reasoning why this is being done now is the following
* The current version of ssl-config has an actual bug when it comes to PKCS12 (see https://github.com/lightbend/ssl-config/pull/306)
* 0.6.1 is binary compatible with 0.4.3, not that it matters since we only really care about source compatibility (see https://github.com/lightbend/ssl-config/pull/342). Thanks to our friendly resident @raboof 
* While having different versions for libraries due to different Scala versions in `Test` scope is tolerable, I think this is something we should strongly avoid when it comes to actual compile/runtime …
=> Update SSL Config version for Scala 2.12 and 2.13

build.sbt, project/Doc.scala
I don't believe this is an issue anymore. Running `doc` for all projects with Scala 3 works fine now.
=> Enable doc publishing for Scala 3

project/Dependencies.scala, project/Paradox.scala
For starters `scalaTestScalaCheckVersion` as `1-14` isn't meant to run with `scalaCheckVersion` 1.15.1 and `scalaTest` `3.2.x` series does support Scala 2.12
=> Use consistent scalatest/scalatest versions

actor/src/main/scala-2.12/org/apache/pekko/util/ByteIterator.scala, actor/src/main/scala-2.13/org/apache/pekko/util/ByteIterator.scala
Since https://github.com/apache/incubator-pekko/pull/305 is basically ready and just waiting for an upstream fix to Scala 2.13, this PR brings in some changes from that PR in preparation for the RC so that we don't potentially break users when we do add the inline.
The changes are quite trivial, i.e. it involves add `final` to some methods inside of `ByteIterator`. If you don't do this and enable the inliner then the inliner complains with the following
```
[error] /Users/mdedetrich/github/incubator-pekko/actor/src/main/scala-2.12/org/apache/pekko/util/ByteIterator.scala:227:12: org/apache/pekko/util/ByteIterator$MultiByteArrayIterator::clear()V is annotated @inline but could not be inlined:
[error] The method is not final and may be overridden.
[error]       clear()
```
While this will …
=> Add final to methods to prepare for future inline

scripts/link-validator.conf
I have seen this failing already a couple of times which makes it unreliable enough to get added onto ignore list
=> Add occasionally failing link to validator ignore list

actor/src/main/scala/org/apache/pekko/io/dns/IdGenerator.scala
* we can add this back in the future if there is a use case
* it's against the DNS resolver spec to use sequential IDs
=> remove sequence id generator

actor-tests/src/test/scala/org/apache/pekko/io/dns/IdGeneratorSpec.scala, actor/src/main/scala/org/apache/pekko/io/dns/IdGenerator.scala
the ID space is small enough - we need to allow negative IDs to double the ID space
fyi @IainHull
=> support negative short ids in async DNS resolver code

actor/src/main/resources/reference.conf, actor/src/main/scala/org/apache/pekko/io/dns/DnsSettings.scala, actor/src/main/scala/org/apache/pekko/io/dns/IdGenerator.scala, bench-jmh/src/main/scala/org/apache/pekko/io/dns/IdGeneratorBanchmark.scala
DNS id generated should be random, see https://datatracker.ietf.org/doc/html/rfc5452#section-4.3. One additional thing that needs to be confirmed is whether we need to handle collisions
=> Generate random DNS id's

cluster-sharding-typed/src/main/scala/org/apache/pekko/cluster/sharding/typed/delivery/ShardingProducerController.scala
```
2023-06-15T00:53:33.2191358Z [0m[[0m[31merror[0m] [0m[0m[31m[31m-- Error: cluster-sharding-typed/src/main/scala/org/apache/pekko/cluster/sharding/typed/delivery/ShardingProducerController.scala:216:4 [0m[0m[0m
2023-06-15T00:53:33.2192931Z [0m[[0m[31merror[0m] [0m[0m[31m216 |[0m    @[35mDeprecated[0m[0m
2023-06-15T00:53:33.2193740Z [0m[[0m[31merror[0m] [0m[0m[31m[31m    |[0m    ^^^^^^^^^^^[0m[0m
2023-06-15T00:53:33.2195052Z [0m[[0m[31merror[0m] [0m[0m[31m    |[0mwrong number of arguments at <no phase> for (since: String, forRemoval: Boolean): Deprecated: (Deprecated#<init> : (since: String, forRemoval: Boolean): Deprecated), expected: 2, found: 0[0m
2023-06-15T00:53:33.2209503Z [0m[[0m[31merror[0m] [0m[0m[31m[31m-- Error: …
```
=> compile problems due to `@Deprecated` annotations

actor/src/main/scala/org/apache/pekko/io/dns/DnsSettings.scala
see https://lists.apache.org/thread/mo611z4dpro1373r4f5pbgtlyjmhhtz9
The original source is https://github.com/netty/netty/blob/4.1/resolver-dns/src/main/java/io/netty/resolver/dns/DefaultDnsServerAddressStreamProvider.java
we already have https://github.com/apache/incubator-pekko/pull/237/files - this just builds on those changes
=> add netty license header to file with significant netty input

project/plugins.sbt
* brings in an improvement where the files in the zip and tgz archives are grouped with a root directory (while preserving the other paths).
* https://github.com/pjfanning/sbt-source-dist/pull/22
=> upgrade sbt-source-dist plugin

LICENSE, legal/pekko-remote-jar-license.txt
see #418 
https://github.com/real-logic/aeron/ does not have a NOTICE file so we don't have to update our NOTICE files
=> acknowledge use of aeron code

LICENSE, actor/src/main/scala/org/apache/pekko/util/FrequencySketch.scala, legal/pekko-actor-jar-license.txt
Relates to #439 
There is no NOTICE file in https://github.com/ben-manes/caffeine/.
Nor in https://github.com/ben-manes/caffeine/tree/a6be555f0f2a44d33a9d7e52ea923622e373ac7f
=> add license information for Caffeine code used in FrequencySketch

.github/workflows/publish-1.0-docs.yml
* publishes docs for Pekko 1.0
* matches https://doc.akka.io/docs/akka/2.6/typed/index.html
* the version number appears in HTML pages is the full x.y.z version (Akka 2.6.21; Pekko 1.0.0)
* the version number in URL path is just x.y (Akka 2.6; Pekko 1.0)
* we need a GitHub CI job because the rsync needs secrets and I don't know them
* we can run the job off a branch after we complete the 1.0.0 release 
* we don't need to run the job every night after we are happy the docs are stable
=> setup CI job to publish 1.0 docs

.github/workflows/publish-1.0-docs.yml, .github/workflows/publish-nightly.yml
the new publish-1.0-docs CI job deleted the 'main-snapshot' dir on the nightlies site
* note the `--delete` in the rsync command
* this delete is generally useful because we might remove doc files or rename them and we don't want to leave the old copy behind
I think this change will stop the 2 jobs interfering with each other
* the nightly job that publishes main-snapshot docs
* the on demand job that publishes 1.0.0 docs
=> modify rsync jobs for docs to try to stop them deleting each other's work

.github/workflows/publish-1.0-docs.yml
Not the most ideal solution, but it will work for now and we can look into fixing this later. This will publish docs into both `1.0.0` and `1.0` since other Pekko modules usually don't care about linking to patch versions (i.e. pekko-http).
Update to `.htaccess` is here https://github.com/apache/incubator-pekko-site/pull/12
=> Also publish API version of docs

project/PekkoDisciplinePlugin.scala
* relates to https://github.com/apache/incubator-pekko/issues/430
* Java 19 is not LTS and Java 20 is latest non-LTS release
* the compiler warnings leading to build failing (-Werror does this) is the main problem with using a new JDK to build Pekko
=> disable -Werror when using Java 20

.asf.yaml
Enables wiki (needed to add testing notes specific to Pekko core).
=> Enable wiki

remote/src/test/scala/org/apache/pekko/remote/classic/ActorsLeakSpec.scala
After doing some extensive testing (talking about 30+ test runs) it turns out that `ActorsLeakSpec` cannot pass locally unless you set `pekko.test.timefactor = 2` which is what is set in CI (see https://github.com/apache/incubator-pekko/blob/88bf6329f193eedd45091f4f9a515943bd8ecb23/.github/workflows/nightly-builds.yml#L168-L175).
=> Set default timefactor for ActorsLeakSpec so it can pass locally

persistence/src/test/scala/org/apache/pekko/persistence/PersistenceSpec.scala
The `persistence-shared/src/test/scala/org/apache/pekko/persistence/journal/leveldb/SharedLeveldbJournalSpec.scala` test currently fails if its run more then once because state that is stored in a local temp folder is not cleaned up after the test completes.
You can replicate this locally by doing the following
* run `persistence-shared/test` locally once, it should pass
* run `persistence-shared/test` second time, it should fail and continue to fail
If you apply this change then the tests continue to pass.
=> Properly cleanup state after SharedLeveldbJournalSpec exits

README.md, project/PekkoBuild.scala, project/TestQuickUntilPassed.scala
Adds a variant of `testQuick` called `testQuickUntilPassed` which runs `testQuick` in a loop until all tests pass. This is intended to be used by the release process to account for some tests being flaky
=> Add testQuickUntilPassed

actor-tests/src/test/scala/org/apache/pekko/io/dns/IdGeneratorSpec.scala, actor/src/main/scala-2.12/org/apache/pekko/util/FunctionConverters.scala, actor/src/main/scala-2.12/org/apache/pekko/util/FutureConverters.scala, actor/src/main/scala-2.12/org/apache/pekko/util/OptionConverters.scala, actor/src/main/scala-2.13+/org/apache/pekko/util/FunctionConverters.scala, actor/src/main/scala-2.13+/org/apache/pekko/util/FutureConverters.scala, actor/src/main/scala-2.13+/org/apache/pekko/util/OptionConverters.scala, actor/src/main/scala/org/apache/pekko/io/dns/IdGenerator.scala, bench-jmh/src/main/scala/org/apache/pekko/io/dns/IdGeneratorBanchmark.scala, project/AddMetaInfLicenseFiles.scala, project/CopyrightHeader.scala, project/LicenseReport.scala
Currently if you create a new source file (typically the case if you add new functionality into Pekko) it applies this header
```scala
/*
* Licensed to the Apache Software Foundation (ASF) under one or more
* license agreements; and to You under the Apache License, version 2.0:
*
*   https://www.apache.org/licenses/LICENSE-2.0
*
* This file is part of the Apache Pekko project, which was derived from Akka.
*/
```
which is not the header that should be applied (this header should only be on source files originally derived from Akka), instead you should rather be applying the standard Apache Header
```scala
/*
* Licensed to the Apache Software Foundation (ASF) under one or more
* contributor license agreements. See the NOTICE file distributed with
* this work for additional information …
```
=> Apply standard Apache Header for new files

.github/workflows/binary-compatibility-checks.yml, .github/workflows/publish-nightly.yml, actor-typed/src/main/mima-filters/1.0.x.backwards.excludes/jfr.excludes, cluster-sharding/src/main/mima-filters/1.0.x.backwards.excludes/jdk-11-specific-classes.excludes, project/MiMa.scala, remote/src/main/mima-filters/1.0.x.backwards.excludes/jdk11-specific-classes.backwards.excludes, stream/src/main/mima-filters/1.0.x.backwards.excludes/28324-jdk9-specific-classes.backwards.excludes
* Copied some excludes files from Akka 2.6
* It appears that the mima check does not factor in some build logic that adds the Java9+ classes to pekko jars
* so mima check incorrectly thinks the classes built for Java9+ are missing from the locally built modules
=> enable mima check

.github/workflows/publish-1.0-docs.yml
* will need to backport/cherry-pick to `1.0.x` branch
* the advantage of having this checked-in as opposed to having a GitHub CI parameter (that can be entered when running the task) is that changes need peer review
=> Update branch in publish-1.0-docs.yml

.github/workflows/build-test-prValidation.yml, build.sbt, project/JavaFormatter.scala
Currently Pekko formats java code on compile which has the unforunate consequence of formatting the entire codebase even when just running due to us generating Scala source code on compile, i.e.
```
pekko > cluster/MultiJvm/test
[info] Formatting 1 Java source...
[info] Reformatted 0 Java sources
[info] 3 file(s) merged using strategy 'Rename' (Run the task at debug level to see the details)
[info] 2 file(s) merged using strategy 'Discard' (Run the task at debug level to see the details)
[info] Built: /home/mdedetrich/github/incubator-pekko/protobuf-v3/target/scala-2.13/pekko-protobuf-v3-assembly-1.0.0+26-ad512ebf-SNAPSHOT.jar
[info] Jar hash: e4c3375316507c107622553eab40d960cae9e132
[info] Formatting 3 Java sources...
[info] Reformatted 0 Java sources
[info] Formatting 2 Java sources... …
```
=> Remove javafmtOnCompile and check in CI

stream/src/main/scala/org/apache/pekko/stream/impl/Stages.scala, stream/src/main/scala/org/apache/pekko/stream/impl/fusing/LazySingleSource.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Source.scala
refs: https://github.com/apache/incubator-pekko/issues/46
There is already a PR in akka , which using `single(()).map(_ => create())` which is simpler, this code itself is easy to understand too, or should I go with `single(create).map(_())`?
Will have to wait: https://github.com/apache/incubator-pekko/issues/38
=> =str Avoid sub materialization in lazySingle.

.github/workflows/binary-compatibility-checks.yml, project/MiMa.scala, project/plugins.sbt
While MiMa may not have worked on really early versions of Scala 3, its reported to be working fine with Scala 3.3 and I can also confirm this when adding MiMa to pekko-streams-circe (see https://github.com/mdedetrich/pekko-streams-circe/pull/13)
Resolves: https://github.com/apache/incubator-pekko/issues/493
=> Also check Scala 3 artifacts in MiMa

cluster-sharding/src/main/resources/reference.conf, cluster/src/main/resources/reference.conf, docs/src/main/paradox/supervision-classic.md, docs/src/main/paradox/testing.md, remote/src/main/resources/reference.conf, serialization-jackson/src/main/resources/reference.conf, stream/src/main/resources/reference.conf
* also removes some Akka migration docs that are not relevant to Pekko users - our migration guide says that we expect users migrating from Akka to first upgrade to Akka 2.6.20 and to follow through on any necessary Akka migrations.
=> fix up some docs with version numbers that are Akka versions

actor/src/main/scala/org/apache/pekko/actor/FSM.scala, actor/src/main/scala/org/apache/pekko/routing/MurmurHash.scala, testkit/src/main/scala/org/apache/pekko/testkit/CallingThreadDispatcher.scala, testkit/src/main/scala/org/apache/pekko/testkit/TestActorRef.scala, testkit/src/main/scala/org/apache/pekko/testkit/TestFSMRef.scala, testkit/src/main/scala/org/apache/pekko/testkit/TestKit.scala
These versions are confusing now that Pekko has started numbering from 1.0.0.
=> remove `@since` annotations with old Akka version numbers

actor/src/main/scala/org/apache/pekko/actor/FSM.scala, actor/src/main/scala/org/apache/pekko/routing/MurmurHash.scala, testkit/src/main/scala/org/apache/pekko/testkit/CallingThreadDispatcher.scala, testkit/src/main/scala/org/apache/pekko/testkit/TestActorRef.scala, testkit/src/main/scala/org/apache/pekko/testkit/TestFSMRef.scala, testkit/src/main/scala/org/apache/pekko/testkit/TestKit.scala
cherry pick of https://github.com/apache/incubator-pekko/commit/3c0672bac227ed49e7f426ecac5f092fa99dc2f3
=> remove `@since` annotations with old Akka version numbers (#536)

stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/HubSpec.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Hub.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Hub.scala
Refs: https://github.com/akka/akka/issues/28327
=> +str Add `startAfterNrOfConsumers` to BroadcastHub.

CONTRIBUTING.md
* the contrib guide links to a POI source file but that header is formatted differently from what we use - the Spark example matches our style
* the existing DRY link is not great - the text display has char encoding issues and the article is truncated because they want you to create an account - the wiki link is fine
=> better license header example

stream/src/main/scala/org/apache/pekko/stream/impl/fusing/GraphInterpreter.scala, stream/src/main/scala/org/apache/pekko/stream/stage/GraphStage.scala
Was: https://github.com/akka/akka/pull/31262/
refs: https://github.com/akka/akka/issues/29557
Use an ConcurrentMap as set to trace the contention in onFeedbackDispatched
=> =str Make use of ConcurrentHashMap instead of List to reduce contention.

multi-node-testkit/src/main/scala/org/apache/pekko/remote/testconductor/Player.scala, multi-node-testkit/src/main/scala/org/apache/pekko/remote/testconductor/RemoteConnection.scala, project/SbtMultiJvm.scala
refs: https://github.com/apache/incubator-pekko/issues/547
and 
refs: https://github.com/apache/incubator-pekko-http/pull/297
=> =sbt Do retry connection in Player.

multi-node-testkit/src/main/scala/org/apache/pekko/remote/testconductor/Player.scala
Lost it in the last pr https://github.com/apache/incubator-pekko/pull/549.
But as we do a `sync()` when connect, so this will never reached.
=> =test Reschedule the reconnect when exception caught.

stream/src/main/scala/org/apache/pekko/stream/impl/fusing/GraphStages.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Source.scala
Using a more straightforward implementation will reduce the AsyncCallback in FutureSource.
=> =str Implement Source.never as a dedicated GraphStage.

multi-node-testkit/src/main/scala/org/apache/pekko/remote/testconductor/Extension.scala
=> =test Change from `Akka` extension to `Pekko` extension in scaladoc.

stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowFromFutureSpec.scala, stream/src/main/scala/org/apache/pekko/stream/impl/fusing/GraphStages.scala
If the future is already failed, it will fail the flow even if there is no downstream demands now.
refs: https://github.com/akka/akka/pull/31728
Which was reported first in akka/akka gitter
This is a behavior change, eagarly failing align with the FailedSource.
```
/**
* Emits a single value when the given `Future` is successfully completed and then completes the stream.
* The stream fails if the `Future` is completed with a failure.
*/
```
=> !str Eagerly fails flow if the future is already failed.

stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/JsonFramingSpec.scala, stream/src/main/scala/org/apache/pekko/stream/impl/JsonObjectParser.scala
I think we can do a quic returning if the buffer size is zero.
=> =str Skip parsing when buffer size < 1

bench-jmh/src/main/scala/org/apache/pekko/stream/LazyFutureSourceBenchmark.scala
refs: https://github.com/apache/incubator-pekko/issues/525
```
[info] Benchmark                                 Mode  Cnt           Score   Error  Units
[info] LazyFutureSourceBenchmark.newLazyFuture  thrpt       4942162872.638          ops/s
[info] LazyFutureSourceBenchmark.oldLazyFuture  thrpt       3474869890.681          ops/s
```
At airport low battery result.
=> =jmh Add LazyFutureSourceBenchmark for #525.

stream/src/main/scala/org/apache/pekko/stream/impl/FanIn.scala, stream/src/main/scala/org/apache/pekko/stream/impl/fusing/StreamOfStreams.scala
Motivotion:
Resort the extractor order for better performance.
=> =str Resort the OnNext extractor order.

bench-jmh/src/main/scala/org/apache/pekko/stream/ZipWithIndexBenchmark.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala
Motivation:
Make code more simpler.
Result:
Simpler code and no performance regression.
```
Jmh/run -i 3 -wi 3 -f1 -t1 .*ZipWithIndexBenchmark.* 
[info] Benchmark                                    Mode  Cnt           Score            Error  Units
[info] ZipWithIndexBenchmark.benchNewZipWithIndex  thrpt    3  6501714129.146 锟斤拷 4044285303.660  ops/s
[info] ZipWithIndexBenchmark.benchOldZipWithIndex  thrpt    3  6146967182.338 锟斤拷  801852805.114  ops/s
```
=> =str Make use of statefulMap to implement zipWithIndex.

project/build.properties
cherry pick e6ebc66db87c8281541bdc5f42c1c9836e9ab322
backport due to CVE fix in sbt 1.9.4
=> =sbt Bump sbt to 1.9.4 (1.0.x branch)

stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala
Motivation:
The paritial fucntion is not needed, my memory is blurry 
Result:
Clean code.
=> =str Drop the partial function usage in Flow#zipWithIndex.

stream/src/main/scala/org/apache/pekko/stream/javadsl/Flow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SubFlow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SubSource.scala
* see https://github.com/apache/incubator-pekko/actions/runs/6061206002/job/16446137883
* seems to happen when dotty doc phase kicks in
* we have already had to remove the `@Deprecated` annotations but these were added by https://github.com/apache/incubator-pekko/commit/2ce8a894e9f36338e85313518ea25170e59badc8
* I will forward fit this to `main` branch if this PR is accepted
=> Having `@deprecated` and `@Deprecated` annotations on same function breaks scala3 build

.github/workflows/build-test-prValidation.yml
Currently the PR workflow 'Build / Test' job has a single step validatePullRequest that both compiles and then tests the changes. This takes 30 minutes and is very verbose -- it is difficult to see exactly where a failure is originating.
This PR separating compile and test: This will make the source of errors in steps clearer, without adding any extra pipeline time. (Steps in github jobs are dependent on one another, so the build files can be passed onto prValidation without the need for PR validation to compile again)
On the overall issue: I think next steps should be to extract test logs into their own short-lifetime artifact files and reduce the CI logs to only show failing tests. Will follow up with a PR on that if people think that's a good idea.
=> Improve PR Workflow: Separate the validateCompile step from validatePullRequest

stream/src/main/scala/org/apache/pekko/stream/impl/fusing/Ops.scala
Motivation:
The isDefineAt will check twice, avoid use it.
Result:
Better performance
=> =str Make use of applyOrElse in MapError operator.

stream/src/main/scala/org/apache/pekko/stream/scaladsl/Graph.scala
Motivation:
Reduce allocation
Result:
Lesser object allocation.
=> =str Fold InHandler and OutHandler into GraphStageLogic for wiretap.

stream/src/main/scala/org/apache/pekko/stream/impl/fusing/Ops.scala
Motivation:
Reduce allocation
Result:
Lesser object allocation.
=> =str Use OptionVal in Recover instead of Option.

stream/src/main/scala/org/apache/pekko/stream/impl/fusing/Ops.scala
Motivation:
Reduce allocation
Result:
Lesser object allocation.
=> =str Fold InHandler and OutHandler into GraphStageLogic for recoverWith.

.github/workflows/binary-compatibility-checks.yml, .github/workflows/build-test-prValidation.yml, .github/workflows/dependency-graph.yml, .github/workflows/format.yml, .github/workflows/headers.yml, .github/workflows/link-validator.yml, .github/workflows/nightly-builds-aeron.yml, .github/workflows/nightly-builds-latest-jdks.yml, .github/workflows/nightly-builds.yml, .github/workflows/publish-1.0-docs.yml, .github/workflows/publish-1.0-nightly.yml, .github/workflows/publish-nightly.yml, .github/workflows/scala3-build.yml, .github/workflows/scala3-compile.yml, .github/workflows/timing-tests.yml
The latest version of the checkout github actions now supports a `fetch-tags` flag which does as described, i.e. it will fetch all of our tags which removes the various workarounds that was used before (i.e. manually running `git fetch` command) etc etc, see https://github.com/actions/checkout/pull/579
This will also help in the erroneous errors that we get in CI, i.e. 
```
[error] Failed to derive version from git tags. Maybe run `git fetch --unshallow` or `git fetch upstream` on a fresh git clone from a fork? Derived version: 0.0.0+1-337943bd-SNAPSHOT`
```
=> Use fetch tags from latest checkout action

legal/pekko-protobuf-v3-jar-license.txt, project/Dependencies.scala
* try to use a newer jar - we use newer versions of protobuf-java already in grpc and connectors projects
* Using the latest protobuf-java jars have caused issues when testing in other repos - so the aim is to try to do smaller upgrades and see how they work out as we test them across the ecosystem
=> protobuf-java 3.19.6

.github/workflows/nightly-builds-latest-jdks.yml
There is no jdk21 temurin release for now, so I have to switch to zulu or oracle :(
=> =build Use zulu in nightly build to test jdk21.

actor-tests/src/test/scala/org/apache/pekko/dispatch/ForkJoinPoolStarvationSpec.scala
Motivation:
Make the nightly build pass for now.
refs: https://github.com/apache/incubator-pekko/issues/661
=> =test Skip ForkJoinPoolStarvationSpec on JDK21

remote/src/main/scala/org/apache/pekko/remote/transport/netty/NettyTransport.scala
refs: https://github.com/apache/incubator-pekko/issues/645
was: https://github.com/apache/incubator-pekko/pull/650
=> =remote Make use of FlushConsolidationHandler to improve throughput.

persistence/src/main/scala/org/apache/pekko/persistence/Persistence.scala, project/Doc.scala, remote/src/main/java/org/apache/pekko/remote/artery/aeron/AeronErrorLog.java
Refs #353 
I added mappings to an external javadoc to solve warning logs which scaladoc's links to external java library cause.
* `com.typesafe` is linked from `persistence/src/main/scala/org/apache/pekko/persistence/Persistence.scala`
* `io.aeron` is linked from `remote/src/main/java/org/apache/pekko/remote/artery/aeron/AeronErrorLog.java`
* `org.reactivestreams` is linked from `stream/src/main/scala/org/apache/pekko/stream/javadsl/Sink.scala` and `stream/src/main/scala/org/apache/pekko/stream/scaladsl/Sink.scala`
=> Add external javadoc links

actor-typed/src/main/scala/org/apache/pekko/actor/typed/scaladsl/AskPattern.scala, actor-typed/src/main/scala/org/apache/pekko/actor/typed/scaladsl/Routers.scala, stream-typed/src/main/scala/org/apache/pekko/stream/typed/javadsl/ActorFlow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SubSource.scala
As described in the title, resolve some javadoc linking issues that cannot be properly addressed within the IDE.
=> chore: javadoc link and typo fixes

actor-typed-tests/src/test/scala-3/docs/org/apache/pekko/typed/InteractionPatterns3Spec.scala
Linked to #660 
I've been looking at various tests in project `actor-typed-tests` and chose to add a test that is a refactoring of the `InteractionPatternsSpec.scala` test specification as this test applies a message adapter to handle responses from other actors. Other tests to which this could be applied are:
```
actor-typed-tests/src/test/scala/org/apache/pekko/actor/typed/eventstream/EventStreamSpec.scala
actor-typed-tests/src/test/scala/org/apache/pekko/actor/typed/scaladsl/ActorThreadSpec.scala
actor-typed-tests/src/test/scala/org/apache/pekko/actor/typed/scaladsl/MessageAdapterSpec.scala
actor-typed-tests/src/test/scala/org/apache/pekko/actor/typed/delivery/TestProducerWithAsk.scala
actor-typed-tests/src/test/scala/org/apache/pekko/actor/typed/delivery/TestProducerWorkPulling.scala …
```
=> Add a first test applying Scala 3 Union types

.github/workflows/scala3-build.yml, actor-tests/src/test/scala-3/org/apache/pekko/util/LineNumberSpec.scala
see https://github.com/apache/incubator-pekko/issues/663
=> Update LineNumberSpec because it fails after Scala 3.3.1 upgrade

stream/src/main/scala/org/apache/pekko/stream/impl/fusing/Ops.scala
Motivation:
We don't expect much exception throws, and it's `lazy val` in `MapAsync`, so better to keep those two the same.
Result:
Consistent with `MapAsync`.
=> =str Make decider caculation lazy

project/plugins.sbt
* relates to #685 
* upgrading will probably not fix the zip64 issue but it is better for us to be using latest release if any future patches are made
=> sbt-assembly 2.1.3

stream-typed-tests/src/test/scala/org/apache/pekko/stream/MapAsyncPartitionedSpec.scala, stream/src/main/scala/org/apache/pekko/stream/MapAsyncPartitioned.scala, stream/src/main/scala/org/apache/pekko/stream/impl/Stages.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Flow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/FlowWithContext.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SourceWithContext.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SubFlow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SubSource.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/FlowWithContext.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/FlowWithContextOps.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Source.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/SourceWithContext.scala
Motivation: 
1. Tweak the mapAsyncPartitioned  & mapAsyncPartitionedUnordered  document
2. Removed some methods which is used only once.
3. Add these method to SubSource and SubFlow.
refs: https://github.com/apache/incubator-pekko/pull/561
=> =str Tweak the stream mapAsyncPartitioned operator

actor-typed-tests/src/test/scala/org/apache/pekko/actor/typed/SupervisionSpec.scala, actor-typed/src/main/scala/org/apache/pekko/actor/typed/internal/Supervision.scala
References #669
after investigate, the reason why message log is `Supervisor` clear stash immediately(L401) while actor restart, no matter the new actor failure again or not.
It is no issue on classic BackoffOnRestartSupervisor, because they don't have StashBuffer. 
https://github.com/apache/incubator-pekko/blob/e94e7b971b74eeadc05a5b3dc28d1e17c434ad7f/actor-typed/src/main/scala/org/apache/pekko/actor/typed/internal/Supervision.scala#L397-L411
=> fix: keep stashBuffer when exception throw again #669

docs/src/main/paradox/additional/osgi.md, project/Dependencies.scala
Netty 4.1.98.Final was an unsafe version:
- crash the JVM when using JDK21+
- HTTP/2 Rapid Reset Attack 
- https://mail.openjdk.org/pipermail/hotspot-gc-dev/2023-September/043696.html
- https://netty.io/news/2023/09/21/4-1-99-Final.html
- https://nvd.nist.gov/vuln/detail/CVE-2023-44487
- https://netty.io/news/2023/10/10/4-1-100-Final.html
=> Update Netty to 4.1.100.final

actor-typed/src/main/scala/org/apache/pekko/actor/typed/internal/ExtensionsImpl.scala
Avoids https://github.com/lampepfl/dotty/issues/18248
=> Sidestep reproducibility issue

.scala-steward.conf
These cannot be updated until we drop JDK 8
=> Add more ignored dependencies to .scala-steward.conf

.github/workflows/generate-doc-check.yml
(cherry picked from commit b558a28a434750c473d72974a9ffd2ae82e8118e)
=> Fix naming in generate doc check

project/Dependencies.scala
* protobuf-java upgrades are tricky - v3.21.12 has a weird NoSuchMethodError that affects one test
* this version seems to at least work smoothly
=> protobuf-java 3.20.3

multi-node-testkit/src/main/scala/org/apache/pekko/remote/testconductor/Player.scala, project/Dependencies.scala
* scala 3.3.1
* Update Player.scala
---------
Co-authored-by: kerr <hepin1989@gmail.com>
(cherry picked from commit 8d34f8039f2801bc70b16fdddeacd6fd4c225c90)
=> scala 3.3.1 (#632)

project/Dependencies.scala
cherry pick 00c6bac1a70d2e0dc0408a4699d136d599855462
needed for this new method https://github.com/lightbend/config/pull/798
see https://akka.io/security/akka-cve-2023-45865.html
=> Update typesafe:config to 1.4.3

project/Dependencies.scala
This no longer applies (I think its leftover from when Akka used to use dotty nightly/pre-release versions to get around bugs).
=> Remove invalid comment

docs/src/main/paradox/scheduler.md
Just updating a link in the documentation to point to a Pekko variant of a commonly used scheduling library
=> Update link to Pekko variant of akka-quartz-scheduler

docs/src/main/paradox/scheduler.md
cherry pick d0e70eb8649b468eaba1f74eb1a595bd10850a0c
=> Update link to Pekko variant of akka-quartz-scheduler (#782)

.github/workflows/build-test-prValidation.yml, actor-testkit-typed/src/main/scala/org/apache/pekko/actor/testkit/typed/internal/StubbedActorContext.scala, build.sbt, project/Dependencies.scala
Pekko main branch (future pekko 1.1.0 dev line) already uses slf4j-api v2 and we had to react to a breaking change with the slf4j LoggingEvent getMarker method being replaced with a getMarkers method - see #748
Since testkit is only used in testing, I think we can live with a solution that ignores the Marker on LoggingEvent if the getMarker method is missing.
TestAppender change in #748 is not needed because the ILoggingEvent class still has a getMarker method (just deprecated).
https://logback.qos.ch/apidocs/ch/qos/logback/classic/spi/ILoggingEvent.html
=> small change to allow pekko-actor-testkit-typed to work with slf4j-api v2

actor-tests/src/test/scala/org/apache/pekko/actor/ActorSystemSpec.scala, actor-typed-tests/src/test/scala/org/apache/pekko/actor/typed/ActorSystemSpec.scala, actor-typed/src/main/scala/org/apache/pekko/actor/typed/ActorSystem.scala, actor/src/main/scala/org/apache/pekko/actor/ActorSystem.scala, actor/src/main/scala/org/apache/pekko/dispatch/Dispatchers.scala, actor/src/main/scala/org/apache/pekko/util/Helpers.scala
see https://github.com/lightbend/config/pull/798
=> do not render env variables in configs

project/Dependencies.scala
We import bcpkix-jdk18on explicitly instead - bcpkix-jdk15on is outdated.
It also has CVEs and is causing security alerts on our project. https://github.com/apache/incubator-pekko/security/dependabot/53 and https://github.com/apache/incubator-pekko/security/dependabot/92
=> exclude bcpkix-jdk15on

actor-tests/src/test/scala/org/apache/pekko/actor/ActorPathSpec.scala
relates to https://github.com/apache/incubator-pekko/pull/765
These tests prove that Pekko doesn't actively check the URI scheme - at least at the initial URI parsing point.
=> add Akka path parsing tests

stream-tests/src/test/java-jdk9-only/org/apache/pekko/stream/javadsl/FlowUnfoldAsyncTest.java, stream/src/main/scala/org/apache/pekko/stream/impl/Unfold.scala
The `MinimalStage` is also a `CompletableFuture`, but calling `isDone` on it will throw `UnsupportedOperationException`.
This will cause problem when user call `CompletableFuture.completedStage` on Java 9+.
=> =str Fix maybe throw for `MinimalStage`.

docs/src/main/paradox/release-notes/index.md
cherry pick b46750a78fa96eacd12dd7775e3a9fd7c46c9c45 #823
=> add more v1.0.2 release notes (#823)

actor/src/main/scala/org/apache/pekko/io/dns/internal/DnsClient.scala
reported as #834 
In this case, we know the 2 questions match (see previous case in the match). I've added the response code to the log.
It still seems to only need to be a debug log as suggested in #834
=> rework noisy dns log

persistence/src/main/scala/org/apache/pekko/persistence/serialization/SnapshotSerializer.scala, persistence/src/test/scala/org/apache/pekko/persistence/serialization/SnapshotSerializerSpec.scala
* aim is to get this working for 1.0.x and forward fit to main branch
* see https://github.com/scullxbones/pekko-persistence-mongo/pull/14#issuecomment-1847223850
@SakulK would you be able to share a persisted akka snapshot? In base64 format, maybe. It would be useful to have some sort of test.
=> support reading akka-persistence snapshots

persistence/src/main/scala/org/apache/pekko/persistence/serialization/SnapshotSerializer.scala, persistence/src/test/scala/org/apache/pekko/persistence/serialization/SnapshotSerializerSpec.scala
@pjfanning after taking another look I think this should make more sense, otherwise `snapshotFromBinary` can either return `T` or `Try[T]` (got bitten by `AnyRef` here..). I'm not sure why the previous version didn't blow up when testing this with real mongo and existing akka persistence snapshots.
=> Use `recoverWith` instead of `recover` in `SnapshotSerializer` akka backwards compatibility

persistence/src/main/scala/org/apache/pekko/persistence/serialization/SnapshotSerializer.scala, persistence/src/test/scala/org/apache/pekko/persistence/serialization/SnapshotSerializerSpec.scala
cherry pick a934df3cdd3ae7a9940e99e72478f6eba1106476 #841
=> Use recoverWith instead of recover in SnapshotSerializer akka backwards compatibility

actor/src/main/scala/org/apache/pekko/io/dns/internal/DnsClient.scala
cherry pick f6af100531e037b4f245f564d7be8c70f0093a4f #835 #834
=> rework noisy dns log (#835)

docs/src/main/paradox/typed/style-guide.md
* relates to https://github.com/vavr-io/vavr/issues/2756
* we may need to remove vavr from the docs altogether but let's just fix the link for now - to keep the link validator checks happy
=> fix broken vavr link

stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowRecoverWithSpec.scala, stream/src/main/scala/org/apache/pekko/stream/impl/TraversalBuilder.scala, stream/src/main/scala/org/apache/pekko/stream/impl/fusing/Ops.scala
perf: avoid subMaterialization  when source is empty.
=> =str Avoid subMaterialization when the provided recover source is empty.

stream/src/main/scala/org/apache/pekko/stream/impl/fusing/Ops.scala
remove unnecessary condition because the opposite check has already been checked - so `else` is enough
=> =str code clean up in Sliding.

stream-tests/src/test/java/org/apache/pekko/stream/javadsl/SourceTest.java, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala
It was only optimized for scaladsl, now works for javadsl too.
=> =str Optimize concat for javadsl.Source.empty.

stream/src/main/scala/org/apache/pekko/stream/javadsl/Flow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SubFlow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SubSource.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala
Motivation:
User was only knowning this by reading code, including me.
Result:
More clear.
=> chore: Add special `null` value handling doc for mapAsync and mapAsyncUnordered

stream/src/main/scala/org/apache/pekko/stream/impl/fusing/Ops.scala
We modify the order to avoid not setting the flag when `onComplete` throws an exception.
=> Optimize closeState flag

docs/src/main/paradox/project/migration-guide-1.0.x-1.1.x.md, docs/src/main/paradox/project/migration-guides.md, docs/src/main/paradox/stream/operators/Source-or-Flow/splitAfter.md, docs/src/main/paradox/stream/operators/Source-or-Flow/splitWhen.md, stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowSplitAfterSpec.scala, stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowSplitWhenSpec.scala, stream/src/main/scala/org/apache/pekko/stream/SubstreamCancelStrategy.scala, stream/src/main/scala/org/apache/pekko/stream/impl/fusing/StreamOfStreams.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Flow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala
This PR is the equivalent of https://github.com/akka/akka/pull/31415 but for Pekko, I would recommend reading the conversation thread from that PR to get the context/justification for the feature.
The very brief summary is that the `SubstreamCancelStrategy` abstraction that is only used when creating a `SubFlow` (via usage of `splitWhen` and other associated functions) is not needed since Pekko already provides a generic streams abstraction for this called a `SupervisionDecider`. It can even be said that the `SubstreamCancelStrategy` is worse than pointless duplication because unlike `SupervisionDecider` you can't do things like log the thrown exception in the `SubFlow` (this is actually the main impetus for the change, because as user I had the situation where `SubFlow` was throwing …
=> Replace SubstreamCancelStrategy with SupervisionDecider for Split

stream/src/main/scala/org/apache/pekko/stream/impl/fusing/Ops.scala
Motivation:
There is a allocation of `Some` in `SupervisedGraphStageLogic` and for performance reason, I want to remove that.
I can choose the `Option[T]` to `OptionVal[T]`,  but that will cause the problem if the user specified function return `null`.
So I choose to drop the usage of `SupervisedGraphStageLogic`.
Result:
Reduce allocation, but repeated code.
Status: Mima file is not added yet, open for discussion, and I think should remove the `SupervisedGraphStageLogic ` too.
=> perf: Drop the usages of SupervisedGraphStageLogic to reduce allocation.

docs/src/test/java/jdocs/stream/javadsl/cookbook/RecipeAdhocSourceTest.java, docs/src/test/scala/docs/stream/cookbook/RecipeAdhocSource.scala
refs: https://github.com/apache/incubator-pekko/issues/886
=> chore: Fix RecipeAdhocSource test.

actor/src/main/mima-filters/1.1.0.backwards.excludes/java-duration-converters.excludes, actor/src/main/scala-2.13/org/apache/pekko/compat/PartialFunction.scala, actor/src/main/scala-2.13/org/apache/pekko/dispatch/internal/SameThreadExecutionContext.scala, actor/src/main/scala-2/org/apache/pekko/util/JavaDurationConverters.scala, actor/src/main/scala-3/org/apache/pekko/compat/PartialFunction.scala, actor/src/main/scala-3/org/apache/pekko/dispatch/internal/SameThreadExecutionContext.scala, actor/src/main/scala-3/org/apache/pekko/util/FutureConverters.scala, actor/src/main/scala-3/org/apache/pekko/util/JavaDurationConverters.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/package.scala
The previous PR at https://github.com/apache/incubator-pekko/pull/857 managed to miss some inline annotations so this PR fills the rest.
Interestingly I managed to find a Scala 3 bug whereby if you mark a method with `inline` it cannot be called within Java sources because its missing a symbol, I have reported the issue upstream at https://github.com/lampepfl/dotty/issues/19346
=> Fix remaining missing inline statements/annotations

actor-testkit-typed/src/main/scala/org/apache/pekko/actor/testkit/typed/internal/ActorSystemStub.scala, actor-tests/src/test/java/org/apache/pekko/util/JavaConverterScala3InlineTest.java, actor-typed/src/main/scala/org/apache/pekko/actor/typed/internal/adapter/ActorSystemAdapter.scala, actor/src/main/scala-2.13/org/apache/pekko/util/FutureConverters.scala, actor/src/main/scala-3/org/apache/pekko/util/FutureConverters.scala, actor/src/main/scala-3/org/apache/pekko/util/OptionConverters.scala, actor/src/main/scala/org/apache/pekko/actor/ActorSelection.scala, actor/src/main/scala/org/apache/pekko/pattern/CircuitBreaker.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/package.scala
The response in https://github.com/lampepfl/dotty/issues/19346#issuecomment-1872478851 confirms that its by design that methods marked `inline` in Scala 3 are not meant to be called within Java, it is intended for such inlined methods  that its meant to **_enforce/guarantee_** the method is inlined which for obvious reasons is not possible if the method is called within Java considering how `inline` in Scala 3 has become a generic construct (this is different from the `@inline` annotation in Scala 2 which you can freely call within Java, it just won't be inlined).
Due to this, this PR removes the Scala 3 `inline` keyword from methods which are designed to be called within Java as well as adding a test to ensure that these designated Java methods can actually be compiled within a Java …
=> Remove Scala 3 inline keyword from Java specific conversion methods

actor-tests/src/test/scala/org/apache/pekko/util/Scala212CompatTest.scala
(cherry picked from commit 7ed85713e2a9c4b9d0aa607aa9649fb05e88ee6b)
=> Fix header for Scala212CompatTest

stream/src/main/scala/org/apache/pekko/stream/impl/Stages.scala, stream/src/main/scala/org/apache/pekko/stream/impl/fusing/MapConcat.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala
Motivation:
Reduce the usage of `statefulMapConcat`.
Result:
A dedicated operator implementation for `mapConcat` operator.
Note:
Does not implemente the `ContextPropagation`, as I think that was for internal commercial hook?
refs: https://github.com/apache/incubator-pekko-http/issues/395 and chatting on slack.
=> feat: Reimplement MapConcat operator without statefulMapConcat.

build.sbt
Pekko's sbt settings already pick up the necessary scala source dirs.
With this change, sbt still finds all the necessary source dirs.
```
sbt ++2.12 "show actor/unmanagedSourceDirectories"
[info] * /Users/pj.fanning/code/incubator-pekko/actor/src/main/scala
[info] * /Users/pj.fanning/code/incubator-pekko/actor/src/main/scala-2.12
[info] * /Users/pj.fanning/code/incubator-pekko/actor/src/main/scala-2
[info] * /Users/pj.fanning/code/incubator-pekko/actor/src/main/java
sbt ++2.13 "show actor/unmanagedSourceDirectories"
[info] * /Users/pj.fanning/code/incubator-pekko/actor/src/main/scala
[info] * /Users/pj.fanning/code/incubator-pekko/actor/src/main/scala-2.13
[info] * /Users/pj.fanning/code/incubator-pekko/actor/src/main/scala-2
[info] * …
```
=> remove unnecessary sbt setting

.scala-steward.conf, project/Dependencies.scala, serialization-jackson/src/main/resources/reference.conf, serialization-jackson/src/main/scala/org/apache/pekko/serialization/jackson/JacksonObjectMapperProvider.scala, serialization-jackson/src/test/scala/org/apache/pekko/serialization/jackson/JacksonFactorySpec.scala
see https://www.javadoc.io/static/com.fasterxml.jackson.core/jackson-core/2.16.0/com/fasterxml/jackson/core/StreamReadConstraints.html
Users who want this feature now can use these libs instead:
* https://github.com/pjfanning/pekko-serialization-jackson215
* https://github.com/pjfanning/pekko-serialization-jackson216
For Pekko 1.1, I still want to get this merged centrally.
=> jackson 2.16 support

.scala-steward.conf
(cherry picked from commit 688eac7bf5bcd7ca99d4c926b7a16d57598c79e4)
While it can be argued that this is pointless since we aren't going to enable scala-steward on the `1.0.x` branch, I still think its a good idea to do this as a defensive strategy in case in the future we change our minds for w/e reason.
=> Add second sbt-osgi in dependency update ignore list

docs/src/main/paradox/stream/operators/Source-or-Flow/onErrorComplete.md, docs/src/main/paradox/stream/operators/index.md, stream-tests/src/test/java/org/apache/pekko/stream/javadsl/FlowTest.java, stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowOnErrorCompleteSpec.scala, stream/src/main/scala/org/apache/pekko/stream/impl/Stages.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Flow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SubFlow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SubSource.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala
refs: https://github.com/apache/incubator-pekko/issues/624
=> feat:Add onErrorComplete stream operator.

docs/src/main/paradox/stream/operators/Source-or-Flow/onErrorComplete.md, docs/src/main/paradox/stream/operators/index.md
Motivation:
Fix up typos.
Sorry for missed that.
=> chore: Fix typos in onErrorComplete.md

stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowRecoverWithSpec.scala, stream/src/main/scala/org/apache/pekko/stream/impl/fusing/Ops.scala
Motivation:
Event there is a dedicated `recover` which can provide a single value, user can sometime use `recoverWith` a `Source.single` too.
seems like Reactor's special onErrorReturn ,where a single value is recovered , we can avoid the sub materialization too.
Result:
Sub-materialization is avoid for `recoverWith(Source.single(..))`
=> feat: Optimize recoverWith stream operator for single source.

stream/src/main/resources/reference.conf, stream/src/main/scala/org/apache/pekko/stream/impl/ActorMaterializerImpl.scala, stream/src/main/scala/org/apache/pekko/stream/impl/PhasedFusingActorMaterializer.scala
Motivation:
Make stream actor using the SingleConsumerMultiProducer  by default for performance.
refs: https://github.com/apache/incubator-pekko/issues/915
=> feat: Make SingleConsumerMultiProducer the default mailbox for stream.

actor-tests/src/test/scala/org/apache/pekko/io/dns/DockerBindDnsService.scala, project/Dependencies.scala
Replacing deprecated docker-client with docker-java. See: https://github.com/apache/incubator-pekko/issues/806
- `AsyncDnsResolverIntegrationSpec` and `DnsDiscoverySpec` tests are successful.
=> Replacing deprecated docker-client with docker-java

docs/src/main/paradox/stream/operators/index.md, project/StreamOperatorsIndexGenerator.scala, stream-tests/src/test/scala/org/apache/pekko/stream/DslConsistencySpec.scala, stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/ForComprehensionsCompileSpec.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala
Motivation:
refs: https://github.com/apache/incubator-pekko/discussions/654
Note:
1. These methods are only added for scaladsl 
2. `foreach`  method just work as fs2, where the `Stream` needs compile aka pekko's `run`. but different in ZIO, where `foreach` === `runForeach`.
Result:
`for comprehensions` works as fs2 for both `Source` and `Flow` in scaladsl
=> feat: Add support for `for comprehensions`.

docs/src/main/paradox/stream/operators/index.md
Motivation:
Fix the `foreach` missing in index.md
=> chore: Add foreach to index.md

project/StreamOperatorsIndexGenerator.scala, stream-tests-tck/src/test/scala/org/apache/pekko/stream/tck/FlatMapConcatDoubleSubscriberTest.scala, stream-tests/src/test/scala/org/apache/pekko/stream/DslConsistencySpec.scala, stream-tests/src/test/scala/org/apache/pekko/stream/impl/fusing/ActorGraphInterpreterSpec.scala, stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowFlattenMergeSpec.scala, stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowSplitAfterSpec.scala, stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowSplitWhenSpec.scala, stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/SourceSpec.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala
Motivation:
1. Add a `flatten` operator which can simplify the code for common usage.
2. `flatten` is well known for most scala developers
3. both ZIO and FS2 have `flatten` operator.
refs: https://github.com/apache/incubator-pekko/issues/936
Cons:
- lack javadsl support
- one more operator.
Result:
Simpler code.
=> feat: Add flatten operator.

stream/src/main/scala/org/apache/pekko/stream/javadsl/Flow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Sink.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Sink.scala
Motivation:
Add the `@since 1.1.0` to `contramap` operator
=> chore: Add @since 1.1.0 to contramap operator.

.sbt-java-formatter.conf
Motivation:
Ignore these two files, which is very annoying.
Result:
will not be formatted when run `javafmtAll`
=> chore: Ignore two pb files from java formatter.

docs/src/main/paradox/stream/operators/Flow/contramap.md
Motivation:
Which needs url-encoded.
Result:
Correctly rendered
=> chore: Fix scaladoc link in contramap.md

actor-tests/src/test/java/org/apache/pekko/japi/pf/PFBuilderTest.java, actor-typed-tests/src/test/java/org/apache/pekko/actor/typed/javadsl/ActorLoggingTest.java, actor/src/main/java/org/apache/pekko/japi/pf/FSMStateFunctionBuilder.java, actor/src/main/java/org/apache/pekko/japi/pf/PFBuilder.java, docs/src/test/java/jdocs/stream/BidiFlowDocTest.java, docs/src/test/java/jdocs/stream/FlowErrorDocTest.java, docs/src/test/java/jdocs/stream/javadsl/cookbook/RecipeAdhocSourceTest.java, docs/src/test/java/jdocs/stream/operators/SourceOrFlow.java, persistence/src/main/java/org/apache/pekko/persistence/fsm/japi/pf/FSMStateFunctionBuilder.java, stream-tests/src/test/java/org/apache/pekko/stream/javadsl/FlowTest.java, stream-tests/src/test/java/org/apache/pekko/stream/javadsl/SourceTest.java
Motivation:
`new PFBuilder<>()` is not that fluent.
Result:
Add a `create` method on `PFBuilder`, alias with others.
=> feat: Add `create` method to PFBuilder.

actor/src/main/java/org/apache/pekko/japi/JAPI.java
Motivation:
Depcate the `JAPI`.java
refs:
https://github.com/apache/incubator-pekko/issues/951
=> chore: Deprecate JAPI.

actor/src/main/scala/org/apache/pekko/japi/function/Function.scala
There is no class called java.util.function.Creator - I think java.util.function.Supplier is the closest equivalent to the Pekko Creator interface.
=> fix up javadoc on Creator trait

stream-tests/src/test/java/org/apache/pekko/stream/javadsl/FlowTest.java
Motivation:
The test for javadsl's `collect` is missing.
Result:
Added a test for `Source.collect` javadsl.
=> chore: Add collect operator test for stream javadsl.

stream-testkit/src/main/scala/org/apache/pekko/stream/testkit/StreamTestKit.scala, stream-testkit/src/test/scala/org/apache/pekko/stream/testkit/StreamTestKitSpec.scala
Motivation:
Add an `expectN` method to StreamTestKit which supports java List
=> feat: Add expectNextN to StreamTestKit for javadsl.

remote/src/main/resources/reference.conf, remote/src/main/scala/org/apache/pekko/remote/transport/PekkoProtocolTransport.scala
another stray reference to akka
I've made the value configurable, just in case this causes unforeseen issues. Users shouldn't need to change the value.
I have tested with a cluster of 2 Pekko remote actors instances on 2 different remote actor-systems - both configured with different managerNames. The remote actors worked fine together.
The manager name only seems to affect the name of the manager actor instances but not in a way that affects messaging them.
=> fix managerName to use `pekko`

actor-tests/src/test/scala/org/apache/pekko/actor/SchedulerSpec.scala, actor/src/main/scala/org/apache/pekko/actor/LightArrayRevolverScheduler.scala, actor/src/main/scala/org/apache/pekko/actor/Scheduler.scala
create a zero periodic tasks on scheduler will let scheduler busy and can not scheduler other task.
on jdk `ScheduledThreadPoolExecutor`, the zero period task currently is forrbidden.
=> fix: reject zero and negative periodic tasks schedule

actor-tests/src/test/scala/org/apache/pekko/actor/SchedulerSpec.scala, actor/src/main/scala/org/apache/pekko/actor/LightArrayRevolverScheduler.scala, actor/src/main/scala/org/apache/pekko/actor/Scheduler.scala
backport of #887 
cherry-pick from 7b2a3d8c
=> fix: reject zero and negative periodic tasks schedule (#887)

stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowCollectWhileSpec.scala
Motivation:
Fix typo in the collectwhileSpec, where shuld be `collect`.
=> chore: Fix FlowCollectWhileSpec.

stream/src/main/scala/org/apache/pekko/stream/impl/fusing/Ops.scala
Motivation：
I found these code is a little duplicated.
Result:
Simpler code.
=> chore: Clean up some duplicated code.

bench-jmh/src/main/scala/org/apache/pekko/stream/ZipWithIndexBenchmark.scala
Motivation:
This should be pekko prefix.
Result:
correct prefix.
No need to backport to 1.0.x
=> chore: Fix incorrectly prefixed config names

bench-jmh/src/main/scala/org/apache/pekko/stream/CollectBenchmark.scala, stream/src/main/scala/org/apache/pekko/stream/impl/fusing/CollectWhile.scala, stream/src/main/scala/org/apache/pekko/stream/impl/fusing/Ops.scala
Motivation:
As `collect` and `collectWhile` are hot, I think it's worth to do this kind of micro optimization, and these code  unlikely to be changed too.
Same trick can be find https://github.com/scala/scala/blob/2.13.x/src/library/scala/collection/IterableOnce.scala#L1178
Result:
`IF_ACMPEQ` will be a little faster, and reduce an `INVOKEVIRTUAL java/lang/Object.equals`
> Jmh/run -i 10 -wi 10 -f1 -t1 .*CollectBenchmark.*
first run:
```
[info] REMEMBER: The numbers below are just data. To gain reusable insights, you need to follow up on
[info] why the numbers are the way they are. Use profilers (see -prof, -lprof), design factorial
[info] experiments, perform baseline and negative tests that provide experimental control, make sure
[info] the benchmarking environment is safe on JVM/OS/HW …
```
=> chore: Micro optimization for `collect*` operator.

docs/src/main/paradox/stream/operators/Source-or-Flow/collectFirst.md, docs/src/main/paradox/stream/operators/index.md, docs/src/test/java/jdocs/stream/operators/SourceOrFlow.java, docs/src/test/scala/docs/stream/operators/sourceorflow/Collect.scala, stream-tests/src/test/java/org/apache/pekko/stream/javadsl/FlowTest.java, stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowCollectFirstSpec.scala, stream/src/main/scala/org/apache/pekko/stream/impl/Stages.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Flow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SubFlow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SubSource.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala
Motivation:
Add the `collectFirst` operator, which would be nice to have it , otherwise you will need a `collect(...).take(...))`
refs: https://github.com/apache/incubator-pekko/issues/977
The doc is OK.
=> feat: Add `collectFirst` stream operator.

remote/src/main/scala/org/apache/pekko/remote/artery/tcp/ssl/PemManagersProvider.scala
* We don't need the ByteArrayInputStream, we can read from the file directly
=> improve performance in PEM reader

docs/src/main/paradox/stream/operators/Sink/fold.md, docs/src/main/paradox/stream/operators/index.md
Motivation:
In https://github.com/apache/incubator-pekko/pull/1012 @mdedetrich find some typos, and fix the typo in fold.md too.
=> chore: Fix typo in fold.md.

docs/src/main/paradox/stream/operators/Sink/foldWhile.md, docs/src/main/paradox/stream/operators/Source-or-Flow/foldWhile.md, docs/src/main/paradox/stream/operators/index.md, docs/src/test/java/jdocs/stream/operators/flow/FoldWhile.java, docs/src/test/java/jdocs/stream/operators/sink/FoldWhile.java, docs/src/test/scala/docs/stream/operators/sink/FoldWhile.scala, docs/src/test/scala/docs/stream/operators/sourceorflow/Fold.scala, docs/src/test/scala/docs/stream/operators/sourceorflow/FoldWhile.scala, stream-tests/src/test/java/org/apache/pekko/stream/javadsl/FlowTest.java, stream-tests/src/test/java/org/apache/pekko/stream/javadsl/SinkTest.java, stream-tests/src/test/java/org/apache/pekko/stream/javadsl/SourceTest.java, stream-tests/src/test/scala/org/apache/pekko/stream/DslFactoriesConsistencySpec.scala, stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowFoldWhileSpec.scala, stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/SinkFoldSpec.scala, stream/src/main/scala/org/apache/pekko/stream/impl/Stages.scala, stream/src/main/scala/org/apache/pekko/stream/impl/fusing/Ops.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Flow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Sink.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SubFlow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SubSource.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Sink.scala
Motivation:
When chating with @GreyPlane and @laglangyue for implementing the forAll and exists, I find pekko stream needs a foldWhile operator, which can help with that.
refs: https://github.com/apache/incubator-pekko/issues/1010
Result:
Richer operators set.
=> feat: Add Flow/Sink#foldWhile operator.

CONTRIBUTING.md
Mention an easy way to format pekko code, which allows you to skip the sbt loading, in specific cases may be vert useful.
=> chore: mention the faster code fmt approach

bench-jmh/README.md
The original Readme line break seemed like was broken, it was not friendly for newcomers, I have clarified it both with shell and one-line command execution.
=> chore: clarify the JMH Readme

actor/src/main/scala/org/apache/pekko/dispatch/ThreadPoolBuilder.scala
Motivation:
There is an additional `new AtomicReference[Option[T]](None)` usage, by introduce a `PekkoManagedBlocker` , this reduced it.
Result:
Clean code an less memory usage.
=> chore: Add PekkoManagedBlocker to reduce memory.

build.sbt, project/plugins.sbt
Updates sbt-pekko-build to 0.3.1 which brings in the pom.xml `name` field fix
=> Update sbt-pekko-build to 0.3.1

stream/src/main/scala/org/apache/pekko/stream/impl/fusing/CollectFirst.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala
Motivation:
Use dedicated collectFirst implementation
Result:
Better performance.
=> perf: Add dedicated collectFirst implementation.

cluster/src/main/scala/org/apache/pekko/cluster/ConfigUtil.scala, cluster/src/main/scala/org/apache/pekko/cluster/SeedNodeProcess.scala, remote-tests/src/multi-jvm/scala/org/apache/pekko/remote/RemoteFeaturesSpec.scala, remote/src/main/resources/reference.conf, remote/src/main/scala/org/apache/pekko/remote/BoundAddressesExtension.scala, remote/src/main/scala/org/apache/pekko/remote/RemoteActorRefProvider.scala, remote/src/main/scala/org/apache/pekko/remote/RemoteSettings.scala, remote/src/main/scala/org/apache/pekko/remote/artery/ArteryTransport.scala, remote/src/main/scala/org/apache/pekko/remote/transport/PekkoProtocolTransport.scala, remote/src/test/scala/org/apache/pekko/remote/classic/RemoteDeathWatchSpec.scala
Resolves: https://github.com/apache/incubator-pekko/issues/108
Currently in draft
=> Handle mixed akka/pekko protocol names

actor/src/main/scala-2.12/org/apache/pekko/util/ByteIterator.scala, actor/src/main/scala-2.12/org/apache/pekko/util/ByteString.scala, actor/src/main/scala-2.13/org/apache/pekko/util/ByteIterator.scala, actor/src/main/scala-2.13/org/apache/pekko/util/ByteString.scala, actor/src/main/scala-3/org/apache/pekko/util/ByteIterator.scala, actor/src/main/scala-3/org/apache/pekko/util/ByteString.scala, bench-jmh/src/main/scala/org/apache/pekko/util/ArrayCopyOf_Benchmark.scala
Motivation:
As ByteString is only copy `Array[Byte]`, better to just use `System.arraycopy`
background: https://github.com/typelevel/cats-effect/pull/3963
Result:
Better performance.
Have no idea why a `Vector[Byte]` is backed by a `Array[AnyRef]`
=> perf: Make use of System.arraycopy directly.

docs/src/main/paradox/stream/operators/Flow/flattenMerge.md, docs/src/main/paradox/stream/operators/index.md, stream-tests/src/test/scala/org/apache/pekko/stream/DslConsistencySpec.scala, stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowFlattenMergeSpec.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala
Motivation:
Add this Scala dsl for make it more friendly and easy to use in scaldsl.
also we can see this in Kotlin's flow and ZIO.
https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/flatten-merge.html
=> chore: Add Flow#flattenMerge operator.

.github/workflows/generate-doc-check.yml, docs/src/test/java-jdk9-only/jdocs/stream/operators/source/AsSubscriber.java, docs/src/test/scala/docs/stream/operators/sink/AsPublisher.scala
See #958 - should improve the testing of the doc oriented test code
=> chore: Run JDK9Test compiling to validate syntax. 

bench-jmh/src/main/scala/org/apache/pekko/stream/CollectBenchmark.scala, stream/src/main/scala/org/apache/pekko/stream/impl/fusing/CollectFirst.scala, stream/src/main/scala/org/apache/pekko/stream/impl/fusing/CollectWhile.scala, stream/src/main/scala/org/apache/pekko/stream/impl/fusing/Ops.scala
More info: @som-snytt point out in https://scala-lang.org/files/archive/spec/2.13/08-pattern-matching.html#type-patterns see singleton.
Thanks @som-snytt for this.
continue : https://github.com/apache/incubator-pekko/pull/983
=> chore: Make use of pattern matching on singleton type instead.

docs/src/main/paradox/stream/operators/Sink/forall.md, docs/src/main/paradox/stream/operators/index.md, docs/src/test/java/jdocs/stream/operators/sink/ForAll.java, docs/src/test/scala/docs/stream/operators/sink/ForAll.scala, stream-tests/src/test/java/org/apache/pekko/stream/javadsl/SinkTest.java, stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/SinkSpec.scala, stream/src/main/scala/org/apache/pekko/stream/impl/fusing/Ops.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Sink.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Sink.scala
Motivation:
Add `Sink#forall` operator for to test whether all the elements match a predicate.
refs: https://github.com/apache/incubator-pekko/issues/972
Note:
The origin author is @laglangyue and I updated and continued with it, so the review will leave to others.
=> feat: Add Sink#forall operator.

project/plugins.sbt
=> Upgrade sbt-pull-request-validator

actor/src/main/scala-3/org/apache/pekko/compat/PartialFunction.scala, actor/src/main/scala-3/org/apache/pekko/dispatch/internal/SameThreadExecutionContext.scala, actor/src/main/scala-3/org/apache/pekko/util/FutureConverters.scala, actor/src/main/scala-3/org/apache/pekko/util/JavaDurationConverters.scala, actor/src/main/scala-3/org/apache/pekko/util/OptionConverters.scala
We are currently having the issue where the Scala 3 `inline` keyword actually strips any mention of the method inside the generated JVM bytecode which is causing issues . Thankfully Scala 3 also introduced [targetName annotation](https://docs.scala-lang.org/scala3/reference/other-new-features/targetName.html) which lets you set the target designated symbol name in the bytecode of any method, i.e. directly quoting
> A [`@targetName`](https://scala-lang.org/api/3.x/scala/annotation/targetName.html) annotation on a definition defines an alternate name for the implementation of that definition. Example:
```scala
import scala.annotation.targetName
object VecOps:
extension [T](xs: Vec[T])
@targetName("append")
def ++= [T] (ys: Vec[T]): Vec[T] = ...
```
>Here, the `++=` operation is implemented …
=> Add targetName overloaded methods for Scala 3 inline methods

.github/workflows/nightly-builds.yml, build.sbt, project/VerifyJDK9Classes.scala
Motivation:
Use Scala-cli to verify the resulting jar can be used in JDK 9, I think this can be a more complete solution than` unzip ...find.`
refs: https://github.com/apache/incubator-pekko/issues/1040
Result:
Can be tested with scala-cli at nightly job, which was verified with https://github.com/apache/incubator-pekko/actions/runs/7684565710/job/20941211960?pr=1064
ping @Roiocam too
=> Verify JDK 9 classes.

docs/src/test/scala/docs/stream/operators/sink/Fold.scala, docs/src/test/scala/docs/stream/operators/sink/ForAll.scala
Motivation:
Fix up forall comping in paradox.
```scala
[01-29 01:12:37.903] [error] /home/runner/work/incubator-pekko/incubator-pekko/docs/src/test/scala/docs/stream/operators/sink/ForAll.scala:29:7: side-effecting nullary methods are discouraged: suggest defining as `def foldExample()` instead
[01-29 01:12:37.903] [error]   def foldExample: Unit = {
```
=> chore: Fix up ForAll comping in nightly build.

.github/workflows/generate-doc-check.yml, project/Jdk9.scala
Motivation:
1. `+TestJdk9 / compile` for all scala versions, catch potential issues.
2. use `--release 11/17/21` instead, to make JDK 21 code compiles
Result:
1. better validation
2. fix nightly build issue on JDK < 17
=> chore: Compile docs code cross all Scala/Java versions.

build.sbt
This is being done because currently its actually disabling the [knob](https://github.com/pjfanning/sbt-pekko-build/blob/main/src/main/scala/com/github/pjfanning/pekkobuild/PekkoInlinePlugin.scala#L56) that allows you to toggle inlining locally incase you want to diagnose whats going on.
It also defeats the whole purpose of having the inliner configuration in sbt-pekko-build in the first place, i.e. the point of sbt-pekko-build is to centralize common build logic to avoid boilerplate and keep things consistent between Pekko projects.
Note that I am also currently in the process of adding a log statement to sbt-pekko-build which will print whether the inliner is enabled or not to avoid surprises for developers, just waiting on https://discord.com/channels/632150470000902164/9226000509898752 …
=> Remove explicit inliner setting override

.github/workflows/nightly-builds.yml
Motivation:
Add Scala 3.3 to build matrix.
Result:
It now nightly builds 2.12, 2.13, and 3.3.
=> chore: Add Scala 3.3 to nightly build matrix.

docs/src/test/scala/docs/actor/ActorDocSpec.scala
Motivation:
Fix ActorDocSpec
refs: https://github.com/apache/incubator-pekko/issues/1081
=> chore: Fix ActorDocSpec on Scala 3.3

actor-tests/src/test/scala/org/apache/pekko/util/ByteStringInitializationSpec.scala, actor-typed-tests/src/test/scala-3/docs/org/apache/pekko/typed/InteractionPatterns3Spec.scala, actor-typed-tests/src/test/scala/docs/org/apache/pekko/typed/InteractionPatternsSpec.scala, stream-tests/src/test/scala/org/apache/pekko/stream/impl/fusing/AsyncCallbackSpec.scala
Motivation:
Remove more reflectiveCall usage from the codebase.
https://docs.scala-lang.org/scala3/guides/migration/incompat-type-inference.html
Result:
Clean code.
=> chore: Remove more reflectiveCall.

persistence-typed/src/main/scala/org/apache/pekko/persistence/typed/internal/RetentionCriteriaImpl.scala
When the user uses `Integer.MAX_VALUE` as keepNSnapshots, it will touch integer overflow, and persistence will never delete those events.
This change will not change anything besides avoid overflow, because the persistence actor version already designed as a long type.
This screenshot was  happened in the real world:
=> Get avoid snapshot interval calculate int overflow

docs/src/main/paradox/stream/operators/Source-or-Flow/mapWithResource.md, stream-tests/src/test/java/org/apache/pekko/stream/javadsl/FlowTest.java, stream-tests/src/test/java/org/apache/pekko/stream/javadsl/SourceTest.java, stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowMapWithResourceSpec.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Flow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SubFlow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SubSource.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala
- Pekko has `mapwithResource` now, would be better to support `AutoCloseable` in Java/Scala dsl too.
- Add `AutoCloseable` shortcut on `mapWithResource`
- Now `mapWithResource` will close the `AutoCloseable` so user don't need to pass close function
- Closes https://github.com/apache/incubator-pekko/issues/1044
=> feat: Add AutoCloseable shortcut on mapWithResource

docs/src/main/paradox/stream/stream-graphs.md
Partition is a very common and useful operator, Many popular projects have such capabilities(such as Kafka and Flink.）we should mention it in stream graph documentation.
We could complete all fan in/out operators into this documentation, but I think that's increased user burden, the additional partition was enough, because it made us have enough basic functions for fan out(this is kind of like load balance):
- 1 to all
- 1 to random one
- 1 to specific one
=> add partition operator in stream graph docs

.github/workflows/binary-compatibility-checks.yml, .github/workflows/build-test-prValidation.yml, .github/workflows/headers.yml, .github/workflows/link-validator.yml, .github/workflows/nightly-builds-aeron.yml, .github/workflows/nightly-builds.yml, .github/workflows/scala3-build.yml, .github/workflows/scala3-compile.yml, .github/workflows/timing-tests.yml
want to upgrade node version - see https://github.com/coursier/cache-action/releases/tag/v6.4.5
=> don't hardcode exact coursier version so that we can pick up patches

actor-typed/src/main/resources/reference.conf, actor/src/main/resources/reference.conf, cluster-sharding-typed/src/main/resources/reference.conf, cluster-sharding/src/main/resources/reference.conf, cluster-tools/src/main/resources/reference.conf, cluster/src/main/resources/reference.conf, remote/src/main/resources/reference.conf, stream/src/main/resources/reference.conf
Separate PR and cherry-pick from #1096, and solve all module typos.
=> Configuration typo fixes

project/plugins.sbt
cherry pick 4f2f9e3e81c6c75ced2cd6780c5d665a00fb2636 
Last 1.0.x build failed because the old version of this lib could not be found (the old version is in the typesafe rrepo, not maven central - and the typesafe repo is becoming brittle)
=> Update sbt-boilerplate to 0.7.0

.github/workflows/nightly-builds.yml
cherry pick cfff9c53df859bb0f4407caf4821e7831dabeb19
due to #1081 and #1082 - want to see if the issues are new
=> chore: Add Scala 3.3 to build matrix.

cluster/src/main/scala/org/apache/pekko/cluster/SeedNodeProcess.scala, remote/src/main/resources/reference.conf, remote/src/main/scala/org/apache/pekko/remote/RemoteSettings.scala, remote/src/test/scala/org/apache/pekko/remote/classic/RemoteSettingsSpec.scala
This property is only needed if you have pekko.remote.accept-protocol-names set up to include "akka". This is the case in the test config for pekko-remote and we get a lot of logging about pekko.cluster.akka.version as a result.
Relates to #765 and can only be merged to 1.0.x because #765 is only merged to that branch.
spotted in https://github.com/apache/incubator-pekko/actions/runs/7854077720 - we don't run the nightly tests on 1.0.x branch (and we should probably fix that too)
As part of the change, I have renamed the config to pekko.remote.akka.version so that the config is with the other new configs.
=> add default for pekko.remote.akka.version

.github/workflows/nightly-1.0-builds.yml
The build added in #1120 includes items from the main branch nightly build. The `sbt dependWalkerCheck` check is only something that was added on main branch so it causes the 1.0 build to break.
=> remove unsupported feature from 1.0 build

build.sbt, project/Protobuf.scala
Previously, the build would rebuild over and over the uber jar with the
shaded protobuf3 distribution. With this patch, this is no longer the
case, as the output is cached locally.
------
The issue with assembly re-creating the same uber-jar on (nearly) every run was discovered using the Develocity Timeline feature, which displays task executions on different swimlanes.
Before this fix, the assembly task is clearly shown as being a bottleneck in the build process:
After this patch is applied, the bottleneck is gone:
After the bottleneck is gone, common tasks (eg. `test`) start faster: Gathering all tests’ names goes from 3.7s to 3.2s (-15%).
=> Cache output of assembly

.scala-steward.conf
Fixes the ignore update not working due to an extra space which is why https://github.com/apache/incubator-pekko/pull/1061 was created and also pins the updates to `0.9.x` since that supports JDK 1.8
=> Pin sbt-paradox updates to 0.9.x

.scala-steward.conf
So looking at the original commit at https://github.com/apache/incubator-pekko/commit/949ee7ea21934459d6240f60277bf0854eeff158, I don't think whatever the original reason is applicable anymore (unlike Akka, Pekko uses a modern scalafmt which scala-steward should have issues with).
As they say, what happens in Athens stays in Athens
=> Remove unnecessary scalafmt ignore

actor-tests/src/test/scala/org/apache/pekko/pattern/AskSpec.scala, actor/src/main/scala/org/apache/pekko/pattern/AskSupport.scala
=> fix: proper path when promise actor terminated quickly

docs/src/main/paradox/stream/operators/Source-or-Flow/statefulMapConcat.md, stream/src/main/scala/org/apache/pekko/stream/javadsl/Flow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SubFlow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SubSource.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala
Motivation:
As reported in refs:https://github.com/apache/incubator-pekko/issues/1141 , the current `statefulMap` will introduce some overhead from the allocation of tuple `(State, Out)`. So let's just keep it before we come up with an allocation free version like JDK 22's gather api.
Result:
Remove the deprecation of `statefulMapConcat`.
Will need backport to 1.0.x branch.
Ping @JD557
=> chore: Remove the deprecation of statefulMapConcat operator.

docs/src/main/paradox/stream/operators/Source-or-Flow/statefulMapConcat.md, stream/src/main/scala/org/apache/pekko/stream/javadsl/Flow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SubFlow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SubSource.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala
(cherry picked from commit c8a99aa590e0c0a718397c3d707068960167b678)
=> chore: Remove the deprecation of statefulMapConcat operator. (#1147)

project/Dependencies.scala
causing some dependency warnings for us - see https://github.com/apache/incubator-pekko/security/dependabot
https://github.com/docker-java/docker-java/pulls shows that they don't have much interest in dependency upgrades
=> upgrade some docker-client transitive dependencies

actor-tests/src/test/scala/org/apache/pekko/io/dns/internal/TcpDnsClientSpec.scala, actor/src/main/scala/org/apache/pekko/io/dns/internal/TcpDnsClient.scala
=> Add handling for tcp register timeout leaving connection dead

actor-testkit-typed/src/main/scala/org/apache/pekko/actor/testkit/typed/internal/ActorSystemStub.scala, docs/src/main/paradox/project/migration-guide-1.0.x-1.1.x.md, docs/src/main/paradox/release-notes/index.md, stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowFlatMapPrefixSpec.scala, stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowFutureFlowSpec.scala, stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/LazyFlowSpec.scala, stream/src/main/scala/org/apache/pekko/stream/Attributes.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Flow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/FlowWithContext.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SourceWithContext.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/FlowWithContextOps.scala
* minor formatting issue with release notes - properly indent one line (see https://pekko.apache.org/docs/pekko/current/release-notes/index.html#1-0-3-m1 - wiki notes line is not indented when it was meant to be)
* I think the splitWhen header in the migration guides looks untidy (see https://pekko.apache.org/docs/pekko/snapshot/project/migration-guide-1.0.x-1.1.x.html#source-splitwhen-flow-splitwhen-source-splitafter-flow-splitafter-behavioural-change)
* use 'behavior' - US spelling - current docs mix both UK and US spelling and we generally seem to use US spellings (e.g. color as opposed to colour)
=> small doc tidy up

stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala
(cherry picked from commit 7eef4e017ddcbe5c475b82aa4af0ce00940e5368)
=> chore:Fix up typos for unfoldResource* operators. (#1190)

serialization-jackson/src/main/resources/reference.conf, serialization-jackson/src/main/scala/org/apache/pekko/serialization/jackson/JacksonObjectMapperProvider.scala, serialization-jackson/src/test/scala/org/apache/pekko/serialization/jackson/JacksonFactorySpec.scala
* the buffer recycler is an important performance feature in Jackson
* Jackson 2.17 also changes the default pool implementation and this has proved an issue - see https://github.com/FasterXML/jackson-module-scala/issues/672
* my plan for Pekko is to keep the existing ThreadLocal implementation as the default even if Jackson has a different default
=> support config for jackson buffer recycler pool

stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowSplitAfterSpec.scala, stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowSplitWhenSpec.scala, stream/src/main/scala/org/apache/pekko/stream/impl/fusing/StreamOfStreams.scala
Resolves: https://github.com/apache/incubator-pekko/issues/1205
Turns out the error was quite simple, we weren't using a decider to caught the exception in `onPush`
=> Fix uncaught decider exception in Split with Supervision.resumingDecider

stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowGroupBySpec.scala, stream/src/main/scala/org/apache/pekko/stream/impl/fusing/StreamOfStreams.scala
Motivation:
Fix up a groupby operator bug(issue), and let it just behavior the same as the scaladoc.
>If elements arrive for a stream that is in the process of closing these elements might get lost.
Without this ,the stream is completed with an error.
Result:
The elements associated with the closed sub source is just dropped, and the stream continue, and this will help to keep long live stream in production alive.
=> chore: Pull instead of throw exception in groupBy operator.

docs/src/test/java/jdocs/stream/javadsl/cookbook/RecipeAdhocSourceTest.java, docs/src/test/java/jdocs/stream/javadsl/cookbook/RecipeHold.java, docs/src/test/java/jdocs/stream/javadsl/cookbook/RecipeManualTrigger.java, docs/src/test/java/jdocs/stream/javadsl/cookbook/RecipeMissedTicks.java, stream-testkit/src/main/scala/org/apache/pekko/stream/testkit/StreamTestKit.scala, stream-testkit/src/test/scala/org/apache/pekko/stream/testkit/StreamTestKitSpec.scala, stream-tests/src/test/java/org/apache/pekko/stream/javadsl/SourceTest.java
Motivation:
Add more java native api to StreamTestKit.
refs:https://github.com/apache/incubator-pekko/issues/970
was: https://github.com/apache/incubator-pekko/pull/1049
continue the work of @naosense
=> Add missing java api for StreamTestKit

stream/src/main/scala/org/apache/pekko/stream/ActorMaterializer.scala
Motivation:
The default parameter should not be there, I was influenced by the `MaterializationException`
=> chore: Remove default parameter of AbruptStreamTerminationException

cluster/src/main/scala/org/apache/pekko/cluster/ConfigUtil.scala, cluster/src/main/scala/org/apache/pekko/cluster/SeedNodeProcess.scala, remote-tests/src/multi-jvm/scala/org/apache/pekko/remote/RemoteFeaturesSpec.scala, remote/src/main/resources/reference.conf, remote/src/main/scala/org/apache/pekko/remote/BoundAddressesExtension.scala, remote/src/main/scala/org/apache/pekko/remote/RemoteActorRefProvider.scala, remote/src/main/scala/org/apache/pekko/remote/RemoteSettings.scala, remote/src/main/scala/org/apache/pekko/remote/artery/ArteryTransport.scala, remote/src/main/scala/org/apache/pekko/remote/transport/PekkoProtocolTransport.scala, remote/src/test/scala/org/apache/pekko/remote/classic/RemoteDeathWatchSpec.scala, remote/src/test/scala/org/apache/pekko/remote/classic/RemoteSettingsSpec.scala
cherry pick 27b4032b2031feab917b58a66ae645308cacdf87, 4b78adfc424bb8fe05092a1d4fbae5d91339d416 and 55fee7050c534a003fdb68de215fedf88db147fb
#765, #1112 
* We haven't had much feedback on these changes in 1.0.3-M1.
* pekko 1.0 and 1.1 have no major differences that would make it significantly harder for an Akka user to switch to pekko 1.1
* this compat code only kicks in when you set certain configs so doesn't have an impact on most users
* we can always remove this code in a future pekko release
=> forward fit Akka compat changes

stream-testkit/src/main/scala/org/apache/pekko/stream/testkit/StreamTestKit.scala
Motivaition:
Fix https://github.com/apache/pekko/issues/1217
=> chore: Fix expectNextWithTimeoutPF

docs/src/test/scala/docs/actor/ActorDocSpec.scala, docs/src/test/scala/docs/actor/SchedulerDocSpec.scala, docs/src/test/scala/docs/dispatcher/DispatcherDocSpec.scala
Motivation:
Fix https://github.com/apache/pekko/issues/1082
=> chore: Fix scala constructor finding tests for scala 3.

.github/workflows/nightly-builds.yml
Motivation:
The genjavadoc doesn't support Scala 3.3 for now.
Result:
Sucess nightly build on Scala 3.3 && JDK 11
=> chore: Skip genjavadoc on Scala 3.3

stream/src/main/scala/org/apache/pekko/stream/impl/Unfold.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala
Motivation:
Just as the old `unfoldJavaAsync`, This will reduce the allocation/convertion in unfold java operator.
Result:
Less allocation
=> chore: Reduce conversions in javadsl's `unfold` operator.

stream-tests/src/test/java/org/apache/pekko/stream/javadsl/FlowTest.java, stream-tests/src/test/java/org/apache/pekko/stream/javadsl/SourceTest.java
Closes #1229.
```java
@Test
public void mustBeAbleToUseMapWithAutoCloseableResource() {
final TestKit probe = new TestKit(system);
final AtomicInteger closed = new AtomicInteger();
Source.from(Arrays.asList("1", "2", "3"))
.via(
Flow.of(String.class)
.mapWithResource(
() -> (AutoCloseable) closed::incrementAndGet, (resource, elem) -> elem))
.runWith(Sink.foreach(elem -> probe.getRef().tell(elem, ActorRef.noSender())), system);
probe.expectMsgAllOf("1", "2", "3");
// FAILED: AssertionError: expected:<0> but was:<1>
Assert.assertEquals(closed.get(), 1); // 👈👈 clean-up may not be processed yet here!
}
```
I found that `AutoCloseable resource.close();` can be not invoked yet on above code so fix it~!
=> Fix mustBeAbleToUseMapWithAutoCloseableResource broken test

actor/src/main/resources/reference.conf, actor/src/main/scala-jdk-9/org/apache/pekko/dispatch/PekkoJdk9ForkJoinPool.scala, actor/src/main/scala/org/apache/pekko/dispatch/ForkJoinExecutorConfigurator.scala, actor/src/main/scala/org/apache/pekko/dispatch/ForkJoinPoolConstants.scala, build.sbt
* relates to #483 
* needs a lot more work
* open for debate on how best to proceed
=> support jdk9 forkjoinpool maximum-pool-size

stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Source.scala
Motivation:
Fix typo in `Source.fromIterator`
=> chore: Fix typo for Source.fromIterator operator.

actor/src/main/scala/org/apache/pekko/dispatch/ForkJoinExecutorConfigurator.scala
relates to #485 
The method handle seemed to work in my testing but today, I am seeing issues.
This change fixes the issues I have seen.
This was the exception I got and that no longer happens with this PR change.
```
[error] java.lang.invoke.WrongMethodTypeException: expected (int,ForkJoinWorkerThreadFactory,int,UncaughtExceptionHandler,boolean)PekkoJdk9ForkJoinPool but found (int,ForkJoinWorkerThreadFactory,int,UncaughtExceptionHandler,boolean)Object
[error] 	at java.base/java.lang.invoke.Invokers.newWrongMethodTypeException(Invokers.java:476)
[error] 	at java.base/java.lang.invoke.Invokers.checkExactType(Invokers.java:485)
[error] 	at org.apache.pekko.dispatch.ForkJoinExecutorConfigurator$ForkJoinExecutorServiceFactory.createExecutorService(ForkJoinExecutorConfigurator.scala:122) …
```
=> fix issue with forkjoin

stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Source.scala
(cherry picked from commit aba2785428e5ccdd9b1ea27d29efe986650a4a36)
=> chore: Fix typo for Source.fromIterator operator. (#1242)

cluster-sharding-typed/src/test/java/jdocs/org/apache/pekko/cluster/sharding/typed/ExternalShardAllocationCompileOnlyTest.java, cluster-sharding-typed/src/test/scala/docs/org/apache/pekko/cluster/sharding/typed/ExternalShardAllocationCompileOnlySpec.scala, cluster-sharding/src/main/scala/org/apache/pekko/cluster/sharding/external/ExternalShardAllocationStrategy.scala, cluster-sharding/src/multi-jvm/scala/org/apache/pekko/cluster/sharding/ExternalShardAllocationSpec.scala
`ExternalShardAllocationStrategy` doesn't have a Java API, users have to use `pekko.util.TimeUnit ` rather than `java.time.Duration`
And the documentation also has an issue that doesn't specific AllocateStrategy, see: https://pekko.apache.org/docs/pekko/current/typed/cluster-sharding.html#external-shard-allocation
=> feat: Java API for ExternalShardAllocationStrategy

docs/src/main/java-jdk-21/docs/actors/classical/OptimizedActorWithJava21.java, docs/src/main/paradox/stream/operators/Source/iterate.md, docs/src/main/paradox/stream/operators/index.md, docs/src/test/java/jdocs/stream/operators/source/Iterate.java, docs/src/test/scala/docs/stream/operators/source/Iterate.scala, stream-tests/src/test/java/org/apache/pekko/stream/javadsl/SourceTest.java, stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/SourceSpec.scala, stream/src/main/scala/org/apache/pekko/stream/impl/Stages.scala, stream/src/main/scala/org/apache/pekko/stream/impl/fusing/CollectFirst.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Source.scala
Motivation:
refs: https://github.com/apache/pekko/issues/1189
Result:
Source.iterate operator added.
Note:
Because there is an overloading issue in Scala 2, so missing an overloaded method in Scala dsl.
=> chore: Add Source.iterate operator.

stream/src/main/scala/org/apache/pekko/stream/javadsl/Flow.scala
Motivation:
Currently, it's using the `Util.immutableSeq` which will copy the whole value in the Java iterable and convert it to a vector.
Because in the MapConcat/StatefulMapConcat ops, only the underlying `iterator` is being used,  so I think we can use the JIteratorWrapper instead.
Result:
Avoid the copy
=> chore: Avoid copy the whole iterable for mapconcat oprerator in Javadsl.

.scala-steward.conf
Jackson 2.17.0 has some issues.
the current setup tries to focus on jackson-core and ignores updates on other jackson modules - there is one jacksonVersion param and ScalaSteward does not recognise that it creates lots of PRs to update the same value (one for each Jackson module)
=> we are not ignoring enough jackson modules (scala-steward)

.github/workflows/scala-steward.yml
This is no longer needed since we are using `JAVA_OPTS`
=> Remove ignore-opts-files arg in scala steward

project/Dependencies.scala
backport #749 
log4j v1 is a bad look even if we don't actually use it
cherry pick 5fafc22a0558a09944c3545d4903928666175665
=> remove unused log4j dependency

stream/src/main/scala/org/apache/pekko/stream/impl/UnfoldResourceSourceAsync.scala
Motivation:
Refactory UnfoldResourceSourceAsync without change the order of type parameter instead of https://github.com/apache/pekko/pull/616
Result:
Clean code and less allocation.
I think we should this when reading the code in https://github.com/apache/pekko/pull/1240
=> chore: Refactor UnfoldResourceSourceAsync.

docs/src/main/paradox/actors.md, docs/src/main/paradox/typed/style-guide.md
Motivation:
The vavr website is down and they don't plan to continue it for now. refs: https://github.com/vavr-io/vavr/issues/2756
=> chore: Remove vavr link.

actor-tests/src/test/scala/org/apache/pekko/util/ByteStringSpec.scala, actor/src/main/scala-2.12/org/apache/pekko/util/ByteIterator.scala, actor/src/main/scala-2.13/org/apache/pekko/util/ByteIterator.scala, actor/src/main/scala-3/org/apache/pekko/util/ByteIterator.scala
`ByteIterator#indexWhere` was misbehaving when from was larger than the underlying iterator. This method was also called by `ByteIterator#indexOf` and `ByteString#indexWhere`, so those were all wrong.
~~This PR also changes the comparison order in `ByteIterator#indexOf` to match the implementation of stdlib collections. This way objects that override `equals` will work as expected.~~
=> chore: Fix ByteIterator indexWhere method

actor-tests/src/test/scala/org/apache/pekko/pattern/RetrySpec.scala, actor/src/main/scala/org/apache/pekko/pattern/Patterns.scala, actor/src/main/scala/org/apache/pekko/pattern/RetrySupport.scala, docs/src/test/java/jdocs/future/FutureDocTest.java
Motivation:
refs:https://github.com/apache/pekko/issues/1268
Add a retry with predicate overloaded method.
Status:
Still WIP, just changed the underling implementation, no new methods and tests are added.
=> feat: Add retry with predicate

docs/src/main/paradox/typed/logging.md
This PR fixes logback AsyncAppender javadoc link in the documentation.
Fixes https://github.com/apache/pekko/issues/1291
=> Fix javadoc link to include module name

docs/src/main/paradox/typed/logging.md
cherry pick 4c1828438e7933310ab868d66a9dbfef04a2156c #1292
=> Fix javadoc link to include module name (#1292)

.github/workflows/binary-compatibility-checks.yml, .github/workflows/build-test-prValidation.yml, .github/workflows/generate-doc-check.yml, .github/workflows/headers.yml, .github/workflows/link-validator.yml, .github/workflows/nightly-1.0-builds.yml, .github/workflows/nightly-builds-aeron.yml, .github/workflows/nightly-builds.yml, .github/workflows/publish-1.0-docs.yml, .github/workflows/publish-1.0-nightly.yml, .github/workflows/publish-nightly.yml, .github/workflows/scala3-build.yml, .github/workflows/scala3-compile.yml, .github/workflows/timing-tests.yml, project/PekkoDevelocityPlugin.scala, project/plugins.sbt
This PR adds a new auto-plugin that configures publishing of a build scan for every CI build on GitHub Actions. Build scans from local builds can be published by authenticated Apache committer only by explicitly opting in. The build will not fail if publishing fails.
The build scans of the Apache Pekko projects are published to the Develocity instance at [ge.apache.org](https://ge.apache.org/), hosted by the Apache Software Foundation and run in partnership between the ASF and Gradle through a [Platinum Targeted Sponsorship](https://news.apache.org/foundation/entry/the-apache-software-foundation-announces-gradle-as-a-platinum-targeted-sponsor). This Develocity instance has all features and extensions enabled and is freely available for use by the Apache Pekko projects and all other Apache …
=> Capture build scans on ge.apache.org to benefit from deep build insights

.github/workflows/binary-compatibility-checks.yml, .github/workflows/build-test-prValidation.yml, .github/workflows/generate-doc-check.yml, .github/workflows/headers.yml, .github/workflows/link-validator.yml, .github/workflows/nightly-1.0-builds.yml, .github/workflows/nightly-builds-aeron.yml, .github/workflows/nightly-builds.yml, .github/workflows/publish-1.0-docs.yml, .github/workflows/publish-1.0-nightly.yml, .github/workflows/publish-nightly.yml, .github/workflows/scala3-build.yml, .github/workflows/scala3-compile.yml, .github/workflows/timing-tests.yml
Follow up PR for the change that was done in https://github.com/apache/pekko/pull/1288, where the wrong variable name was used. Due to the wrong name the Build Scan was not published. 
Develocity docs about environment variable can be found [here](https://docs.gradle.com/develocity/sbt-plugin/#via_environment_variable)
=> Fix Develocity access key environment variable name

actor/src/main/scala/org/apache/pekko/event/Logging.scala
As described. I think this comment should mention Pekko instead of Akka.
=> Replace Akka reference With Pekko

build.sbt
/code/incubator-pekko/build.sbt:12: warning: value scalafixScalaBinaryVersion in object autoImport is deprecated (since 0.12.1): scalafixScalaBinaryVersion now follows scalaBinaryVersion by default
ThisBuild / scalafixScalaBinaryVersion := scalaBinaryVersion.value
=> remove unnecessary scalafix setting

actor-tests/src/test/scala/org/apache/pekko/util/ManifestInfoSpec.scala
Applying this PR will use more realistic version numbers in the ManifestInfoSpec. Right now they are clearly based on akka versions, which could potentially be confusing.
=> Use more realistic version numbers in ManifestInfoSpec

.github/workflows/nightly-builds.yml
relates to https://github.com/apache/pekko/pull/1324
See failures in JDK11 builds in https://github.com/apache/pekko/actions/runs/9104380012/job/25028122890
The affected sbt calls only happen when Java version is 11 due to conditions in the workflow yml.
=> build issue in nightly-builds.yml

.github/workflows/nightly-builds.yml
I accidentally changed the condition from `!=` to startsWith in https://github.com/apache/pekko/pull/1329
Needs to be 'not startsWith'.
=> fix startsWith condition in nightly-builds.yml

.github/workflows/nightly-builds.yml
Motivation:
Fix nightly publish
https://github.com/apache/pekko/actions/runs/9126537049/job/25095015352
=> chore: Separate commands with `;` in nightly-builds.yml

cluster-sharding-typed/src/main/scala/org/apache/pekko/cluster/sharding/typed/internal/ClusterShardingImpl.scala
Make code cleaner, it is basically the same.
https://github.com/apache/pekko/blob/b5eb6ff01a8d5c5f50b5d1b54280c0dcb075a59a/actor-typed/src/main/scala/org/apache/pekko/actor/typed/scaladsl/adapter/PropsAdapter.scala#L31-L36
https://github.com/apache/pekko/blob/b5eb6ff01a8d5c5f50b5d1b54280c0dcb075a59a/actor-typed/src/main/scala/org/apache/pekko/actor/typed/internal/adapter/ActorSystemAdapter.scala#L125-L133
=> chore: clean code in ClusterSharding

stream/src/main/scala/org/apache/pekko/stream/javadsl/Flow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Sink.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SubFlow.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Sink.scala
Motivation:
Add the missing 1.1.0 annotation
Result:
@since 1.1.0 added for foldWhile.
=> chore: Add since 1.1.0 for `foldWhile` operator

project/Dependencies.scala
see https://github.com/apache/pekko/security/dependabot/102, https://github.com/apache/pekko/security/dependabot/103, https://github.com/apache/pekko/security/dependabot/104
=> add bcpkix test dependency to fix dependabot issues

docs/src/main/paradox/stream/operators/Source-or-Flow/throttle.md
found something typo and missing by reviewing in resolves https://github.com/apache/pekko-persistence-jdbc/pull/199
=> docs: stream operator throttle typo

cluster-sharding/src/main/scala/org/apache/pekko/cluster/sharding/ShardRegion.scala
=> Avoid unnecessary shard updates while shutting down

cluster-sharding/src/main/scala/org/apache/pekko/cluster/sharding/ShardRegion.scala
* Avoid unnecessary shard updates while shutting down
* Avoid re-creating the same message for each shard
cherry pick 92b38e72d6a2701da06f483e8cd27953e403240e
=> Avoid unnecessary shard updates while shutting down (#1342)

actor-typed/src/main/scala/org/apache/pekko/actor/typed/internal/ExtensionsImpl.scala
Towards #325
Hopefully works around https://github.com/scala/scala3/issues/18248
(the diff looks larger than it is, it just moves the two inner functions to regular private functions)
=> fix: improve workaround for Scala3 bug 18248

actor-testkit-typed/src/main/scala/org/apache/pekko/actor/testkit/typed/javadsl/LoggingTestKit.scala, actor-testkit-typed/src/main/scala/org/apache/pekko/actor/testkit/typed/scaladsl/LoggingTestKit.scala, actor-typed-tests/src/test/scala/org/apache/pekko/actor/typed/ActorRefIgnoreSpec.scala, cluster-sharding/src/main/scala/org/apache/pekko/cluster/sharding/external/ExternalShardAllocationStrategy.scala, docs/src/main/paradox/typed/guide/tutorial_1.md, persistence/src/main/scala/org/apache/pekko/persistence/journal/leveldb/LeveldbIdMapping.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Flow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Sink.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SubFlow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SubSource.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Sink.scala
* see #1357 
* also cases where 'a' is used but 'an' is better
=> fix some typos

actor/src/main/scala/org/apache/pekko/actor/Timers.scala, docs/src/test/java/jdocs/testkit/TestKitDocTest.java
Motivation:
refs: https://github.com/apache/pekko/issues/1360
Result:
Easy usage in Java
=> feat: Add UntypedAbstractActorWithTimers

README.md
This badge does come with some obligations, but mostly things we'd want to do anyway.
See also https://cwiki.apache.org/confluence/display/SECURITY/OpenSSF+Best+Practices+Badge
=> chore: add OpenSSF Best Practices badge

project/PekkoDevelocityPlugin.scala
Prevously, the tests that are run in the `TestJdk9` configuration were not captured by Develocity: the results of these tests would not appear in the Develocity test report and dashboard, and failed tests would not be retried.
Because TestJdk9 is a custom configuration, Develocity cannot configure it automatically and we need to manually add the Develocity test settings in that configuration. This is done through an auto plugin that is enabled only on projects where both the Develocity and Jdk9 plugins are enabled.
=> Configure `TestJdk9` for Develocity

.github/workflows/dependency-graph.yml, .github/workflows/scala-steward.yml
Be more selective in granting permissions to actions
=> chore: restrict GitHub actions permissions

.github/workflows/dependency-graph.yml
apparently permissions must be at the job level, not the step level.
Follow-up on #1371
=> fix: dependency-graph permissions

actor-tests/src/test/scala/org/apache/pekko/actor/SchedulerSpec.scala, actor-tests/src/test/scala/org/apache/pekko/config/ConfigSpec.scala, actor/src/main/resources/reference.conf, actor/src/main/scala/org/apache/pekko/actor/LightArrayRevolverScheduler.scala
Motivation:
refs: https://github.com/apache/pekko/issues/1364
Modification:
Add another config `pekko.scheduler.error-on-tick-duration-verification-failed = on` by default and can be changed to `off` when needed.
Result:
Better experience
=> feat: Support adjust the scheduler's tick-duration.

stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/BoundedSourceQueueSpec.scala, stream/src/main/mima-filters/1.0.x.backwards.excludes/pr-1374-boundedsourcequeue-iscompleted-classes.backwards.excludes, stream/src/main/scala/org/apache/pekko/stream/BoundedSourceQueue.scala, stream/src/main/scala/org/apache/pekko/stream/impl/BoundedSourceQueue.scala
Motivation:
refs: https://github.com/apache/pekko/issues/1356
Result:
Better user interface to work with, and can call `complete` without handling the maybe exception.
=> feat: Add `isCompleted` method to BoundedSourceQueue

docs/src/main/paradox/release-notes/index.md
I will merge this when release 1.0.3 is approved.
I will also then forward fit to main branch. The release note pages are changed a little so there will need to be a little customisation of the forward fit.
=> add release notes for v1.0.3

stream/src/main/scala/org/apache/pekko/stream/QueueOfferResult.scala
new API for Java users, used to detect queue completion.
```java
QueueOfferResult offerResult = queue.offer(params);
if (offerResult == QueueOfferResult.enqueued()) {
// logic...
} else if (offerResult == QueueOfferResult.dropped()) {
// logic...
} else if (offerResult instanceof QueueOfferResult.Failure) {
// logic...
} else if (offerResult == QueueOfferResult.closed()) {
// logic...
} else {
// logic...
}
```
https://github.com/apache/pekko/blob/3fabc04acfc472777c85a1bef09bc7f2f777f2e0/stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/BoundedSourceQueueSpec.scala#L98-L106
=> feat: add QueueClosed singleton instance for Java API

docs/src/main/paradox/migration/migration-guide-1.0.x-1.1.x.md
@pjfanning @raboof @He-Pin @Roiocam @jxnu-liguobin Can you have a look into this just to confirm I didn't say anything wrong.
Related to https://github.com/apache/pekko/issues/1205#issuecomment-2216939178
=> Fix migration notes for SubstreamCancelStrategy deprecation

actor-tests/src/test/scala/org/apache/pekko/actor/ActorLifeCycleSpec.scala, actor-tests/src/test/scala/org/apache/pekko/actor/SupervisorSpec.scala, actor/src/main/scala/org/apache/pekko/actor/ActorCell.scala, actor/src/main/scala/org/apache/pekko/actor/dungeon/FaultHandling.scala
Related with #1384 and resolves #1384, some of code contributed by @sadekmunawar 
if PR can reproducer this issue, the ci checks will be unable to successd: https://github.com/apache/pekko/actions/runs/9770536752/job/26971887726?pr=1385
=> fix: resolves and addition tests for child preStart supervise

actor-tests/src/test/scala/org/apache/pekko/actor/ActorLifeCycleSpec.scala, actor-tests/src/test/scala/org/apache/pekko/actor/SupervisorSpec.scala, actor/src/main/scala/org/apache/pekko/actor/ActorCell.scala, actor/src/main/scala/org/apache/pekko/actor/dungeon/FaultHandling.scala
=> fix: resolves and addition tests for child preStart supervise (#1385)

actor/src/main/scala/org/apache/pekko/actor/ActorCell.scala
continue #1385, we allow empty actorRef now.
=> fix: only setFailed when actor not null

actor/src/main/scala/org/apache/pekko/actor/ActorCell.scala
=> fix: only setFailed when actor not null (#1399) 

stream/src/main/scala/org/apache/pekko/stream/javadsl/Flow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Graph.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Sink.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/StreamConverters.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SubFlow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SubSource.scala
So I discovered this when using the javadsl within a kotlin project but it appears that many of the stream functions in javadsl are using their curried equivalents (i.e. `limitWeighted(n: Long)(costFn: function.Function[Out, java.lang.Long])` vs `limitWeighted(n: Long, costFn: function.Function[Out, java.lang.Long])`,
This appears to be a massive oversight, as not only is this currently entirely inconsistent in the codebase (see fold vs foldWhile in Flow javadsl or fold in Source vs fold in Flow javadsl) but Java has no real concept curried functions and so applying curried functions written in Scala is not idiomatic. For Java the standard practice is to just have a single parameter list with the function as the last arg (and Kotlin also expects this).
There is also the case of …
=> Fix uncurried Pekko Stream ops in javadsl

.github/workflows/nightly-builds.yml, actor-testkit-typed/src/main/scala/org/apache/pekko/actor/testkit/typed/internal/TestAppender.scala, cluster-typed/src/test/scala/org/apache/pekko/cluster/typed/ClusterActorLoggingSpec.scala
Resolves: https://github.com/apache/pekko/issues/795, diagnostics:  https://github.com/apache/pekko/issues/795#issuecomment-2244124743
ci checks passed in my repo:
- https://github.com/Roiocam/pekko/actions/runs/10052058874/job/27782660091
- https://github.com/Roiocam/pekko/actions/runs/10052058454/job/27782659033
=> fix: flaky logging mdc tests

actor-tests/src/test/scala-3/org/apache/pekko/util/LineNumberSpec.scala
Causing the nightly tests for 1.0.x to fail wen Scala 3 is used. See https://github.com/apache/pekko/actions/runs/10085818425/job/27887309952
This code is a direct copy of what we have in main branch.
https://github.com/pjfanning/incubator-pekko/blob/39a91c5cebe5f8394216fa7aab6b7b400045b8ed/actor-tests/src/test/scala-3/org/apache/pekko/util/LineNumberSpec.scala
See #683
Partial cherry pick of 15f02d696f0e1d28cdf062cacf8adcd4f83041fe
=> backport LineNumberSpec fix for Scala3

actor-tests/src/test/scala/org/apache/pekko/dispatch/ForkJoinPoolStarvationSpec.scala
cherry pick e94e7b971b74eeadc05a5b3dc28d1e17c434ad7f #662
test is causing the Nightly tests for 1.0.x to fail - see https://github.com/apache/pekko/actions/runs/10085818425/job/27887308944
=> backport ForkJoinPoolStarvationSpec fix from main branch

docs/src/main/paradox/split-brain-resolver.md
Also fixes small grammar issue nearby.
=> Fix typo in split-brain-resolver.md

.github/workflows/build-test-prValidation.yml
=> run extra tests that need Java 9+

docs/src/main/paradox/split-brain-resolver.md
cherry pick 338374c36047815af3a9386609ee38dfca2e1858 #1428
=> Fix typo in split-brain-resolver.md (#1428)

actor-typed-tests/src/test/scala/org/apache/pekko/actor/typed/SupervisionSpec.scala, actor-typed-tests/src/test/scala/org/apache/pekko/actor/typed/coexistence/ClassicSupervisingTypedSpec.scala
continue #1386, separate PR for test migration
=> chore: migrate tests to flatten supervise API

docs/src/main/paradox/release-notes/releases-1.1.md, docs/src/main/paradox/stream/operators/Source-or-Flow/optionalVia.md, docs/src/main/paradox/stream/operators/index.md, docs/src/test/java/jdocs/stream/operators/SourceOrFlow.java, docs/src/test/scala/docs/stream/operators/sourceorflow/OptionalVia.scala, stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowSpec.scala, stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowWithContextSpec.scala, stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/SourceSpec.scala, stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/SourceWithContextSpec.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Flow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/FlowWithContext.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SourceWithContext.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/FlowWithContext.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Source.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/SourceWithContext.scala
This PR adds `optionalVia`/`unsafeOptionalVia` functions which allows you to apply a `viaFlow`  to elements in the stream only if they are defined. This kind of utility function has cropped up due to needing to fulfill a pretty basic/common scenario, i.e. in my case I have a  `Source` of elements and a `Flow` that performs a http request but I only want to apply the http request a subset of those elements.
Tests have been added to the PR but I haven't added documentation, @raboof @jrudolph @He-Pin maybe you can let me know where to put it.
=> Add optionalVia and unsafeOptionalDataVia

docs/src/main/paradox/release-notes/releases-1.1.md, stream-tests/src/test/scala/org/apache/pekko/stream/DslFactoriesConsistencySpec.scala, stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowWithContextSpec.scala, stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/SourceWithContextSpec.scala, stream/src/main/mima-filters/1.0.x.backwards.excludes/pr-1443-also-alsoTo-source-flow-with-context.backwards.excludes, stream/src/main/scala/org/apache/pekko/stream/scaladsl/FlowWithContext.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/FlowWithContextOps.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Sink.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/SourceWithContext.scala
This PR adds `alsoTo`/`alsoToContext` onto `FlowWithContext`/`SourceWithContext` which just wrap the underlying `delegate` methods, this is analogous to the current `map`/`mapContext` methods that already exist.
Note that `delegate.alsoTo(Flow.fromFunction { in: (Out, Ctx) => in._2 }.toMat(that)(Keep.right))` is copied from the implementation of `contramap`. I would have ideally liked to use `contramap` however the method is not available on a `Graph[SinkShape[_]]`
I didn't add tests due to the sheer triviality of the implementation but can add them if asked.
=> Add alsoTo/alsoToContext to FlowWithContext/SourceWithContext

docs/src/main/paradox/release-notes/releases-1.1.md, stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowWithContextSpec.scala, stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/SourceWithContextSpec.scala, stream/src/main/mima-filters/1.0.x.backwards.excludes/pr-1446-wireTap-wireTapContext-source-flow-with-context.backwards.excludes, stream/src/main/scala/org/apache/pekko/stream/scaladsl/FlowWithContext.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/FlowWithContextOps.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/SourceWithContext.scala
Analogous to https://github.com/apache/pekko/pull/1443 but with `wireTap`/`wireTapContext`
=> Add wiretap/wiretapContext to FlowWithContext/SourceWithContext

actor-typed-tests/src/test/scala/org/apache/pekko/actor/typed/BehaviorSpec.scala, actor-typed/src/main/scala/org/apache/pekko/actor/typed/javadsl/Behaviors.scala, actor-typed/src/main/scala/org/apache/pekko/actor/typed/scaladsl/Behaviors.scala
=> feat: streamlined approach for Behaviors #1444

actor-typed-tests/src/test/java/jdocs/org/apache/pekko/typed/DispatchersDocTest.java, actor-typed-tests/src/test/java/jdocs/org/apache/pekko/typed/MailboxDocTest.java, actor-typed-tests/src/test/scala/docs/org/apache/pekko/typed/DispatchersDocSpec.scala, actor-typed-tests/src/test/scala/docs/org/apache/pekko/typed/MailboxDocSpec.scala, actor-typed-tests/src/test/scala/org/apache/pekko/actor/typed/scaladsl/DispatcherSelectorSpec.scala, actor-typed-tests/src/test/scala/org/apache/pekko/actor/typed/scaladsl/MailboxSelectorSpec.scala, actor-typed/src/main/resources/reference.conf, actor-typed/src/main/scala/org/apache/pekko/actor/typed/Props.scala, actor/src/main/resources/reference.conf, docs/src/main/paradox/typed/dispatchers.md, docs/src/main/paradox/typed/mailboxes.md
I have experience in migrating Classic to Typed. In the process, I found that Typed can't customize Mailbox through Props. We should match the same Classic method on Typed.
=> additional mailbox selector for typed props

stream/src/main/scala/org/apache/pekko/stream/javadsl/Flow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/FlowWithContext.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SourceWithContext.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/FlowWithContext.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Source.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/SourceWithContext.scala
Some typos where introduced in https://github.com/apache/pekko/pull/1422
=> Fix typos in optionalVia/unsafeOptionalVia

.github/workflows/publish-1.0-docs.yml
I forgot to do when we released v1.0.3. This is now causing a problem after I merged https://github.com/apache/pekko-site/pull/123 because that redirects 'current' docs to the non-existent 1.0.3 docs.
=> publish 1.0.3 docs

cluster-sharding-typed/src/main/scala/org/apache/pekko/cluster/sharding/typed/internal/ClusterShardingImpl.scala, cluster-sharding/src/main/scala/org/apache/pekko/cluster/sharding/ClusterSharding.scala
Reverts apache/pekko#1304
see #1463
=> Revert "chore: avoid the double evaluation of entityId in ClusterSharding"

docs/src/main/paradox/typed/logging.md
I would like to backport this to branch 1.0.x if it is approved.
The docs list the logger names with their required org.apache prefixing.
=> docs: logger names are Fully Qualified Class Names

project/OSGi.scala
Set the correct version range for `Import-Package` declarations to `org.apache.pekko` packages.
Fixes #1479.
=> Fix OSGi metadata

stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowCollectTypeSpec.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala
`Flow#collectType` was not working as expected for primitives. This PR replaces the use of `ClassTag#runtimeClass#instanceOf` with `ClassTag#unapply`.
While the default implementation of `ClassTag#unapply` simply defers to `ClassTag#runtimeClass#instanceOf`, this is not the case for the `ClassTag`s of primitives, which only override `unapply`.
See the `IntManifest` for an example:
https://github.com/scala/scala/blob/v2.13.14/src/library/scala/reflect/Manifest.scala#L223-L236
=> Support primitives in Flow#collectType

actor/src/main/scala/org/apache/pekko/dispatch/AbstractDispatcher.scala, actor/src/main/scala/org/apache/pekko/dispatch/ThreadPoolBuilder.scala, actor/src/main/scala/org/apache/pekko/util/MessageBuffer.scala
cf https://github.com/apache/pekko/issues/1484 and https://github.com/kamon-io/Kamon/issues/1352
These three sites are enough to fix downstream kamon instrumentation (at least, enough to pass the test suite and negate the need for a recent workaround)
=> Fix downstream kamon instrumentation

actor/src/main/scala/org/apache/pekko/actor/dungeon/Dispatch.scala
relates to #1484 
I have similar issues in https://github.com/pjfanning/micrometer-pekko and this change fixes the broken test I ran into there when upgrading to Pekko 1.1.
I have tested this locally and it fixes the issue in micrometer-pekko.
More changes will be needed for Kamon but I'm raising this to show a path forward and to see if this acceptable for Pekko 1.1.2. We can add more changes in more PRs.
I won't merge this until a few people have reviewed it and there are no objections.
fyi @hughsimpson
=> mark stop() method as noinline

stream/src/main/scala-2.12/org/apache/pekko/stream/javadsl/CollectionUtil.scala, stream/src/main/scala-2.13+/org/apache/pekko/stream/javadsl/CollectionUtil.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Flow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/FlowWithContext.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Sink.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SourceWithContext.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SubFlow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SubSource.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Tcp.scala
=> issue with full list copies in pekko-stream javadsl

actor/src/main/scala/org/apache/pekko/actor/ActorPath.scala, actor/src/main/scala/org/apache/pekko/actor/ActorSystem.scala, cluster-tools/src/main/scala/org/apache/pekko/cluster/client/ClusterClient.scala, cluster/src/main/scala/org/apache/pekko/cluster/ClusterSettings.scala, remote/src/main/scala/org/apache/pekko/remote/RemoteDeployer.scala, remote/src/main/scala/org/apache/pekko/remote/RemoteSettings.scala, remote/src/main/scala/org/apache/pekko/remote/artery/ArterySettings.scala, remote/src/main/scala/org/apache/pekko/remote/artery/tcp/ssl/SSLEngineConfig.scala, remote/src/main/scala/org/apache/pekko/remote/routing/RemoteRouterConfig.scala, remote/src/main/scala/org/apache/pekko/remote/transport/netty/NettySSLSupport.scala
=> replace more uses of Util.immutableSeq

project/PekkoDevelocityPlugin.scala
sbt-develocity v1.1 ships with local and remote build cache support for the `compile` and `test` tasks (see
https://gradle.com/develocity/releases/2024.2#build-caching-for-sbt).
The local build cache is enabled by default, while the remote cache requires configuring the nodes that are allowed to upload artifacts to the build cache (see
https://docs.gradle.com/develocity/sbt-build-cache/#rolling_out_the_cache_in_your_organization).
It's important to confirm that a project's build is ready to use the build cache (local or remote) to avoid unexpected behaviors. Specifically, one should make sure that all relevant inputs to the `compile` or `test` task are captured, as otherwise the generated build cache key will be incorrect (this can lead to erractic behavior, as entries from the cache will …
=> Disable Develocity local build cache

actor/src/main/scala/org/apache/pekko/actor/ActorPath.scala, actor/src/main/scala/org/apache/pekko/actor/ActorSystem.scala, actor/src/main/scala/org/apache/pekko/actor/dungeon/Children.scala, actor/src/main/scala/org/apache/pekko/util/Index.scala, cluster-metrics/src/main/scala/org/apache/pekko/cluster/metrics/ClusterMetricsCollector.scala, cluster-metrics/src/main/scala/org/apache/pekko/cluster/metrics/Metric.scala, cluster-tools/src/main/scala/org/apache/pekko/cluster/client/ClusterClient.scala, cluster/src/main/scala/org/apache/pekko/cluster/Cluster.scala, cluster/src/main/scala/org/apache/pekko/cluster/ClusterEvent.scala, cluster/src/main/scala/org/apache/pekko/cluster/ConfigUtil.scala, cluster/src/main/scala/org/apache/pekko/cluster/Member.scala, remote/src/main/scala/org/apache/pekko/remote/RemotingLifecycleEvent.scala
also tidies up some stray instances where the Pekko converters are imported unnecessarily
=> reduce use of scala.collection.JavaConverters

actor-typed/src/main/scala/org/apache/pekko/actor/typed/internal/LoggerClass.scala
Fixes #1521
It appears on JDK21 the lambda class is called e.g. `class org.apache.pekko.persistence.typed.EventSourcedBehaviorLoggingSpec$ChattyEventSourcingBehavior$$$Lambda/0x00007f1aa03e53b0` instead of e.g. `class org.apache.pekko.persistence.typed.EventSourcedBehaviorLoggingSpec$ChattyEventSourcingBehavior$$$Lambda$523/0x000000080053e040`
=> Fix determining log class by stack on JDK21

project/PekkoBuild.scala
we don't use these
If someone is experimenting locally, they can add these resolvers explicitly instead of using the sys props that this old code supports.
=> remove old resolver support

stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowZipWithIndexSpec.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala
relates to #1525 
I have validated that the test fails without the zipWithIndex change.
=> revert zipWithIndex changes

persistence-testkit/src/main/scala/org/apache/pekko/persistence/testkit/PersistenceTestKitPlugin.scala, persistence-testkit/src/main/scala/org/apache/pekko/persistence/testkit/query/internal/EventsByTagStage.scala, persistence-testkit/src/main/scala/org/apache/pekko/persistence/testkit/query/scaladsl/PersistenceTestKitReadJournal.scala, persistence-testkit/src/test/scala/org/apache/pekko/persistence/testkit/query/EventsByTagSpec.scala
Resolves https://github.com/apache/pekko/issues/1527.
=> Implement EventsByTagQuery in PersistenceTestKitReadJournal

persistence-testkit/src/main/scala/org/apache/pekko/persistence/testkit/PersistenceTestKitPlugin.scala, persistence-testkit/src/main/scala/org/apache/pekko/persistence/testkit/query/internal/EventsBySliceStage.scala, persistence-testkit/src/main/scala/org/apache/pekko/persistence/testkit/query/scaladsl/PersistenceTestKitReadJournal.scala, persistence-testkit/src/test/scala/org/apache/pekko/persistence/testkit/query/EventsBySliceSpec.scala
Related to https://github.com/apache/pekko/issues/1513, reasoning same as https://github.com/apache/pekko/issues/1527 - it would be useful if testkit had this capability.
`TimestampOffset` could be implemented here, because only real persistence layer implementation that uses this that I am aware of - r2dbc - does use `TimestampOffset`, but I am not sure if it is worth the hassle.
=> Implement EventsBySliceQuery in PersistenceTestKitReadJournal 

persistence-testkit/src/main/scala/org/apache/pekko/persistence/testkit/PersistenceTestKitPlugin.scala, persistence-testkit/src/main/scala/org/apache/pekko/persistence/testkit/internal/SnapshotStorageEmulatorExtension.scala, persistence-testkit/src/main/scala/org/apache/pekko/persistence/testkit/scaladsl/PersistenceTestKit.scala, persistence-testkit/src/test/scala/org/apache/pekko/persistence/testkit/scaladsl/RuntimeJournalsSpec.scala, persistence-typed/src/main/mima-filters/1.1.x.backwards.excludes/eventsourcedbehavior.excludes, persistence-typed/src/main/scala/org/apache/pekko/persistence/typed/internal/BehaviorSetup.scala, persistence-typed/src/main/scala/org/apache/pekko/persistence/typed/internal/EventSourcedBehaviorImpl.scala, persistence-typed/src/main/scala/org/apache/pekko/persistence/typed/internal/EventSourcedSettings.scala, persistence-typed/src/main/scala/org/apache/pekko/persistence/typed/internal/ReplayingEvents.scala, persistence-typed/src/main/scala/org/apache/pekko/persistence/typed/internal/ReplayingSnapshot.scala, persistence-typed/src/main/scala/org/apache/pekko/persistence/typed/javadsl/EventSourcedBehavior.scala, persistence-typed/src/main/scala/org/apache/pekko/persistence/typed/scaladsl/EventSourcedBehavior.scala, persistence-typed/src/test/scala/org/apache/pekko/persistence/typed/internal/StashStateSpec.scala
Resolves https://github.com/apache/pekko/issues/1513.
=> Configuring persistence plugins at runtime for EventSourcedBehavior

.github/dependabot.yml
* see https://github.com/apache/pekko/runs/32596468063
* appears to complain that there is no 'schedule'
* compare this to https://github.com/pjfanning/excel-streaming-reader/blob/main/.github/dependabot.yml
* note the different indent
* this is a bit of guesswork because some of the yaml issues can be tricky and it is hard to know if GitHUB CI wokflows are valid until you merge them
=> fix alignment in dependabot.yml

docs/src/main/paradox/cluster-metrics.md
sigar seems dormant: the website is not on 'https', and has become entirely unreachable recently. The repo hasn't seen an update since 9 years.
Perhaps we should consider whether it's responsible to still link to it at all - but for now let's at least link to the GitHub repo instead of the defunct website.
=> fix: link to GitHub for Hyperic Sigar

cluster/src/main/scala/org/apache/pekko/cluster/ClusterDaemon.scala, cluster/src/test/scala/org/apache/pekko/cluster/MixedProtocolClusterSpec.scala
Rolling upgrade from Akka to Pekko requires cluster formation with mixed protocol nodes. If the config `accept-protocol-names` contains both "akka" and "pekko", nodes using either protocol should be able join the same cluster.
Relates to [#765](https://github.com/apache/pekko/pull/765)
=> Allow cluster formation with mixed protocols

osgi/src/test/scala/org/apache/pekko/osgi/PojoSRTestSupport.scala, project/Dependencies.scala
refs: https://github.com/apache/pekko/pull/1574
=> chore: bump tinybundles related things too when upgrade to 4.0.0

cluster/src/main/scala/org/apache/pekko/cluster/ClusterDaemon.scala
relates to https://github.com/apache/pekko/pull/1568#discussion_r1860406983
=> add back brackets in logging (ClusterDaemon)

.scala-steward.conf
* Mockito seems to be a transitive dependency so we probably don't need to pin it.
* see #1582 also
* also allow for patch version updates on agrona
=> Update pins in .scala-steward.conf

stream/src/main/scala/org/apache/pekko/stream/scaladsl/SourceWithContext.scala
refs: https://github.com/apache/pekko/issues/1610
Motivation:
Fix flaky test in unsafeOptionalDataVia
Modification:
1. rewrite with `mergeSequence`
=> bug: fix occasional ordering issue in result in unsafeOptionalDataVia

stream/src/main/scala/org/apache/pekko/stream/impl/PhasedFusingActorMaterializer.scala
Motivation:
Code clean-up with IDEA
Modification:
remove `s` and make fields private.
=> chore: tidy up implementation of PhasedFusingActorMaterializer

docs/src/main/paradox/stream/operators/Sink/none.md, docs/src/main/paradox/stream/operators/index.md, docs/src/test/java/jdocs/stream/operators/sink/NoneMatch.java, docs/src/test/scala/docs/stream/operators/sink/NoneMatch.scala, stream-tests/src/test/java/org/apache/pekko/stream/javadsl/SinkTest.java, stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/SinkSpec.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Sink.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Sink.scala
Motivation:
refs: https://github.com/apache/pekko/issues/1613
refs https://github.com/Kotlin/kotlinx.coroutines/releases/tag/1.10.0 too.
Result:
1. add `Sink#none` operator
2. The doc renders OK
=> feat: Add Sink.none operator

.github/autolabeler.yml, .github/workflows/binary-compatibility-checks.yml, .github/workflows/dependency-graph.yml, .github/workflows/format.yml, .github/workflows/headers.yml, .github/workflows/link-validator.yml, .github/workflows/nightly-1.0-builds.yml, .github/workflows/nightly-builds-aeron.yml, .github/workflows/scala-steward.yml, .github/workflows/scala3-build.yml, .github/workflows/timing-tests.yml
different header based on whether I think file is of Pekko origin or if it is based on Akka files that we inherited at fork time
=> add license headers to CI files

.scala-steward.conf, project/Dependencies.scala, serialization-jackson/src/main/resources/reference.conf, serialization-jackson/src/main/scala/org/apache/pekko/serialization/jackson/JacksonObjectMapperProvider.scala, serialization-jackson/src/test/scala/org/apache/pekko/serialization/jackson/JacksonFactorySpec.scala
* supports https://github.com/FasterXML/jackson-core/pull/1296
* Jackson lock-free buffer recyclers turned out to have major trouble and have been deprecated - https://github.com/trinodb/trino/issues/21356
=> jackson 2.18 with max-token-count support

.jvmopts-ci
Motivation:
It needs to be enabled in `.jvmopts-ci` too.
refs: https://github.com/apache/pekko/issues/1634
otherwise, it's just :
```
io.netty.util.ResourceLeakDetector -- -Dio.netty.leakDetection.level: simple
```
Modification:
Add `-Dio.netty.leakDetection.level=PARANOID` (max level) to `.jvmopts-ci` 
Result:
Can detect leak in CI
=> chore: Enable netty leak detector in CI

actor-tests/src/test/scala/org/apache/pekko/actor/SchedulerSpec.scala, actor/src/main/scala/org/apache/pekko/actor/LightArrayRevolverScheduler.scala, actor/src/main/scala/org/apache/pekko/actor/Scheduler.scala
Motivation:
refs: https://github.com/apache/pekko/issues/1579
Tests is still missing
=> feat: Add SchedulerTask which will be notified once cancelled.

project/SbtMultiJvmPlugin.scala
Motivation:
Add the leak detector to multi-node-testing too.
refs: https://github.com/apache/pekko/issues/1634
Modification:
Add the options to the MultiNode CommandLine Options
Result:
=> chore: Add netty leak detector in multi-node-testing.

.github/workflows/scala-steward.yml
This PR makes scala-steward github action to run on ubuntu-latest and install sbt before running.
see:
https://github.com/actions/runner-images/issues/10636
https://github.com/scala-steward-org/scala-steward-action/pull/644
=> Update scala-steward.yml to latest ubuntu image.

stream/src/main/scala/org/apache/pekko/stream/scaladsl/Hub.scala
Motivation:
refs: https://github.com/apache/pekko/issues/1627
Modification:
Reduce the loop count
Result:
Reduce the loop count
@andreaslochbihler-da cc as he is the origin reporter
=> perf: Reduce loops in when clean queue in BroadcastHub

.github/workflows/nightly-1.1-builds.yml
Motivication:
refs: https://github.com/apache/pekko/issues/1647
Modification:
Change 1.0.x to 1.1.x
Result:
1.1.x code is tested now.
=> fix: Use 1.1.x build in 1.1.x nightly build

stream-tests/src/test/scala/org/apache/pekko/stream/impl/fusing/ActorGraphInterpreterSpec.scala, stream/src/main/scala/org/apache/pekko/stream/impl/fusing/GraphInterpreter.scala
Motivation:
fix https://github.com/apache/pekko/issues/1646
Modification:
Avoid calling `finalizeStage(logic)` many times.
Result:
No NPE on 1.1.x
forward port, there is no NPE on 1.1.x, but the `finalizeStage` can still be called many times.
=> fix: avoid call finalizeStage more times than once.

stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/StreamConvertersSpec.scala
Motivation:
refs: https://github.com/apache/pekko/issues/1653
Modification:
Implemented the splitIterator in test
Result:
Tests run ok.
=> chore: fix failed in StreamConvertersSpec

.github/workflows/build-test-prValidation.yml, .github/workflows/nightly-builds.yml, cluster/src/main/scala/org/apache/pekko/cluster/ClusterDaemon.scala, cluster/src/test/scala/org/apache/pekko/cluster/MixedProtocolClusterSpec.scala, remote/src/main/scala/org/apache/pekko/remote/Remoting.scala
Run I the tests locally they pass but the nightly tests were failing until I removed this change.
see #1590
```
sbt \
-Dpekko.cluster.assert=on \
-Dpekko.log.timestamps=true \
-Dpekko.test.timefactor=2 \
-Dpekko.actor.testkit.typed.timefactor=2 \
-Dpekko.test.tags.exclude=gh-exclude,timing \
-Dpekko.test.multi-in-test=false \
"cluster/testOnly *JoinConfigCompatCheckerRollingUpdateSpec"
```
=> reimplement fix for akka/pekko cluster

.github/workflows/build-test-prValidation.yml, cluster/src/main/scala/org/apache/pekko/cluster/ClusterDaemon.scala, cluster/src/test/scala/org/apache/pekko/cluster/MixedProtocolClusterSpec.scala, remote/src/main/scala/org/apache/pekko/remote/Remoting.scala
cherry pick ef212e9a98614ba13cd65cde3cd8140702f1f35b #1594
=> reimplement fix for akka/pekko cluster (#1594)

remote/src/main/scala/org/apache/pekko/remote/transport/netty/NettyHelpers.scala
Motivation:
Performance, it was extended to the `SimpleChannelInboundHandler` which will check if the type is a `ByteBuf`, now, we just test it explicitly.
Modification:
Make it extends the `ChannelInboundHandlerAdapter` and `release` explicitly , which was released by the `SimpleChannelInboundHandler`
Result:
Simple code and performance a little better.
=> perf: optmize NettyChannelHandlerAdapter with explict extends.

stream/src/main/scala/org/apache/pekko/stream/impl/fusing/FlatMapPrefix.scala
extracted from https://github.com/apache/pekko/pull/1621
Motivation:
In https://github.com/apache/pekko/discussions/1566 , @queimadus points out a leak
Modification:
1. change the builder from a buffer to a vector builder.
2. free that builder to null after the prefix is generated.
Result:
leak fixed.
```scala
import org.apache.pekko.actor.ActorSystem
import org.apache.pekko.stream.scaladsl.{Flow, Sink, Source}
import org.apache.pekko.util.ByteString
import scala.concurrent.Await
object PekkoQuickstart extends App {
private implicit val system: ActorSystem = ActorSystem()
val s = Source
.repeat(())
.map(_ => ByteString('a' * 400000))
.take(1000000)
.flatMapPrefix(50000) { _ => Flow[ByteString] }
val r = Source.empty
.concatAllLazy(List.tabulate(30000)(_ => s): _*)
.runWith(Sink.ignore) …
```
=> fix: Fix leak in FlatMapPrefix operator.

remote/src/main/mima-filters/1.1.x.backwards.excludes/quarantine.backwards.excludes, remote/src/main/resources/reference.conf, remote/src/main/scala/org/apache/pekko/remote/artery/ArterySettings.scala, remote/src/main/scala/org/apache/pekko/remote/artery/ArteryTransport.scala, remote/src/main/scala/org/apache/pekko/remote/artery/Association.scala, remote/src/main/scala/org/apache/pekko/remote/artery/InboundQuarantineCheck.scala, remote/src/test/scala/org/apache/pekko/remote/artery/HarmlessQuarantineSpec.scala, remote/src/test/scala/org/apache/pekko/remote/artery/OutboundIdleShutdownSpec.scala
* relates to #578
* basic tests that now watch for the quarantine event and with an experimental change to try to suppress that quarantine event when harmless=true
* this suppression is non-default and can be enabled with the config `pekko.remote.artery.propagate-harmless-quarantine-events = off`
=> add non-default config that allows InboundQuarantineCheck to ignore 'harmless' quarantine events

stream-tests/src/test/java/org/apache/pekko/stream/javadsl/FlowTest.java, stream-tests/src/test/java/org/apache/pekko/stream/javadsl/SourceTest.java, stream/src/main/mima-filters/1.1.x.backwards.excludes/pr-271-use-java-list-in-flatmapPrefix-javadsl.backwards.excludes, stream/src/main/scala/org/apache/pekko/stream/javadsl/Flow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SubFlow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SubSource.scala
This will make it easier to work with in Java. And the scaladsl was `seq`
=> Make flatMapPrefix javadsl using java.util.List

stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowWithContextSpec.scala, stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/SourceWithContextSpec.scala
Motivation:
Run the testing more times for ordering validation.
Modification:
Run it 64 times
Result:
Test unsafeDataVia more times.
These tests are fast, so no much overhead.
=> chore: Test more rounds for unsafeDataVia keeping order.

stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowWithContextSpec.scala, stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/SourceWithContextSpec.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/FlowWithContext.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/SourceWithContext.scala
Motivation:
Find this when run https://github.com/apache/pekko/pull/1680
Fix: https://github.com/apache/pekko/actions/runs/12616423403/job/35157651854#step:7:20761
Modification:
port the fix in https://github.com/apache/pekko/pull/1611
Result:
ran 1024 times, works.
=> fix: Fix occasional ordering issue in FlowWithContext#unsafeOptionalDataVia

stream/src/main/scala/org/apache/pekko/stream/impl/LazySource.scala, stream/src/main/scala/org/apache/pekko/stream/impl/fusing/ActorGraphInterpreter.scala, stream/src/main/scala/org/apache/pekko/stream/impl/fusing/StreamOfStreams.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/DelayStrategy.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Graph.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/DelayStrategy.scala
Motivation:
More lambda
Modification:
use lambda
Result:
Clean code
=> chore: Use more lambda instread in stream module.

stream/src/main/scala/org/apache/pekko/stream/impl/ActorRefBackpressureSinkStage.scala, stream/src/main/scala/org/apache/pekko/stream/impl/PhasedFusingActorMaterializer.scala, stream/src/main/scala/org/apache/pekko/stream/impl/fusing/ActorGraphInterpreter.scala
Motivation:
Call methods directly on ArrayDequeue to avoid forwarding.
Modification:
Call methods directly on ArrayDequeue to avoid forwarding.
Result:
performant better
=> chore: Avoid forwarding method on ArrayDequeue in stream module.

actor/src/main/scala/org/apache/pekko/dispatch/BatchingExecutor.scala
Motivation:
Call methods directly on ArrayDequeue to avoid forwarding.
Modification:
Call methods directly on ArrayDequeue to avoid forwarding.
Result:
performant better
=> chore: Avoid forwarding method on ArrayDequeue in BatchingExecutor.

.github/workflows/dependency-graph.yml, project/Dependencies.scala
Currently, dependency-submission would submit all dependencies to https://github.com/apache/pekko/security/dependabot , including test dependencies. We then added explicit dependencies to the build to squash warnings about outdated test dependencies (#1181, #1313 and #1344).
With version 3, sbt-dependency-submission now supports ignoring scopes. This PR proposes to ignore the test scope, and remove the explicit dependencies from the build.
Of course, we want our developers to be secure as much as our users. From that perspective you could say we'd want to remove 'insecure' dependencies even from the test scope. In practice, however, I think it's really unlikely that a vulnerability in a test scope dependency would lead to a realistic attack on a developer. For that reason, I think …
=> chore: dependency-submission: skip test scope

.github/workflows/dependency-graph.yml
To remove false positives from the counter for
https://github.com/apache/pekko/security
follow-up on https://github.com/apache/pekko/pull/1392
=> chore: dependency-graph: ignore more contexts and modules

actor-tests/src/test/java/org/apache/pekko/util/ConstantFunJavaTest.java, actor/src/main/scala/org/apache/pekko/japi/function/Function.scala, stream-tests/src/test/java/org/apache/pekko/stream/javadsl/FlowTest.java, stream-tests/src/test/java/org/apache/pekko/stream/javadsl/SourceTest.java
Motivation:
Make life easier for Java developers without the `i -> i`
Modification:
Add an `identity` helper function.
Result:
Clean code.
=> chore: Add identity function.

.github/workflows/dependency-graph.yml
confirmed ignoring `runtime-internal` suppresses the really old guava, the `scala-doc-tool` and `scala-tool` configs currently don't pull in any problematic dependencies but they should not be relevant to our users either.
Follow-up on https://github.com/apache/pekko/pull/1689 and https://github.com/apache/pekko/pull/1392
=> chore: ignore even more configs for dependency submission

stream-tests/src/test/java/org/apache/pekko/stream/javadsl/FlowTest.java, stream-tests/src/test/java/org/apache/pekko/stream/javadsl/SourceTest.java, stream/src/main/mima-filters/1.1.x.backwards.excludes/pr-1669-avoid-boxing-in-zipWithIndex.backwards.excludes, stream/src/main/scala/org/apache/pekko/stream/impl/fusing/ZipWithIndex.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Flow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SubFlow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SubSource.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala
Motivation:
1. Performance, but it was reverted in https://github.com/apache/pekko/issues/1525
instead of https://github.com/apache/pekko/pull/1657
2. signature on SubSource#zipWithIndex returns a `Pair <T, Object>` instead of `Pair<T, java.lang.Long>`, which is a bug
Modification:
Reimplemented it in a dedicated graph stage.
Result:
Better performance and fix `SubSource#zipWithIndex`
=> fix: avoid boxing in zipWithIndex and fix type signature in SubSource#zipWithIndex

docs/src/main/paradox/release-notes/releases-1.1.md
=> release notes for 1.1.3

actor-typed-tests/src/test/scala/org/apache/pekko/actor/typed/ActorContextSpec.scala, bench-jmh/src/main/scala/org/apache/pekko/actor/RequestResponseActors.scala, cluster-tools/src/main/scala/org/apache/pekko/cluster/pubsub/DistributedPubSubMediator.scala, persistence/src/main/scala/org/apache/pekko/persistence/serialization/MessageSerializer.scala, persistence/src/test/scala/org/apache/pekko/persistence/serialization/SnapshotSerializerSpec.scala, project/Dependencies.scala, project/PekkoDisciplinePlugin.scala, scripts/link-validator.conf
* Update scala-library to 2.13.15
* Update link-validator.conf
* fix `-Wconf` to match new semantics
Override order reversed, see also https://github.com/scala/scala/releases
backport https://github.com/apache/pekko/pull/1505
This will make future maintain easier.
---------
Co-authored-by: Arnout Engelen <arnout@bzzt.net>
Co-authored-by: PJ Fanning <pjfanning@users.noreply.github.com>
(cherry picked from commit dad6b9f6e3289334d709053849595d5f0e1f686e)
=> Update scala-library to 2.13.15 (#1505)

stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowWithContextSpec.scala, stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/SourceWithContextSpec.scala
(cherry picked from commit 2ee37454cb4a9058f4ad57b818f5d8cb783ba820)
=> chore: Test more rounds for unsafeDataVia keeping order. (#1680)

stream/src/main/scala/org/apache/pekko/stream/impl/fusing/StreamOfStreams.scala
Motivation:
Check `breadth` >= 1 in FlattenMerge
Modification:
Add a requirement for that.
=> chore: Require breadth >= 1 in FlattenMerge

stream/src/main/scala/org/apache/pekko/stream/impl/fusing/Ops.scala
Motivation:
require parallelism >= 1 in MapAsync and MapAsyncUnordered
Modification:
Add requirements
=> chore: Require parallelism >= 1 in MapAsync and MapAsyncUnordered

.github/workflows/binary-compatibility-checks.yml, .github/workflows/build-test-prValidation.yml, .github/workflows/generate-doc-check.yml, .github/workflows/headers.yml, .github/workflows/link-validator.yml, .github/workflows/nightly-1.0-builds.yml, .github/workflows/nightly-1.1-builds.yml, .github/workflows/nightly-builds-aeron.yml, .github/workflows/nightly-builds.yml, .github/workflows/publish-1.0-docs.yml, .github/workflows/publish-1.0-nightly.yml, .github/workflows/publish-1.1-docs.yml, .github/workflows/publish-1.1-nightly.yml, .github/workflows/publish-nightly.yml, .github/workflows/scala3-build.yml, .github/workflows/timing-tests.yml, project/PekkoDevelocityPlugin.scala
This PR migrates the Pekko project to publish Build Scans to the the new Develocity instance at develocity.apache.org.
=> Publish build scans to develocity.apache.org

actor/src/main/scala/org/apache/pekko/actor/LightArrayRevolverScheduler.scala, actor/src/main/scala/org/apache/pekko/actor/RepointableActorRef.scala, actor/src/main/scala/org/apache/pekko/actor/dungeon/Children.scala, actor/src/main/scala/org/apache/pekko/actor/dungeon/Dispatch.scala, actor/src/main/scala/org/apache/pekko/dispatch/AbstractDispatcher.scala, actor/src/main/scala/org/apache/pekko/dispatch/Mailbox.scala, actor/src/main/scala/org/apache/pekko/pattern/AskSupport.scala, actor/src/main/scala/org/apache/pekko/pattern/CircuitBreaker.scala, remote/src/main/scala/org/apache/pekko/remote/artery/Association.scala
Motivation:
Make code compiles on JDK 23
refs: https://github.com/apache/pekko/issues/1725
Modification:
Add @nowarn("cat=deprecation")
Result:
Tested locally, it compiles now
=> chore: Make code compiles on JDK 23

actor-tests/src/test/scala-jdk21-only/org/apache/pekko/dispatch/VirtualThreadPoolDispatcherSpec.scala, actor/src/main/scala/org/apache/pekko/dispatch/AbstractDispatcher.scala, actor/src/main/scala/org/apache/pekko/dispatch/VirtualThreadSupport.scala, docs/src/main/paradox/dispatchers.md, docs/src/main/paradox/typed/dispatchers.md, project/PekkoBuild.scala
Motivation:
Test the actor is running on virtual threads.
=> chore: Proper test virtual thread dispatcher and update doc.

actor/src/main/scala/org/apache/pekko/dispatch/AbstractDispatcher.scala, actor/src/main/scala/org/apache/pekko/dispatch/VirtualThreadSupport.scala, actor/src/main/scala/org/apache/pekko/dispatch/VirtualizedExecutorService.scala
Motivation:
`LoadMetrics` is needed in `BalancingDispatcher`, which is missing.
Modification:
Add `LoadMetrics` in the virtual thread executor.
with:
```scala
[WARN] [01/20/2025 02:35:27.497] [VirtualThreadPoolDispatcherSpec-pekko.actor.internal-dispatcher-3] [VirtualThreadExecutorConfigurator] 
Failed to get the default scheduler of virtual thread, so the `LoadMetrics` is not available when using it with `BalancingDispatcher`.
Add `--add-opens java.base/java.lang=ALL-UNNAMED` to the JVM options to help this.
```
=> feat: Add LoadMetrics support for virtual thread executor.

docs/src/main/paradox/typed/dispatchers.md, docs/src/test/scala/docs/dispatcher/DispatcherDocSpec.scala
Motivation:
fix https://github.com/apache/pekko/issues/1735
Modification:
Add doc
=> chore: Add doc about virtual thread executor.

actor-tests/src/test/scala-jdk21-only/org/apache/pekko/dispatch/ForkJoinPoolVirtualThreadSpec.scala, actor/src/main/resources/reference.conf, actor/src/main/scala/org/apache/pekko/dispatch/AbstractDispatcher.scala, actor/src/main/scala/org/apache/pekko/dispatch/ForkJoinExecutorConfigurator.scala, actor/src/main/scala/org/apache/pekko/dispatch/ThreadPoolBuilder.scala, actor/src/main/scala/org/apache/pekko/dispatch/VirtualThreadSupport.scala, actor/src/main/scala/org/apache/pekko/dispatch/VirtualizedExecutorService.scala, docs/src/main/paradox/dispatchers.md, docs/src/main/paradox/typed/dispatchers.md, docs/src/test/scala/docs/dispatcher/DispatcherDocSpec.scala, project/JdkOptions.scala
Motivation:
Enhances the current virtual thread support which can switch the virtual threads' scheduler.
Modification:
Use the method handle to change the scheduler of virtual threads.
1. when virtualization is on, the forkJoinPool will create a `CarrierThread`
2. and then all actors run on a virtual threads.
3. when virtualization is off, the actors run on the old PekkoForkJoinWorkerThread.
Result:
Virtualization with virtual threads supported.
We have a user case at $Work, where we are pulling data from a blocking API, With this, I think we can then decrease the Threads number.
based on https://github.com/apache/pekko/pull/1734
=> feat: Enhance virtual thread support 

stream-tests/src/test/scala/org/apache/pekko/stream/impl/TraversalBuilderSpec.scala, stream/src/main/scala/org/apache/pekko/stream/impl/TraversalBuilder.scala
Motivation:
The EmptySource should be added to the cases too.
extracted from https://github.com/apache/pekko/pull/1701#discussion_r1929190034
Modification:
Add EmptySource to match
=> chore: Add the missing EmptySource case to TraversalBuilder

stream-tests/src/test/scala/org/apache/pekko/stream/impl/TraversalBuilderSpec.scala, stream/src/main/scala/org/apache/pekko/stream/impl/TraversalBuilder.scala
(cherry picked from commit ba639f68a2eebb521e01879f584d2f682a7934eb)
=> chore: Add the missing EmptySource case to TraversalBuilder (#1743)

stream-testkit/src/main/mima-filters/1.1.1.backwards.excludes/pr-1468-override-timeout-stream-testkit.backwards.excludes, stream-testkit/src/main/scala/org/apache/pekko/stream/testkit/javadsl/StreamTestKit.scala, stream-testkit/src/main/scala/org/apache/pekko/stream/testkit/scaladsl/StreamTestKit.scala, stream-testkit/src/test/scala/org/apache/pekko/stream/testkit/StreamConfiguration.scala, stream-testkit/src/test/scala/org/apache/pekko/stream/testkit/StreamSpec.scala
The context of this change is https://github.com/apache/pekko-http/pull/590#pullrequestreview-2281514043. It turns out its extremely cumbersome to manually override the duration so I am adding this public method
@raboof @jrudolph Let me know if this line of thinking is on the right lines.
=> Add overridden duration timeout to StreamTestKit

.github/workflows/nightly-builds.yml, .github/workflows/verify-jdk9-classes.sh, project/VerifyJDK9Classes.scala
* the CI action is not yet approved by ASF Infra team
* The main fix is to have the license header in the generated script appear after the CLI directives for the scala version and imports.
* fixes #1751
=> [CI] fix issue with running scala-cli scripts

persistence-testkit/src/main/scala/org/apache/pekko/persistence/testkit/query/javadsl/PersistenceTestKitReadJournal.scala, persistence-testkit/src/test/scala/org/apache/pekko/persistence/testkit/query/EventsByTagSpec.scala
=> add EventsByTagQuery to JavaDSL PersistenceTestKitReadJournal

docs/src/main/paradox/release-notes/index.md, docs/src/main/paradox/release-notes/releases-1.2.md
=> release notes for 1.2.0-M1

persistence-testkit/src/main/scala/org/apache/pekko/persistence/testkit/query/javadsl/PersistenceTestKitReadJournal.scala, persistence-testkit/src/test/scala/org/apache/pekko/persistence/testkit/query/EventsBySliceSpec.scala
* fixes #1766
* just adds a basic test that uses Java DSL but that doesn't replicate all the Scala DSL tests (since the Java DSL just delegates to the Scala DSL implementation)
=> Implement EventsBySliceQuery in PersistenceTestKitReadJournal (java dsl)

stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowStatefulMapSpec.scala, stream-typed-tests/src/test/scala/org/apache/pekko/stream/MapAsyncPartitionedSpec.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala
Motivation:
To avoid https://github.com/apache/pekko/issues/1525 , I checked all the `Flow#withAttributes` usage.
Modification:
Move the `.withAttributes()` inside the `via(...)`
Result:
1. consistent style
2. safer when using it with graphdsl.
=> chore: Tweak withAttributes in Flow

stream-tests/src/test/scala/org/apache/pekko/stream/impl/TraversalBuilderSpec.scala, stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowFlattenMergeSpec.scala, stream/src/main/scala/org/apache/pekko/stream/impl/FailedSource.scala, stream/src/main/scala/org/apache/pekko/stream/impl/JavaStreamSource.scala, stream/src/main/scala/org/apache/pekko/stream/impl/TraversalBuilder.scala
Motivation:
Add helper method to extract the value presented graph which will enable future optimization.
which is needed in https://github.com/apache/pekko/issues/1672
Modification:
Add TraversalBuilder.getValuePresentedSource method
Result:
TraversalBuilder.getValuePresentedSource internal method added
=> feat: Add TraversalBuilder.getValuePresentedSource method for further optimization

stream-tests/src/test/scala/org/apache/pekko/stream/impl/GraphStageLogicSpec.scala, stream/src/main/scala/org/apache/pekko/stream/stage/GraphStage.scala
Motivation:
Add Spliterator support for emitMulti, reducing overhead when working with java stream.
Result:
less overhead
I would like rebase https://github.com/apache/pekko/pull/1775 on this.
=> feat: Add emitMulti with Spliterator support

actor-tests/src/test/java/org/apache/pekko/pattern/PatternsTest.java, actor-tests/src/test/scala/org/apache/pekko/pattern/PatternSpec.scala, actor/src/main/scala/org/apache/pekko/pattern/FutureTimeoutSupport.scala, actor/src/main/scala/org/apache/pekko/pattern/Patterns.scala
Motivation:
refs: https://github.com/apache/pekko/issues/1359
still wip, test is missing
=> feat: Add Pattern timeout support

stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowRecoverWithSpec.scala, stream/src/main/scala/org/apache/pekko/stream/impl/fusing/Ops.scala
Motivation:
refs： https://github.com/apache/pekko/issues/1663
Result:
Avoid some materialization.
=> chore: optimize recoverWith to avoid some materialization

stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/HubSpec.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Hub.scala
Motivation:
Fix https://github.com/apache/pekko/issues/1739 
as [anpin](https://github.com/anpin) just did。
Modification:
Handle the `NormalShutdownReason` as a normal complementation.
=> chore: Handle NormalShutdownReason in MergeHub

docs/src/main/paradox/typed/cluster-singleton.md
* relates to https://github.com/akka/akka/issues/27705 - closed but the docs were not updated
* and https://github.com/apache/pekko/discussions/1786
* the link to the issue is broken because it generates one pointing to Pekko issues not Akka issues
* I don't see a need to raise an issue to provide actual documentation here - if someone wants to provide it, they can but I don't think logging an issue will encourage that
=> remove incomplete section in cluster-singleton.md

docs/src/main/paradox/stream/operators/Source-or-Flow/switchMap.md, docs/src/main/paradox/stream/operators/index.md, stream-tests/src/test/java/org/apache/pekko/stream/javadsl/FlowTest.java, stream-tests/src/test/java/org/apache/pekko/stream/javadsl/SourceTest.java, stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowSwitchSpec.scala, stream/src/main/scala/org/apache/pekko/stream/impl/Stages.scala, stream/src/main/scala/org/apache/pekko/stream/impl/fusing/Switch.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Flow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SubFlow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SubSource.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala
=> feat: Add switchMap operator

bench-jmh/src/main/scala/org/apache/pekko/stream/FlatMapConcatBenchmark.scala, stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowFlatMapConcatParallelismSpec.scala, stream/src/main/scala/org/apache/pekko/stream/impl/Stages.scala, stream/src/main/scala/org/apache/pekko/stream/impl/fusing/FlattenConcat.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Flow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SubFlow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SubSource.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala
Motivation:
Add support for https://github.com/apache/pekko/issues/1672
Based on: https://github.com/apache/pekko/pull/1701
Modification:
1. Add flatmapConcat with parallelism
2. add optimization to avoid materialization at the same time.
Result:
1. flatmapConcat with parallelism supported
Benchmark:
```scala
[info] Benchmark                                       Mode  Cnt         Score         Error  Units
[info] FlatMapConcatBenchmark.completedFuture         thrpt    5   1045035.962 ±   95438.439  ops/s
[info] FlatMapConcatBenchmark.completedFutureP1       thrpt    5  10200822.173 ±  506488.622  ops/s
[info] FlatMapConcatBenchmark.internalSingleSource    thrpt    5  17561424.472 ± 2469846.548  ops/s
[info] FlatMapConcatBenchmark.internalSingleSourceP1  thrpt    5  17434317.937 ± …
```
=> feat: Add flatmapConcat with parallelism support

project/Dependencies.scala
* upgrading netty in 1.1.x branch in anticipation of 1.1.4 release
* includes fix for CVE-2025-24970
* main branch uses 4.2.1 but it seems best not to risk a non-patch upgrade in a Pekko patch release
=> upgrade to netty 4.1.121 due to CVE-2025-24970

cluster/src/test/scala/org/apache/pekko/cluster/MixedProtocolClusterSpec.scala
Tidier to test with the compat check enabled.
Also renamed one test because it doesn't involve an Akka node.
=> allow compat check in cluster test

cluster/src/test/scala/org/apache/pekko/cluster/ClusterJoinSpec
This is a new test added in #1861. The compat check should probably not have been disabled.
I will do a separate investigation for the equivalent mixed cluster tests in main and 1.1.x branches (#1865).
The CI issue is an unrelated link validation issue.
=> enable compatibility check in cluster test

actor/src/main/scala/org/apache/pekko/util/ConstantFun.scala, docs/src/main/paradox/stream/operators/Source-or-Flow/dropRepeated.md, docs/src/main/paradox/stream/operators/index.md, docs/src/test/java/jdocs/stream/operators/SourceOrFlow.java, docs/src/test/scala/docs/stream/operators/sourceorflow/Filter.scala, stream-tests/src/test/java/org/apache/pekko/stream/javadsl/SourceTest.java, stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowDropRepeatedSpec.scala, stream/src/main/scala/org/apache/pekko/stream/impl/Stages.scala, stream/src/main/scala/org/apache/pekko/stream/impl/fusing/DropRepeated.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Flow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SubFlow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/SubSource.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Flow.scala
Motivation:
Add dropRepeated stream operator.
refs: https://github.com/apache/pekko/issues/1662
=> feat: Add dropRepeated stream operator.

.github/workflows/nightly-builds.yml, cluster-metrics/src/main/scala/org/apache/pekko/cluster/metrics/protobuf/NumberInputStream.scala, cluster-metrics/src/test/scala/org/apache/pekko/cluster/metrics/protobuf/NumberInputStreamSpec.scala
* see #1911 
* reworking the newly added NumberInputStream to allow arrays of primitives (eg arrays of bytes) fixes the issue - that oddly only occurs with Scala 2.12 runtime
=> try to fix broken cluster metrics test

.scala-steward.conf, actor-typed/src/main/scala/org/apache/pekko/actor/typed/internal/LoggerClass.scala, bench-jmh/src/main/scala/org/apache/pekko/util/StackBench.scala, project/Doc.scala, project/Jdk9.scala, project/JdkOptions.scala, project/PekkoBuild.scala, project/TestExtras.scala, project/plugins.sbt, remote/src/test/scala/org/apache/pekko/remote/artery/tcp/ssl/PemManagersProviderSpec.scala, remote/src/test/scala/org/apache/pekko/remote/classic/RemoteInitErrorSpec.scala
* fixes #259
* see also #1967 and #1730 and #1237 
* I plan to follow up with an extra PR to move the Jdk9 code into the main code directories (which looks like a fairly big change because there is a lot of build config associated with this)
=> Remove java8 home and scala steward pins related to java 11 and java 17

.github/workflows/nightly-1.2-builds.yml, .github/workflows/publish-1.2-docs.yml, .github/workflows/publish-1.2-nightly.yml
* we need nightly tests and snapshot publishing for the new 1.2.x branch
* stop running the nightlies for 1.0.x but allow them to still be run manually
=> create jobs to publish 1.2 snapshots

stream-tests/src/test/scala/org/apache/pekko/stream/io/DeprecatedTlsSpec.scala, stream-tests/src/test/scala/org/apache/pekko/stream/io/TlsSpec.scala
* Part of #2000 but there are many other broken tests still
* SessionRenegotiationFirstTwo is still tested and that uses a stronger cipher suite
* SessionRenegotiationFirstOne uses a weak cipher suite, TLS_RSA_WITH_AES_128_CBC_SHA, that no longer seems to work with Java 24
```
javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
[info]   at java.base/sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:162)
[info]   at java.base/sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:103)
```
=> don't test SessionRenegotiationFirstOne on java 24

actor-tests/src/test/java/org/apache/pekko/actor/ActorCreationTest.java, actor-tests/src/test/java/org/apache/pekko/actor/JavaAPI.java, actor-tests/src/test/java/org/apache/pekko/actor/NonStaticCreator.java, actor-tests/src/test/java/org/apache/pekko/dispatch/JavaFutureTests.java, actor-tests/src/test/scala/org/apache/pekko/actor/PropsCreationSpec.scala, actor-tests/src/test/scala/org/apache/pekko/event/EventBusSpec.scala, actor-typed/src/main/mima-filters/2.0.x.backwards.excludes/javaapi-functions.excludes, actor-typed/src/main/scala/org/apache/pekko/actor/typed/javadsl/Adapter.scala, actor-typed/src/main/scala/org/apache/pekko/actor/typed/javadsl/Behaviors.scala, actor/src/main/mima-filters/2.0.x.backwards.excludes/javaapi-functions.excludes, actor/src/main/scala/org/apache/pekko/actor/AbstractProps.scala, actor/src/main/scala/org/apache/pekko/actor/ActorCell.scala, actor/src/main/scala/org/apache/pekko/actor/FaultHandling.scala, actor/src/main/scala/org/apache/pekko/actor/IndirectActorProducer.scala, actor/src/main/scala/org/apache/pekko/dispatch/Future.scala, actor/src/main/scala/org/apache/pekko/japi/JavaAPI.scala, actor/src/main/scala/org/apache/pekko/pattern/Patterns.scala, actor/src/main/scala/org/apache/pekko/serialization/SerializationSetup.scala, docs/src/test/java/jdocs/persistence/LambdaPersistenceDocTest.java, docs/src/test/java/jdocs/stream/GraphStageDocTest.java, docs/src/test/java/jdocs/stream/javadsl/cookbook/RecipeMultiGroupByTest.java, docs/src/test/java/jdocs/stream/operators/source/Restart.java, docs/src/test/java/jdocs/testkit/ParentChildTest.java, persistence/src/main/mima-filters/2.0.x.backwards.excludes/javaapi-functions.excludes, persistence/src/main/scala/org/apache/pekko/persistence/AtLeastOnceDelivery.scala, persistence/src/main/scala/org/apache/pekko/persistence/PersistentActor.scala, persistence/src/test/scala/org/apache/pekko/persistence/TimerPersistentActorSpec.scala, stream/src/main/java/org/apache/pekko/stream/javadsl/JavaFlowSupport.java, stream/src/main/mima-filters/2.0.x.backwards.excludes/javaapi-functions.excludes
Motivation:
refs: https://github.com/apache/pekko/issues/267
Make use of `pekko.japi.function`
=> chore: Migrate to pekko.japi.function

LICENSE, actor-tests/src/test/scala/org/apache/pekko/io/ByteBufferCleanerSpec.scala, actor/src/main/java/org/apache/pekko/io/ByteBufferCleaner.java, actor/src/main/scala/org/apache/pekko/io/DirectByteBufferPool.scala
* see #2019 
* the existing cleaner code will not work in Java 9+
* this new code copied from commons-io will mean that the cleaner works in all Java versions
* the support it needs in sun.misc.Unsafe is deprecated in Java 23 but still exists and should work
* worst case scenario is that Java 23+ users who don't allow sun.misc.Unsafe to work will not get the Cleaner to proactively clean the byte buffers and will need to rely on the Garbage Collector
* I would like to backport this to Pekko 1.2.0
=> use better byte buffer cleaner

persistence/src/main/resources/reference.conf, persistence/src/main/scala/org/apache/pekko/persistence/journal/AsyncWriteJournal.scala, persistence/src/test/scala/org/apache/pekko/persistence/journal/AsyncWriteJournalResponseOrderSpec.scala
https://github.com/apache/pekko/issues/2026
I left the previous behaviour to be the default one, just in case, but I think that eventually AsyncWriteJournal.Resequencer should be removed.
Please, double check the wording on the reference.conf config option. Also I'm not sure whether I need to update the documentation and where should I update it.
=> Add AsyncWriteJournal option for disabling Resequencer (#2026)

remote/src/main/mima-filters/1.1.x.backwards.excludes/quarantine.backwards.excludes, remote/src/main/resources/reference.conf, remote/src/main/scala/org/apache/pekko/remote/artery/ArterySettings.scala, remote/src/main/scala/org/apache/pekko/remote/artery/ArteryTransport.scala, remote/src/main/scala/org/apache/pekko/remote/artery/Association.scala, remote/src/main/scala/org/apache/pekko/remote/artery/InboundQuarantineCheck.scala, remote/src/test/scala/org/apache/pekko/remote/artery/HarmlessQuarantineSpec.scala, remote/src/test/scala/org/apache/pekko/remote/artery/OutboundIdleShutdownSpec.scala
backport add non-default config that allows InboundQuarantineCheck to ignore 'harmless' quarantine events (#1555)
cherry picks ec5e33fdb944305b709ba784166a438493fec497
=> backport add non-default config that allows InboundQuarantineCheck to ignore 'harmless' quarantine events (#1555)

docs/src/main/paradox/stream/operators/Source-or-Flow/onErrorResume.md, docs/src/main/paradox/stream/operators/index.md, stream-tests/src/test/java/org/apache/pekko/stream/javadsl/FlowTest.java, stream-tests/src/test/java/org/apache/pekko/stream/javadsl/SourceTest.java, stream-tests/src/test/scala/org/apache/pekko/stream/DslConsistencySpec.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Flow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala
Motivation:
refs: https://github.com/apache/pekko/issues/2116
The current `recoverWith` is using a Scala partial function, which is hard to use from the Java side, with this, we can achieve the same as `reactor-core/rxjava` friendly to Java developers.
The `onErrorComplete` and `onErrorResume` are widely used in MCP Java SDK.
Modification:
1. Add `onErrorResume` operator to both Source and Flow, javadsl only
2. Adjust the current FlowTest, which was testing the Source dsl, but now Flow DSL.
3. Add both Flow and Source testing for `onErrorResume` and `onErrorComplete`
Result:
Easy to use for Java developers.
=> feat: Add Flow/Source#onErrorResume for javadsl.

stream/src/main/scala/org/apache/pekko/stream/javadsl/Flow.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Source.scala
(cherry picked from commit 617d1c5faa633c25c149b6a85401fa288a05ea5c)
=> chore: Remove the deprecated annotation from recoverWith (#2119)

stream/src/main/mima-filters/2.0.x.backwards.excludes/remove-deprecated-methods.excludes, stream/src/main/scala/org/apache/pekko/stream/stage/GraphStage.scala
Motivation:
This method should and can be removed completely, it was deprecated.
Modification:
Remvoe the private onDownstreamFinish method
Result:
Clean code and better performance.
=> chore: Remove the deprecated onDownstreamFinish method in GraphStage

bench-jmh/src/main/scala/org/apache/pekko/util/ByteString_indexOf_Benchmark.scala, bench-jmh/src/main/scala/org/apache/pekko/util/ByteString_lastIndexOf_Benchmark.scala
* existing indexOf benchmarks don't include checks for the indexOf(Byte) method
* add lastIndexOf benchmarks
=> extend ByteString benchmarks

stream/src/main/scala/org/apache/pekko/stream/ActorMaterializer.scala
Motivation:
Make it a lazy val to cache the value.
=> chore: make toAttributes a lazy val

actor/src/main/scala/org/apache/pekko/dispatch/ThreadPoolBuilder.scala
Motivation:
This should be an internal api
refs: https://github.com/apache/pekko/issues/2171
=> chore: Make ThreadPoolConfig an internal api

actor/src/main/java/org/apache/pekko/japi/function/IntFunction.java, actor/src/main/java/org/apache/pekko/japi/function/package-info.java, actor/src/main/mima-filters/2.0.x.backwards.excludes/javaapi-functions.excludes, actor/src/main/scala/org/apache/pekko/pattern/Patterns.scala, docs/src/test/java/jdocs/future/FutureDocTest.java
Motivation:
Make use of japi.funtion.* in Patterns
refs: https://github.com/apache/pekko/issues/2197
=> chore: Make use of japi.funtion.* in Patterns

project/Dependencies.scala, project/OSGi.scala
Motivation:
remove scala.compat.java8 in osgi
=> chore: remove scala.compat.java8 in osgi

actor-tests/src/test/java/org/apache/pekko/japi/ThrowablesTest.java, actor/src/main/scala/org/apache/pekko/japi/Throwables.scala
Motivation:
When lambda doesn't support throwing exceptions, but the method we want to use declares that it throws exceptions, we can use this method to support it, similar to lombok's @sneakyThrows.
Usage:
```java
() -> {
try {
.....// can throw
} catch(Throwable e) {
Throwables.sneakThrow(e)
}
}
```
=> feat: Add sneakyThrow for Java

.scalafix.conf, project/ScalaFixExtraRulesPlugin.scala
I tested `sbt sortImports`and the com.sandinh/scala-rewrites plugin makes no difference.
=> remove unnecessary scalafix plugin

LICENSE, NOTICE, legal/pekko-actor-jar-license.txt, legal/pekko-actor-jar-notice.txt
* the 3rd party code that we copied from scala-collection-compat has been removed
* likewise the Scala library borrowings only now apply to Helpers.scala
=> remove unnecessary items from license

docs/src/main/paradox/stream/operators/Sink/count.md, docs/src/main/paradox/stream/operators/index.md, docs/src/test/java/jdocs/stream/operators/SinkDocExamples.java, stream-tests/src/test/java/org/apache/pekko/stream/javadsl/SinkTest.java, stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/SinkSpec.scala, stream/src/main/scala/org/apache/pekko/stream/impl/Stages.scala, stream/src/main/scala/org/apache/pekko/stream/impl/fusing/CountSink.scala, stream/src/main/scala/org/apache/pekko/stream/javadsl/Sink.scala, stream/src/main/scala/org/apache/pekko/stream/scaladsl/Sink.scala
Motivation:
refs: https://github.com/apache/pekko/issues/2182
=> feat: Add Sink#count operator.

actor-tests/src/test/scala/org/apache/pekko/actor/ActorSystemSpec.scala, actor-tests/src/test/scala/org/apache/pekko/event/LoggingReceiveSpec.scala, actor/src/main/scala-2.13/org/apache/pekko/util/ByteString.scala, actor/src/main/scala/org/apache/pekko/actor/Address.scala, actor/src/main/scala/org/apache/pekko/util/FrequencySketch.scala, persistence/src/main/scala/org/apache/pekko/persistence/Eventsourced.scala, remote/src/main/scala/org/apache/pekko/remote/artery/Control.scala, stream/src/main/scala/org/apache/pekko/stream/impl/QueueSource.scala, stream/src/main/scala/org/apache/pekko/stream/impl/SetupStage.scala, stream/src/main/scala/org/apache/pekko/stream/impl/Sinks.scala, stream/src/main/scala/org/apache/pekko/stream/impl/io/TcpStages.scala, testkit/src/test/scala/org/apache/pekko/testkit/metrics/MetricsKit.scala
* see #2254
* tested with latest pre-release nightly for scala 2.13.17
* these may not be the only issues
=> silence compiler warnings new in scala 2.13.17

.asf.yaml
cherry pick 91554a46db54de1c76bf03c9cb0379fa05a8f45b
something that we can tag as v1.3..0-M0 to ensure that snapshots end up with 1.3 versions
=> protect 1.3.x branch (#2264)

actor-tests/src/test/scala/org/apache/pekko/util/ByteStringSpec.scala
ByteString inherits these from Scala Seq.
They are used in pekko-http.
=> add containsSlice/indexOfSlice tests

testkit/src/main/scala/org/apache/pekko/testkit/javadsl/TestKit.scala, testkit/src/test/java/org/apache/pekko/testkit/javadsl/TestKitApiTest.java
* fixes #2226
* Aim is to backfit to 1.3.0.
* The shutdownActorSystem code has long accepted Scala Durations - the duration is optional. So it hasn't caused too many problems so I, personally, am not too pushed about removing the old methods that allow Scala Duration params. I don't see why we can't support both.
=> JavaDSL TestKit - add shutdownActorSystem that takes Java Duration params

stream/src/main/scala/org/apache/pekko/stream/impl/fusing/SourceSink.scala
Nightly doc build has failed for a few days - e.g. https://github.com/apache/pekko/actions/runs/18082049707
```
[error] /home/runner/work/pekko/pekko/stream/src/main/scala/org/apache/pekko/stream/impl/fusing/SourceSink.scala:50:5: discarding unmoored doc comment
[error] Applicable -Wconf / @nowarn filters for this fatal warning: msg=<part of the message>, cat=lint-doc-detached
[error]     /**
[error]     ^
[error] one error found
```
=> try to fix doc build issue

project/Dependencies.scala
* I'm not sure if this should be delayed till 2.0.0-M2.
* aim is to upgrade dependencies first
* we probably then want to upgrade docs and rename some classes - possibly retaining the Junit5 prefixed class names as synonyms of the new Junit6 classes
=> jupiter junit 6

CONTRIBUTING.md, README.md
Removed the requirement for Java 11 minimum from the documentation. The docs already mention Java 17 min so this Java 11 mention is actually incorrect.
=> Update README to remove Java 11 requirement
